### ISSUE TITLE
configure docker image mirroring to other registries for use in private kubernetes clusters

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1090]
so we can support private GKE clusters that can't see docker hub.

similar to #843 we need a way to configure mirroring of docker images to other registries

**Comment by mgrzybek** [comment]
In order to do it simply, we can add a prefix for each container name we create using an environment variable.

**Comment by AdilusPrimus** [comment]
Hi it is written here that Google's Container Registry mirrors public Docker Hub images that are frequently requested by Container Registry users: https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring.
It seems that the problem here is that Jenkins X tries to pull images from another repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
Is there a way to refer to images from the Docker Hub repo so we could retrieve those automatically from the Google Container Registry?
When deploying K8s clusters in a GCP private network, we only have an automatically defined access to the Google's Container Registry and if the required images were published on Docker Hub's repos they technically would have been pulled in the GCP's Docker repo.
