### ISSUE TITLE
How to get this to display after Jenkins X installation completed successfully

### ISSUE THREAD

**Issue by scheung38** [jenkins-x/jx#1130]
What is the command to list this, (as shown in demo video) but no longer showing now after a successful cluster gke creation:

<img width="493" alt="screen shot 2018-06-24 at 16 45 16" src="https://user-images.githubusercontent.com/1273014/41820229-670d66c2-77ce-11e8-98a2-2c9c1011b696.png">

http://jenkins.jx.35.195.85.51.nip.io/ - ok
http://nexus.jx.35.195.85.51.nip.io/ - ok
http://monocular.jx.35.195.85.51.nip.io/ - ok

http://kubernetes-dashboard.jx.35.195.85.51.nip.io/ - 404
http://chartmuseum.jx.35.195.85.51.nip.io/ - 404
http://docker-registry.jx.35.195.85.51.nip.io/ - 401 Unauthorized

Any idea why the last 3 services are not found or not authorized?

**Comment by jstrachan** [comment]
btw we don't include kube dashboard inside Jenkins X any more due to security. We hope to add it back some day when we've Dex + RBAC sorted.

For chart museum try querying the `/api/charts` path? e.g. this works for me: http://chartmuseum.jx.35.195.85.51.nip.io/api/charts

similarly for docker registry try `/v2` : http://docker-registry.jx.35.195.85.51.nip.io/v2/

**Comment by rafaelpolo19** [comment]
The same thing happens to me, some solution?
http://monocular.jx.192.168.99.114.nip.io/ - ok
http://monocular.jx.192.168.99.114.nip.io/ - ok

http://jenkins.jx.192.168.99.114.nip.io/ -
default backend - 404
