### ISSUE TITLE
"jx get env" returns dev, staging, and production. Then why doesn't "jx get apps" show dev?

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#1141]
Junis-MacBook-Pro:nodejenx juni$ jx get env
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER SOURCE                                                              REF PR
dev        Development Development Never   jx            0                                                                                     
staging    Staging     Permanent   Auto    jx-staging    100           https://github.com/junibutler/environment-bitermaple-staging.git        
production Production  Permanent   Manual  jx-production 200           https://github.com/junibutler/environment-bitermaple-production.git     

Junis-MacBook-Pro:nodejenx juni$ jx get apps
APPLICATION STAGING PODS URL                                                        PRODUCTION PODS URL
goagainjenx 0.0.1   1/1  http://goagainjenx.jx-staging.35.203.177.62.nip.io                         
gojenx      0.0.8   1/1  http://jx-staging-gojenx.jx-staging.35.203.177.62.nip.io   0.0.7      1/1  http://jx-production-gojenx.jx-production.35.203.177.62.nip.io
nodejenx    0.0.3   1/1  http://jx-staging-nodejenx.jx-staging.35.203.177.62.nip.io 0.0.3      1/1  http://jx-production-nodejenx.jx-production.35.203.177.62.nip.io

The CloudBees CD for Kubernetes app seems to not show "dev" either. 

I have a couple of apps (android) where builds are failing (due to known issues). These are not reported since they never made it to staging. The apps that are failing on dev are just as interesting as the ones on staging and production from a deployment throughout standpoint. If you agree, why did we leave them out?

**Comment by jstrachan** [comment]
so we run builds in the `dev` namespace but we typically never deploy them as external URLs which is why they don't show up in the `jx get apps`

**Comment by jstrachan** [comment]
if you use DevPods then those apps show up too in `jx get apps` btw: https://jenkins-x.io/developing/devpods/

**Comment by junibutler** [comment]
okay, thanks. ideally, we should use devpods. but at the end of the day, it is up to the teams. (yet another governance thing...how can we enforce best practices?).

if they choose not to do so, i sill feel they should have a view of build and test failures in the dev/test environment. simply because, there could be an unhealthy drag in dev/test, where a lot of apps might be lying broken. ones that haven't made it to staging for some time, but are flying under the radar.

from a business standpoint, the cloudbees cd for k8s app should throw light on that is my understanding. please let me know if you think otherwise. 

from a technical standpoint, i don't know if deploying the dev namespace as external URLs is a challenge, or we didn't do it only because it's not a priority.

**Comment by rawlingsj** [comment]
> if they choose not to do so, i sill feel they should have a view of build and test failures in the dev/test environment. simply because, there could be an unhealthy drag in dev/test, where a lot of apps might be lying broken. ones that haven't made it to staging for some time, but are flying under the radar.

You can view the build logs for any app when in the dev environment by running `jx get build logs`, but there are no applications actually running in dev environment, just the build tools like Jenkins, Nexus etc.  The first environment an application is deployed to from a pipeline after a change is merged is by default staging which is why you only see apps in staging and production.  I.e. this is working as expected.


> from a business standpoint, the cloudbees cd for k8s app should throw light on that is my understanding. please let me know if you think otherwise.

Yes but we probably ought to keep CloudBees specific discussions away from the OSS project.

> from a technical standpoint, i don't know if deploying the dev namespace as external URLs is a challenge, or we didn't do it only because it's not a priority.

There is no application deployment in the dev environment, applications only run in Preview, Edit, Staging and Production environments.  We did talk about renaming the `dev` environment to be `home` or something which might help avoid confusion?

**Comment by sdoxsee** [comment]
I hope I'm not hijacking this issue but I've run `jx create devpod` and I'm able to get into the pod and build it with `skaffold dev -p dev` but I never see the URL i can visit to view my devpod deployed.

```
Stephens-MacBook-Pro:demo2 sdoxsee$ jx get apps
APPLICATION EDIT PODS URL STAGING PODS URL                                         PRODUCTION PODS URL
demo2                     0.0.2   1/1  http://demo2.jx-staging.35.203.18.88.nip.io 0.0.2      1/1  http://demo2.jx-production.35.203.18.88.nip.io
Stephens-MacBook-Pro:demo2 sdoxsee$ jx get environments
NAME       LABEL       KIND        PROMOTE NAMESPACE       ORDER CLUSTER SOURCE                                                              REF PR
dev        Development Development Never   jx              0
sdoxsee    sdoxsee     Edit        Never   jx-edit-sdoxsee 1
staging    Staging     Permanent   Auto    jx-staging      100           https://github.com/sdoxsee/environment-grabbernebula-staging.git
production Production  Permanent   Manual  jx-production   200           https://github.com/sdoxsee/environment-grabbernebula-production.git
Stephens-MacBook-Pro:demo2 sdoxsee$ jx create devpod --reuse
Reusing pod sdoxsee-maven - waiting for it to be ready...
Pod sdoxsee-maven is now ready!
You can open other shells into this DevPod via jx create devpod --reuse
[root@sdoxsee-maven code]# ls
Dockerfile  Jenkinsfile  charts  mvnw  mvnw.cmd  pom.xml  skaffold.yaml  src
[root@sdoxsee-maven code]#
```

I can create a new issue if necessary but seeing as this issue is so fresh and is related to "viewing what you're developing" and follows the [suggestion](https://github.com/jenkins-x/jx/issues/1141#issuecomment-400261573) above, I though I would hop on this one. Thanks!
