### ISSUE TITLE
jx cannot handle KUBECONFIG pointing to a list of paths with a : separator

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1169]
so we should split by the path separator on the platform and try find the first one that exists instead

**Comment by rgauss** [comment]
I don't have the context of exactly what it's doing there, but shouldn't it be able to parse all of them and obey the `kubectl` `current-context`?

**Comment by rgauss** [comment]
While the fix is very much appreciated, if I'm reading the code right this is just picking the first one and won't be expected be the expected behavior for developers who use `kubectl config use-context <context>`.

IMHO, jx should use whatever kubectl has been configured to use which would mean obeying `current-context`.

One way to dump the contents of the current config would be:
```
kubectl config current-context | kubectl config view
```
