### ISSUE TITLE
Failed to read artifact descriptor with devel-SNAPSHOT dependencies

### ISSUE THREAD

**Issue by adomenech73** [jenkins-x/jx#1200]
Whenever I try to build a java project with devel-SNAPSHOT dependencies on its pom.xml I get `Failed to read artifact descriptor` even if the dependency exists on nexus.

When dependencies are not loaded in nexus I get `Could not find artifact` message instead

This doesn't happen with Release dependencies

**Comment by rawlingsj** [comment]
My guess is the maven settings.xml in the `jx` namespace doesn't have the nexus snapshot repo configured.  FWIW we recommend not depending on SNAPSHOT dependencies for maven projects.  SNAPSHOTS can be GC'd and you never quite know where you are with them. 

If you are in a team that needs to build and test a project with a library from another team before they release it we tend to use versions built from a Jenkins X preview environment instead of traditional SNAPSHOTS.  These are similar except they are versioned to include the PR and Build number.  I.e. you can change https://github.com/jenkins-x/draft-packs/blob/master/packs/maven/Jenkinsfile#L23 to `mvn deploy` and that will deploy to nexus where your pom can then pull from nexus.
