### ISSUE TITLE
provide better UX when folks get a 500 creating jenkins client

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1234]
A common problem that gets raised on slack is when folks get `error: error creating jenkins credential jenkins-x-chartmuseum 500 Server Error` when running some commands like `jx import`.  

Perhaps we can catch this error and provide better UX that helps recreate the token?

**Comment by rawlingsj** [comment]
Perhaps deleting the server entry in the `~/.jx/jenkinsAuth.yaml` on install is enough?

**Comment by jstrachan** [comment]
added to the FAQ until we figure out a fix https://jenkins-x.io/faq/issues/#error-creating-jenkins-credential-jenkins-x-chartmuseum-500-server-error

**Comment by Benbentwo** [comment]
I had a similar issue after setting up my Jenkins Pod to default use GitHub Enterprise instead of Jenkins auth, meaning I could not login to jenkins via admin and global password because I immediately got redirected to my github login page.

<details>
    <summary>Looking at a few different sources I pieced together my solution to allow import again</summary>

---
Run:

```shell
jx import --git-provider-url=https://github.<someCompany>.com/ --org <someOrg> --filter <someApp>
```

if given a 403 or 500, likely due to `~/.jx/jenkinsAuth.yaml` being configured wrong. due to GHE auth being installed
for each user in that file, run

```shell
jx delete jenkins token <probablyBadUser>
```

until the user section of the file is `[]`.

Then run the import command again, for **jenkins** user name, it's found after logging into jx, look in Jenkins -> people -> userID

For the token click show legacy token from `http://<jenkinsUrl>/me/configure`
Then Proceed with your GHE credentials

---

I should note, my solution might be a little more home-brew as I have Plugins not being cleaned up on Jenkins restart.

</details>
