### ISSUE TITLE
jx quickstart application fail to push docker-registry

### ISSUE THREAD

**Issue by angegar** [jenkins-x/jx#1243]
### Summary 
When i submit a commit my pipeline fail during the push to docker registry

### Steps to reproduce the behavior
Just push a commit from my application

### Jx version
NAME               VERSION
jx                 1.3.75
jenkins x platform 0.0.1759
kubernetes cluster v1.9.6
kubectl            v1.10.5
git                git version 2.17.0

### Kubernetes cluster provider / Version
Client Version: v1.10.5
Server Version: v1.9.6

### Operating system / Environment
Windows 10 with LSS (Ubuntu 18.04)

### Expected behavior
Commit push to docker registry and pipeline succeed as i am just running the quickstart

### Actual behavior
Pipeline fail with :

```
The push refers to a repository [100.71.203.90:5000/lgil3/jx-test-app]
time="2018-07-09T21:18:31Z" level=fatal msg="build step: pushing [100.71.203.90:5000/lgil3/jx-test-app:0.0.2]: Get https://100.71.203.90:5000/v1/_ping: http: server gave HTTP response to HTTPS client"
```

### Additional information

My k8s cluster was installed with KOPS and the helm client was already there.

**Comment by jstrachan** [comment]
I've added this to the FAQ along with workarounds as folks hit this fairly frequently: https://jenkins-x.io/faq/issues/#http-server-gave-http-response-to-https-client

**Comment by angegar** [comment]
I read this into the setup guide and i already edit my k8x configuration :

![image](https://user-images.githubusercontent.com/5628764/42569018-71d858b6-850f-11e8-9325-3f715a6c3bd8.png)
 
May be the configuration was not correctly applied, i will try kop update cluster --yes once again.

**Comment by ccojocar** [comment]
Closing this since a workaround is documented.

**Comment by bartoliniii** [comment]
Because I've spent a couple of hours trying to solve the issue with an insecure registry, I'll leave my solution here.

Problem (for the current version of jx) was related to tekton build that uses [kaniko/executor](https://github.com/GoogleContainerTools/kaniko). To force kaniko to work with http registry, you have to add `kanikoFlags: "--insecure"` to your jx-requirements.yml (like [here](https://jenkins-x.io/v3/develop/faq/config/general/#how-do-i-configure-kaniko-flags))

@jstrachan I think it should be very useful to add information about that step to official jx documentation (I assume, that plenty of people lost days trying to find the way ho to build an image for quickstart project, and probably some of them gave up ).
