### ISSUE TITLE
install  err 

### ISSUE THREAD

**Issue by McDingl** [jenkins-x/jx#1262]
** install JX on  existing k8s cluster ,architecture below :**

![image](https://user-images.githubusercontent.com/37035429/42563889-edf51ac0-8531-11e8-8c25-d1eabb967a85.png)

my step and output:

1.jx install 

![image](https://user-images.githubusercontent.com/37035429/42563973-20c87b90-8532-11e8-9d5c-5223e222a835.png)

question:

1.how  to specify  my k8s cluster by commond " jx install "?
2. jx  tool  must   on the k8s master ？
3. official could give a  install  step in detail ?

tks , i spend a week to install

**Comment by jstrachan** [comment]
1. to use `jx install` you must be connected to the kubernetes cluster so that you can run `kubectl get namespace` or `kubectl get node`. `jx` uses the same connection mechanism as `kubectl` - so that `~/.kube/config` lists the available contexts or you use `$KUBECONFIG` to point to the kube config to use
2. No, `jx` is only required on the computer used to install or import projects
3. Not sure I understand the question. Detail of jx install here: https://jenkins-x.io/commands/jx_install/
