### ISSUE TITLE
Default Jenkins console when browsed to to be the /blue/ url

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#1276]
### Summary 
`jx open jenkins` does the right thing, but it would be nice if when the user browsed to the root of the console (eg via a bookmark or after logging in fresh) it would then redirect to the blue ocean version of the console.

EDIT: ah yes: https://issues.jenkins-ci.org/browse/JENKINS-46706?focusedCommentId=322092&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322092 was how Tyler did it

**Comment by michaelneale** [comment]
@rawlingsj I know ci.jenkins.io does something with nginx, just for the root (and ideally just for browsers), not sure if in the pod for jenkins there is nginx or similar for jenkins x. May be a trivial one

**Comment by rawlingsj** [comment]
Yeah we use an NGINX ingress controller for all ingress to the cluster.  You can add NGINX ingress annotations to the Jenkins Service so that exposecontroller generates the ingress rule with the correct annotations.  I.e. we do this for monocular 
https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L174

So you can choose from these annotations https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md

And add them like the monocular example to the Jenkins service here https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L232

Then you can recreate the ingress rules with the new CLI I'm going to hopefully merge today which is 
```
jx  upgrade ingress
```

**Comment by ccojocar** [comment]
This seems to be fixed. The `jx console` opens by default the blue URL.
