### ISSUE TITLE
"jx create cluster aws" gives an error

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#1298]
### Steps to reproduce the behavior

Junis-MacBook-Pro:workspace juni$ jx create cluster aws

### Jx version

The output of `jx version` is:

Junis-MacBook-Pro:workspace juni$ jx version
NAME               VERSION
jx                 1.3.88
jenkins x platform 0.0.1436
kubernetes cluster v1.8.10-gke.0
kubectl            v1.10.1
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb
git                git version 2.15.1 (Apple Git-101)
error: Unable to get latest version for github.com/jenkins-x/jx GET https://api.github.com/repos/jenkins-x/jx/releases/latest: 500  []

COPY OUTPUT HERE

Junis-MacBook-Pro:workspace juni$ jx create cluster aws
kops not found
? Missing required dependencies, deselect to avoid auto installing: kops
Downloading https://github.com/kubernetes/kops/releases/download/1.9.1/kops-darwin-amd64 to /Users/juni/.jx/bin/kops.tmp...

Downloaded /Users/juni/.jx/bin/kops.tmp
? nodes 3
error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by secade** [comment]
I ran into this issue yesterday. For me, the issue was with my local AWS configuration. It seems like that specific error is propagated up from `kops` when trying to authenticate to AWS using local settings. Because I'd been messing around with a few different ways to set up k8s on AWS, I decided to nuke my installs and configs for the following CLIs:

* [aws](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html)
* [jx](https://jenkins-x.io/getting-started/install/)
* [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
* [kops](https://github.com/kubernetes/kops)
* [helm](https://docs.helm.sh/using_helm/#installing-helm)

Once I did this, I made sure that my `~/.aws/config` file contained a region setting, then I specified the availability zones as part of the `create cluster` command like so:

```
# ~/.aws/config
[default]
aws_access_key_id = { REDACTED }
aws_secret_access_key = { REDACTED }
region = us-east-2
output = json

# shell command
$ jx create cluster aws --verbose --zones us-east-2a,us-east-2b,us-east-2c
```
The `--verbose` flag was pretty helpful.

**Comment by ccojocar** [comment]
This issue seems to be related to the user setup. I am closing it.
