### ISSUE TITLE
jx import --no-draft=true doesn't create Jenkinsfile

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jx#1511]
I think this is related to #1483 Now with --no-draft no charts or skaffold or Dockerfile is created, which is great. But no Jenkinsfile is created either. Is that the intention? So anyone using --no-draft=true needs to add their own Jenkinsfile?

**Comment by ccojocar** [comment]
Currently, no Jenkinsfile is created if draft is disabled, because the default Jenkinsfile is defined in the build pack. In this case, you will have to define manually the Jenkinsfile in your project.  I am going to close this issue because at the moment, we don't intend to create Jenkinsfile without using a build pack.
