### ISSUE TITLE
newer jx cli doesn't respect --environment-git-owner parameter for staging environment

### ISSUE THREAD

**Issue by rezmuh** [jenkins-x/jx#1601]
### Summary 
I've been using --environment-git-owner parameter in the past but as of recent versions of jx cli, it doesn't pay attention to the parameter for staging environment anymore. production environment is still created correctly on the correct --environment-git-owner.
  
### Steps to reproduce the behavior

```
jx create cluster aws \
--kubernetes-version 1.10.5 \
--cluster-name cdub.tech \
--domain cdub.tech \
--http false \
--tls-acme true \
--default-environment-prefix cdub \
--environment-git-owner coverwatch \
--zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c \
--master-size m4.large \
--nodes 2 \
--node-size m4.large
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.221
jenkins x platform 0.0.2267
kubernetes cluster v1.10.5
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

It is on aws and was created with kops through `jx create cluster aws`

### Operating system / Environment

Arch Linux

### Expected behavior

Per the above command, two environment repos should be on coverwatch/environment-cdub-staging and coverwatch/environment-cdub-production

### Actual behavior
Repo for staging environment is created in rezmuh/environment-cdub-staging (my GitHub username) while the production is still correct, it is at coverwatch/environment-cdub-production

**Comment by affixalex** [comment]
Big ol' +1 to this. I may dig into this further today but a fix would be glorious.

**Comment by affixalex** [comment]
On a perhaps related note, `jx create env` doesn’t seem to be allowing me to select an organization and I think think is likely the underlying issue with not respecting `--environment-git-owner` - a bug in the code for interacting with the GitHub API. I'm not sure about the specifics here, but I'm going to look into it right now.

**Comment by Salaboy** [comment]
I've reported this a while ago.. with a very cryptic title: https://github.com/jenkins-x/jx/issues/1516 is this the same behaviour?

**Comment by i0n** [comment]
Hey there! Perhaps I can lend a hand/get this fixed for you guys.

There has been a bit of an un-going refactor recently around `jx install` as we straighten out a security model for user credentials. 

As it stands the first user (the user account used to install jx itself) will effectively be an admin account and will manage the repositories for the various environments. The details for the account to be used are stored in `~/.jx/gitAuth.yaml` It would be handy to take a look at what's in there for you guys in order to get to the bottom of this issue. Could you possibly post it's contents into this issue? (Don't forget to redact the actual API keys!)

**Comment by i0n** [comment]
Ah, I forgot to mention. As jx development is moving pretty fast at the moment it would be handy if you could test against the very latest version just to make sure we haven't already fixed the issue. Thanks!

**Comment by rezmuh** [comment]
Hi @i0n 

This is the last gitAuth.yaml file I have from `jx version 1.3.235`: 

```
servers:
- url: https://github.com
  users:
  - username: rezmuh
    apitoken: [...]
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: rezmuh
defaultusername: rezmuh
pipelineusername: rezmuh
currentserver: https://github.com
pipelineserver: https://github.com
```

I will try to update jx and try to create a new cluster to see if issue is still happening on the newest version. Gotta say, a bit hard to keep with jx releases. lol

**Comment by i0n** [comment]
Ok great, thanks for that. Given that you have only got information for the rezmuh user stored in gitAuth.yaml, I would expect that you would be prompted to enter the coverwatch user's credentials when you run the above command. I haven't been able to replicate the split environment issue you have experienced previously, so interested to know if you're still seeing that.

**Comment by rezmuh** [comment]
I just tested creating a new cluster again on `jx version 1.3.251` using the same parameter as the above.

staging environment is still created under github.com/rezmuh while production is created under github.com/coverwatch (the correct path). Please note that coverwatch is an organization though, not a user.

Also, I moved the original `~/.jx/gitAuth.yaml` to a different location so I could do a diff with newly created gitAuth.yaml but there are no differences between them.

**Comment by i0n** [comment]
Ok awesome, that helps a lot. Ideally I'm thinking if you pass a user/org that hasn't already been used then you should just be prompted for new creds. I'll take a look at getting some unit tests to cover this and see if I can get it behaving ;-)

**Comment by affixalex** [comment]
I also tested on jx 1.3.254. I wiped out `~/.jx/*` and added a gitAuth.yaml as follows.

`servers:
- url: https://github.com
  users:
  - username: xx-buildbot
    apitoken: redacted
    bearertoken: ""
  - username: affixalex
    apitoken: redacted
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: xx-buildbot
defaultusername: xx-buildbot
currentserver: https://github.com
`

Doing `jx create cluster gke --environment-git-owner=Whatever` tries to create the staging repository in the xx-buildbot personal account.

**Comment by i0n** [comment]
Hi again! Thanks for all the info, perhaps I should run through the functionality for git auth on install or cluster creation. This has only recently changed as we had to tweak the security model.

The first git user passed to the cluster is configured as the "pipeline user". By default this pipeline user will own the environment repositories. The token for this user is pushed to the cluster as a secret to allow git access to the environment repos.

Subsequent users can then be added to the installation and their details will never be pushed into the cluster, only stored locally in `~/.jx/gitAuth.yaml`

Subsequent users that create or import apps will trigger an auto invite of the pipeline user to that repo as a collaborator (currently github only), to allow the pipeline user to make releases for that app.

So the expectation here is that the first git account used will be the account used for instantiation, and then subsequent accounts would be normal team members.

Because any team member that owns a jx environment repo would necessitate the user's git api token being pushed into the cluster, we don't recommend that. Instead preferring to defer to an account specifically created or assigned for that purpose.

Hopefully that helps clear things up a little. There's obviously still a few bugs flying around in the code somewhere though.

**Comment by rezmuh** [comment]
ok, i get the idea for "pipeline user". However, a user can belong to an organisation right? E.g when you do `jx create env staging`, it will ask "which organisation do you want to use?" 

In my case, the pipeline user is correct, which is my username but I expected the environment repo to be in the `coverwatch` organisation. 

And as mentioned above though, it's weird that the repo for staging is incorrect while repo for production is correct (at least with GitHub. I'm experiencing something else on Gitlab but that's for later discussion, I guess. haha)

**Comment by Lazyshot** [comment]
The issue here would appear to be the owner is overwritten a few lines below it is set within the CreateEnvOptions.

https://github.com/jenkins-x/jx/blob/7bed06db5af17a42c30c78d120063fb4b3ad9b0a/pkg/jx/cmd/install.go#L642

From a first glance, this option should be set before the owner flag is allowed to overwrite.
