### ISSUE TITLE
Environment and Repository creation fails with Bitbucket provider

### ISSUE THREAD

**Issue by iamonkara** [jenkins-x/jx#1623]
### Summary 
On aws cluster creation the step of environment and repository creation fails with Bitbucket provider

### Steps to reproduce the behavior
jx install --provider aws --git-provider-url https://bitbucket.org --git-api-token XXXXX --git-username XXXXX --git-private=true --environment-git-owner thc-caringly

### Jx version
The output of `jx version` is:

```
jx                 1.3.237
jenkins x platform 0.0.2267
kubernetes cluster v1.10.3
kubectl            v1.10.7
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1
```

### Kubernetes cluster
brand new AWS cluster (kops based)

### Operating system / Environment
Ubuntu 18.04

### Expected behavior
Repository and Environment creation

### Actual behavior
the API url is wrong hence creation fails
```
error: failed to create staging environment: Failed to create repository /environment-mastermica-staging due to: POST https://bitbucket.org/api/v3/user/repos: 401  []
```
further digging shows the correct bitbucket api to call to create repo is [`/2.0/users/{username}/repositories`](https://developer.atlassian.com/bitbucket/api/2/reference/resource/users/%7Busername%7D/repositories) or [`/2.0/repositories/{username}/{repo_slug}` ](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D)

Any idea why POST request is made to `https://bitbucket.org/api/v3/user/repos` ??

For us GitHub is not an option and migrating to Gitlab (if it worked) won't be easy. So any help to make this work for bitbucket will be much appreciated.

**Comment by daya** [comment]
I am having the exact same issue

**Comment by wbrefvem** [comment]
@polothy Any thoughts about this?

**Comment by iamonkara** [comment]
@polothy thanks I will try those and report back. But it seems there is no straightforward way to 

- erect an AWS cluster with BitBucketCloud and 
- even for `jx install` there are hoops to be jumped

right?

**Comment by polothy** [comment]
Yeah, you might have discovered a missing flag.  I'm not sure what the intended workflow is supposed to be for git providers that are not GitHub (EG: you must add them first or if you can add them on the fly via install).

**Comment by jstrachan** [comment]
I think we got this one resolved. Its partly due to not terribly clear documentation and UX.

When using other git providers than github you need to specify these instructions: 
https://jenkins-x.io/developing/git/#using-a-different-git-provider-for-environments

i.e. use one these 2 commands:

`jx create cluster --no-default-environments`
`jx install--no-default-environments`

to setup Jenkins X without default environments. Then add a new git provider - ensuring the kind it setup properly: https://jenkins-x.io/developing/git/#adding-a-new-git-provider

this issue was actually caused by the `https://bitbucket.org/` URL being setup without the `bitbucketcloud` type as per https://jenkins-x.io/developing/git/#bitbucket-cloud

**Comment by jstrachan** [comment]
I've tried to make the docs a bit more clear now to avoid others hitting this: http://localhost:1313/developing/git/#using-a-different-git-provider-for-environments

**Comment by httpete** [comment]
We see also, running against our bitbucketserver, that the API calls to create the environment repos work great. To create the "project" repos (like jx create quickstart) are totally not right. If someone can point us to it, we can try to fix it.
