### ISSUE TITLE
create a prow plugin to detect if a PR changes the Jenkinsfile and warn

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1854]
When using Prow we should check to see if a PR tampers with the Jenkinsfile, if it does make sure it's reviewed before running the pipeline to ensure we don't get a malicious change that executes on our release infra.

**Comment by jglick** [comment]
See https://github.com/jenkinsci/workflow-multibranch-plugin/pull/69 for background. In multibranch Jenkins service, the implementation of [`SCMSource.getTrustedRevision`](https://javadoc.jenkins.io/plugin/scm-api/jenkins/scm/api/SCMSource.html#getTrustedRevision-jenkins.scm.api.SCMRevision-hudson.model.TaskListener-) in `github-branch-source` indicates whether the author of a PR had write access to the repository anyway, in which case `Jenkinsfile` patches are honored; otherwise they are currently ignored.
