### ISSUE TITLE
helm fails to install jenkins-x on AKS cluster

### ISSUE THREAD

**Issue by matakan** [jenkins-x/jx#2112]
### Summary 
I am having an issue while installing jenkins-x into an existing AKS cluster. Actually the problem started today. With the same configuration, there was no problem until yesterday.

...
Installing jx into namespace jx
Waiting for tiller pod to be ready, service account name is tiller, namespace is jx, tiller namespace is kube-system
Waiting for cluster role binding to be defined, named tiller-role-binding in namespace jx
 Trying to create ClusterRoleBinding tiller-role-binding for role: cluster-admin and ServiceAccount: jx/tiller
Created ClusterRoleBinding tiller-role-binding
tiller cluster role defined: cluster-admin in namespace jx
tiller pod running
error: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.2789 --values /Users/uu/.jx/cloud-environments/env-aks/myvalues.yaml --values /Users/uu/.jx/cloud-environments/env-aks/secrets.yaml --values /Users/uu/.jx/gitSecrets.yaml --values /Users/uu/.jx/adminSecrets.yaml --values /Users/uu/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/Users/uu/.jx/cloud-environments/env-aks', output: 'Release "jenkins-x" does not exist. Installing it now.
Error: watch closed before Until timeout': exit status 1

### Jx version

The output of `jx version` is:

>tmp$ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.482
jenkins x platform 0.0.2789
Kubernetes cluster v1.11.3
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1 (Apple Git-112)

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by kumarinfo90** [comment]
Even i am getting the same error,can some one please give us the solution .

# jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.489
jenkins x platform 0.0.2806
Kubernetes cluster v1.9.11
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1


If you do not have a custom domain setup yet, Ingress rules will be set for magic dns nip.io.
Once you have a customer domain ready, you can update with the command jx upgrade ingress --cluster
If you don't have a wildcard DNS setup then setup a new CNAME and point it at: 137.135.105.232.nip.io then use the DNS domain in the next input...
? Domain 137.135.105.232.nip.io
nginx ingress controller installed and configured
Lets set up a Git username and API token to be able to perform CI/CD

? Do you wish to use kumarinfo90 as the GitHub username for CI/CD pipelines: Yes
Current configuration dir: /root/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Current configuration dir: /root/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Compressing objects: 100% (6/6), done.
Total 1141 (delta 1), reused 3 (delta 0), pack-reused 1135
Generated helm values /root/.jx/extraValues.yaml
? Select Jenkins installation type: Static Master Jenkins
Installing Jenkins X platform helm chart from: /root/.jx/cloud-environments/env-aks
Installing jx into namespace jx
Waiting for tiller pod to be ready, service account name is tiller, namespace is jx, tiller namespace is kube-system
Waiting for cluster role binding to be defined, named tiller-role-binding in namespace jx
 tiller cluster role defined: cluster-admin in namespace jx
tiller pod running
error: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.2806 --values /root/.jx/cloud-environments/env-aks/myvalues.yaml --values /root/.jx/cloud-environments/env-aks/secrets.yaml --values /root/.jx/gitSecrets.yaml --values /root/.jx/adminSecrets.yaml --values /root/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/root/.jx/cloud-environments/env-aks', output: 'Error: UPGRADE FAILED: "jenkins-x" has no deployed releases': exit status 1

**Comment by jstrachan** [comment]
does the latest release work any better? We've released `0.0.2859` now?

**Comment by kumarinfo90** [comment]
i have upgraded today and tried again
but getting the same
# jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.521
jenkins x platform 0.0.2859
Kubernetes cluster v1.9.11
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1

**Comment by kumarinfo90** [comment]
# helm ls
NAME                    REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
expose-skullplume       1               Tue Nov  6 12:19:02 2018        DEPLOYED        exposecontroller-2.3.82                         default
jenkins-x               1               Tue Nov  6 12:14:56 2018        FAILED          jenkins-x-platform-0.0.2859                     jx
jx-build-templates      1               Tue Nov  6 12:43:00 2018        DEPLOYED        jx-build-templates-0.0.69                       jx
jx-knative-build        1               Tue Nov  6 12:42:54 2018        DEPLOYED        knative-build-0.0.12                            jx
jx-prow                 1               Tue Nov  6 12:42:49 2018        DEPLOYED        prow-0.0.43                                     jx
jxing                   1               Tue Nov  6 12:10:46 2018        DEPLOYED        nginx-ingress-0.30.0            0.20.0          kube-system

**Comment by kumarinfo90** [comment]
Hi Matakan,

It works now!
step1 : Jx version

## upgrade the latest version as stated
when you creating the cluster just try by passing the password parameter it may help,
Step 2:  jx create cluster aks --default-admin-password=xxxxxxx 

Thanks

**Comment by jtnord** [comment]
@matakan @kumarinfo90 can this issue now be closed?

**Comment by GingerBuffalo** [comment]
I've started having this issue. Up until last week, I was able to complete jx install operations. I upgraded jx sometime late last week, and this exact issue is a repro for me every time now. Is it a regression?

**Comment by carlosignaciom** [comment]
We've started to experience the same issue from yesterday trying to create a brand new cluster in AKS. Is it possible that this issue is not well solved?

**Comment by jcalavia** [comment]
We're experiencing the same error in a fresh minikube setup

```
Installing jenkins-x-platform version: 0.0.3832
Adding values file /Users/user/.jx/cloud-environments/env-minikube/myvalues.yaml
Adding values file /Users/user/.jx/adminSecrets.yaml
Adding values file /Users/user/.jx/extraValues.yaml
Adding values file /Users/user/.jx/cloud-environments/env-minikube/secrets.yaml
Upgrading Chart 'upgrade --namespace services --install --timeout 6000 --version 0.0.3832 --values /Users/user/.jx/cloud-environments/env-minikube/myvalues.yaml --values /Users/user/.jx/adminSecrets.yaml --values /Users/user/.jx/extraValues.yaml --values /Users/user/.jx/cloud-environments/env-minikube/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform'



error creating cluster installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace services --install --timeout 6000 --version 0.0.3832 --values /Users/user/.jx/cloud-environments/env-minikube/myvalues.yaml --values /Users/user/.jx/adminSecrets.yaml --values /Users/user/.jx/extraValues.yaml --values /Users/user/.jx/cloud-environments/env-minikube/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/Users/user/.jx/cloud-environments/env-minikube', output: 'Release "jenkins-x" does not exist. Installing it now.
NAME:   jenkins-x
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'

```
The output of jx version

```
NAME             VERSION
jx               1.3.1096
git              git version 2.20.1
Operating System Mac OS X 10.14.4 build 18E226
```

**Comment by GingerBuffalo** [comment]
My repro is on provider=oke. Attempting install with this command:
jx install --git-username=someusername --git-provider-kind=gitlab --git-provider-url=https://someurl --default-environment-prefix=someprefix --environment-git-owner=someownervalue --provider=oke

As of about Friday last week, every attempt results in this failure to install jenkins-x:
Installing jx into namespace jx
using stable version 0.0.3832 from charts of jenkins-x/jenkins-x-platform from /Users/ploveles/.jx/jenkins-x-versions
Installing jenkins-x-platform version: 0.0.3832
Adding values file /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml
Adding values file /Users/ploveles/.jx/adminSecrets.yaml
Adding values file /Users/ploveles/.jx/extraValues.yaml
Adding values file /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml
Upgrading Chart 'upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml --values /Users/ploveles/.jx/adminSecrets.yaml --values /Users/ploveles/.jx/extraValues.yaml --values /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform'
error: installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml --values /Users/ploveles/.jx/adminSecrets.yaml --values /Users/ploveles/.jx/extraValues.yaml --values /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/Users/ploveles/.jx/cloud-environments/env-oke', output: 'Release "jenkins-x" does not exist. Installing it now.
NAME:   jenkins-x
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'

jx version:
NAME               VERSION
jx                 1.3.1096
Kubernetes cluster v1.12.7-3+1a4d39a9763d23
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G5019

I've been trying out jenkins-x since last week, really hoping it to be the right solution for my team. At this point, I'm about to bail on it now though. This issue is blocking any further progress.

**Comment by desolatorxxl** [comment]
@jcalavia @GingerBuffalo please take a look at https://github.com/jenkins-x/jx/issues/3574.
