### ISSUE TITLE
Bitbucket Server token fails on multibranch scan

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#2214]
### Summary 

The multibranch config throws an error message: 
```
The selected credentials do not have permission to determine whether jenkins-x-testing does or does not exist
```

The multibranch scan logs also reveal a 401 when Jenkins attempts to read repo info.

The token works just fine during repo creation, so this is probably a bug in how we're setting up the Jenkins credential.

### Steps to reproduce the behavior

`jx install --git-provider-url=<Bitbucket Server URL>`
Input valid API token when prompted.

### Jx version

The output of `jx version` is:

```
jx                 1.3.539
jenkins x platform 0.0.2871
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
```

### Kubernetes cluster

GKE - `jx create cluster gke`

### Operating system / Environment

ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75

### Expected behavior

Jenkins should be able to use the token to read repos on Bitbucket Server. The token in question has project admin permissions and can be used to create repos.

### Actual behavior

Jenkins gets a 401 from Bitbucket Server when trying to read repos and consequently the scan fails.

**Comment by wbrefvem** [comment]
PEBKAC. I specified the wrong username during installation, and even though I went back and changed it, the Jenkins credential for the repo was still using the incorrect username.

**Comment by acxmatos** [comment]
Just for anyone wondering around this problem just like I was. In my case, it was not PEBKAC since the credential was correct and working fine for other plugins.

We use a corporate internet proxy to manage Jenkins plugins. For some reason, this proxy was being used by the Bitbucket plugin during the credential validation call, resulting in an invalid authentication (401).

I could find the following on Jenkins fine logs, which led me to solve the problem:

Jan 23, 2020 5:09:06 PM FINE com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient
Using proxy authentication (user=xxx)

Jan 23, 2020 5:17:11 PM FINE com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticator
Add host=http://x.x.x.x:7990 to authCache.

As you can see, the BitbucketServerAPIClient class was using the proxy to make an internal call. In the Manage Plugin advanced settings, I just added the Bitbucket Server IP address to the "No Proxy Host" list, and the issue went away.
