### ISSUE TITLE
How to integrate GCP deployment manager (microservice configuration as code)

### ISSUE THREAD

**Issue by bhouston** [jenkins-x/jx#2296]
### Summary 

I want to have my microservices self-contained such that when deploying they run their GCP configuration as code . This way my microservices can create and own their own GCP resources like Data Store, etc.  What is the best practice for this?  I can not find this in the docs or whether this is even supported?  Basically it seems that I have to squeeze this into helm?  Is this best practice?

Right now if here is no existing Kubernetes hosted services I can not use it in an automated fashion in Jenkin-x.  I would prefer to use managed services in GCP if possible, particularly pub-sub, data store and similar.

### Steps to reproduce the behavior

Unsure of best practices.

### Jx version

 current.

The output of `jx version` is:

```
n/a
```

### Kubernetes cluster

GKE

### Operating system / Environment

GPC

### Expected behavior

Confiugration as code for microservice owned resources on GCP

### Actual behavior

Seems like GCP resources required by microservices needs to be configured separately?

**Comment by ccojocar** [comment]
@bhouston I think one approach is to define the GCP resource in Terraform and store the configuration in the microservice repository or environment repository. This configuration can be applied in the deployment step. 

Another option is to use service-catalog (https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) and define the resources as YAML in the helm chart of the microservice. 

I am closing this issue since is not really related to `jx`.
