### ISSUE TITLE
tide was reporing a missing label that was not correct.

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2306]
### Summary 

As per [this discussion on slack](https://kubernetes.slack.com/archives/C9LTHT2BB/p1542896179344600)
I had  a PR #2291) that I had approved and the tide status on GitHub was `"Pending — Not mergeable. Needs updatebot label"`.

However the `jx` repo configuration in Tide is not looking for the "updatebot" label and so this status was confusing.  In reality it was missing the "lgtm" label.

### Steps to reproduce the behavior

* submit a PR to `jx` repo.
* approve it with `/approve`
* check the tide status.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 [32m1.3.568[0m
jenkins x platform [32m0.0.2902[0m
Kubernetes cluster [32mv1.11.2-gke.18[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.11.0+g2e55dbe[0m
helm server        [32mv2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
```

### Kubernetes cluster

GKE  (jenkins-x production cluster)

### Expected behavior

the status from tide is either specific about the labels it is missing or generic.
e.g.
`"Pending — Not mergeable. Needs lgtm label"`.
`"Pending — Not mergeable. Needs foo, bar, whizbang labels"`.
or 
`"Pending — Not mergeable. Missing one or more lables."`.

The latter is not very helpful but at least it means you don;t go looking for the wrong thing.

### Actual behavior

"`Pending — Not mergeable. Needs updatebot label"`.

**Comment by jtnord** [comment]
yes I believe so. we always see missing update-bot when it is missing approved

**Comment by pmuir** [comment]
Agreed. Still an issue :-D Though this is really a bug in prow, not JX.

**Comment by ccojocar** [comment]
@jtnord @pmuir Can we do something in `jx` to mitigate it? I think we should open a but in prow and link it to this one. Thanks

**Comment by pmuir** [comment]
I don't think so as the reporting is entirely done in prow.

**Comment by ccojocar** [comment]
@jtnord @pmuir Can we close this issue?

**Comment by jtnord** [comment]
@ccojocar no this is a useablility issue in JX and can not be closed (it came up again today in [slack](https://kubernetes.slack.com/archives/C9LTHT2BB/p1553169272306100)).  SHould be filed upstream and tracked here and closed when the upstream bug is closed or we are no longer seeing this behaviour due to some other reason (like moving away from prow)

**Comment by pmuir** [comment]
tide has a concept of queries, queries are are what it uses to check if a PR can be merged by the bot or not. Queries specify a set of github labels that must be present, and a set of labels that must not be present on the PR for the merge to happen. If none of the queries are met, it doesn't merge the PR (obviously) and it also displays a helpful status message to explain how to satisfy the query - all good so far

You can have multiple queries (which we do), and any of those queries can be satisfied for a merge. In this case tide will show the "easiest" query to satisfy (which its logic dictates is the one with the least number of needed label changes). The least number of changes in this case is the query that requires the `updatebot` label to be present, but that's not one you (ie. you, the PR author) can satisfy ever, as the `updatebot` label should only ever be added by Updatebot. The query you can satisfy is the one that requires the `approved` but because of the above algorithm it chooses `updatebot` (I can't remember the exact detail of the algorithm obviously as they are both one label, but it's some ordering thing). So we really need to add some config to tell it not to show that query in the status message or something (e.g. a different algorrithm)
