### ISSUE TITLE
prow quickstart release builds get stuck, auto promoting to staging 

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2410]
Even though the promotion is successful the release pipeline for the quickstart never completes.  The last entry in the logs say the promote can't get commit statuses:
```
Merge commit has not yet any statuses on repo project-demo/environment-jx-staging merge sha abc123
```
I can see the PR on the `environment-jx-staging` repo get's merged successfully so not too sure what's up yet.

**Comment by rawlingsj** [comment]
As a quick workaround we could add the `--no-wait` flag to promote in the buildpack https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/maven/pipeline.yaml#L32 when using prow ?  @jstrachan what do you think?

**Comment by rawlingsj** [comment]
Rather than adding the workaround in the build backs which would affect non prow pipelines too, let's add it to jx, log an explanation and let's keep this issue open to investigate and fix the real issue.

**Comment by dinfer** [comment]
I meet the same problem. and since the pr is merged, how can I get the fix?
the version of jenkins-x-platform is still `0.0.3402` for 15 days now. when will the jenkins-x-versions get updated? should I manually change the local version repo to force the platform get upgrade?

**Comment by GingerBuffalo** [comment]
I think I'm hitting something similar to this issue. I used jx import on an existing project, and using static jenkins. I'm using gitlab enterprise edition, hosted within the jenkins x cluster. Everything appears to set up correctly, including webhooks. The webhooks are not showing any error. But jx promote is hanging on the pr sent to staging. The pr in staging is created just fine, but it's not auto approved. I've tried manually approving, but it appears jx promote can't actually see the pr (hence this popular warning message "WARNING: Failed to query the Pull Request last commit status for..."). 

As the webhooks appear to work just fine, I'm trying to see if maybe the issue is to do with how merge requests are configured to work on the gitlab server. If anyone here has any ideas, I'm all ears.

**Comment by valdestron** [comment]
/remove-lifecycle stale

 Any news about this issue ?

**Comment by dinfer** [comment]
/remove-lifecycle stale

It seems no one care about this issue.

**Comment by Ubermensch01** [comment]
/reopen
I'm still seeing this issue in the pipeline, can anyone shed some light on it?
