### ISSUE TITLE
Preview environments are not redeployed after new commits on the PR

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2482]
### Summary 
Preview environments are not redeployed after new commits on the PR

### Steps to reproduce the behavior

1. Open a PR on a project
2. Check the preview is up
3. Commit new changes that should be visible on the preview env

### Jx version

The output of `jx version` is:

jx                 1.3.642
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.10.4
helm client        v2.12.0+gd325d2a
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14 build 18A391

### Kubernetes cluster

GKE

### Operating system / Environment
Does not matter

### Expected behavior
The preview env should be rebuilt to embed new commits

### Actual behavior
The bot is publishing a new comment on the PR with a link to the preview env but this one is not updated with the changes coming from the latest commit.

**Comment by romainverduci** [comment]
Imported as CNJ-94

**Comment by garethjevans** [comment]
Hi @romainverduci, I think the issue is that even though the image pull policy is set to Always, helm seems to think the image hasn't changed so doesn't trigger a deploy.  Could possibly add `--force` for the preview to ensure resources are recreated, or ensure a new image (different name) is used for each PR.

**Comment by romainverduci** [comment]
@garethjevans I can confirm it's working well now, thanks :)
