### ISSUE TITLE
quickstart doesn't work with --git-provider-url=https://gitlab.com option

### ISSUE THREAD

**Issue by spender0** [jenkins-x/jx#2500]
### Summary 
quickstart ignores "--git-provider-url=https://gitlab.com" option.
### Steps to reproduce the behavior
```
jx get git 
Name       Kind   URL
gitlab.com gitlab https://gitlab.com

jx create quickstart --git-provider-url=https://gitlab.com
```
it asks for GitHub token instead of using existing configured gitlab server:

```
To be able to create a repository on github.com we need an API Token
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter in into the form below:

? API Token: 
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.657
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.2
Operating System   "Fedora release 29 (Twenty Nine)"
```

**Comment by jmtbusiness** [comment]
Same problem with a github enteprise on prem setup

```
jmtizon:~/Work/Jx $ jx create quickstart --git-provider-url=https://my.guthub-enterprise.com
To be able to create a repository on github.com we need an API Token
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter in into the form below:

? API Token: 
```

**Comment by jstrachan** [comment]
@spender0  creating quickstarts currently uses a github organisation to find the quickstarts to create which is why its asking for your github API token: https://github.com/jenkins-x-quickstarts

we could change how we support the quickstarts to avoid needing a github token though

**Comment by moglimcgrath** [comment]
Having a similar issue with jx create quickstart --git-provider-kind='bitbucketserver'
I would like to add the quickstart app to the bitbucket server we have and not github

**Comment by dcanadillas** [comment]
As commented here the API GitHub token seems to be requested for using the quickstart. I used an API token from GitHub when asked, and my Gitlab account and token when creating the quickstart. And everything is created correctly in Gitlab.

In my case works with:
```
$ jx create quickstart --git-provider-url https://gitlab.com --git-username
 _<my-username>_ --git-api-token _<my-api-token>_
```

Maybe would be more intuitive to use a different message in the creation wizard. In my case I had this:
_"Using Git provider Gitlab at https://gitlab.com

About to create repository  on server https://gitlab.com with user DCanadillas
? Which organisation do you want to use? DCanadillas
? Enter the new repository name:  go-demo

**Creating repository DCanadillas/go-demo
To be able to create a repository on github.com we need an API Token**
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo"_

So, can be confusing because seems that the repo is going to be created in GitHub, but it is not. It is created in Gitlab in this case.

**Comment by bitsofinfo** [comment]
same issue

**Comment by bitsofinfo** [comment]
@spender0 please reopen this
