### ISSUE TITLE
skip-ingress flag not working

### ISSUE THREAD

**Issue by bygui86** [jenkins-x/jx#2571]
### Summary
During jx install on an existing empty cluster, using the flag "--skip-ingress" cause an issue and prevent the installation.

### Steps to reproduce the behavior

* create a GKE cluster ether manually or using gcloud SDK
* install JX
	`jx install \
		--default-environment-prefix playground \
		--skip-ingress \
		--environment-git-owner Interdiscount \
		--default-admin-password ***** \`
* the process is interrupted by an error (see screenshot below)
![image](https://user-images.githubusercontent.com/22518997/50382852-abe9a800-06a8-11e9-9e93-bf4aa2599267.png)

### Jx version
1.3.684

### Kubernetes cluster
GKE version 1.11.5-gke.5

### Operating system / Environment
MacOsX 10.14.2

### Expected behavior
The installation should end without issues and jx should not install any kubernetes ingress controller after the creation or import of a new application.

### Actual behavior
The installation of JX in an already existing empty cluster failed.

**Comment by rawlingsj** [comment]
The expose job is needed to create the ingress rules for all services and applications that are create.  The flag `--skip-ingress` was intended to just skip in the installation on the default nginx ingress controller. 

@bygui86 do you have the logs from a failed expose job?  I'm sure we used to prompt for the `domain` if folks didn't require the default ingress controller but from the screenshot I can't see that it was provided.  My guess is the expose job pod is missing the domain and failing.

**Comment by bygui86** [comment]
@rawlingsj thanks for the reply. I misunderstood the usage of `--skip-ingress`.
I don't have that cluster anymore but anyway the jx installation was prevented by this error so I didn't go into the cluster to see jobs because I thought everything failed.

**Comment by ccojocar** [comment]
@bygui86 Did you have any other ingress controller installed in the cluster? 

Maybe we should detect when no ingress controller is installed, and display to the user this information in case the user provides `--skip-ingress` option.

This seems to be a required for jenkins-x platform installation to succeed. I am not sure if it works with other ingress controller such as Contour which uses envoy instead of nginx.  

@rawlingsj Is `expose` controller kind of coupled to `nginx-ingress` controller, given that it uses specific `ningx` annotations.

**Comment by ccojocar** [comment]
I tested the `skip-ingress` with an existing `nginx-ingress-controller`, and it seems that the expose job is failing because doesn't have permissions to list the nodes at the cluster scope. 

```
I0116 16:36:53.281339       1 ingress.go:39] NewIngressStrategy 1 true
F0116 16:36:53.315800       1 exposecontroller.go:194] failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: fai$
ed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope
```

The `expose` role and role binding is created in the `jx` namespace. We need to check why the `exposecontroller` needs to perform this action at the cluster level.

**Comment by ccojocar** [comment]
The root cause of this issue is an empty domain in the `expose` controller configuration. In this particular case, the expose controller will try to infer the domain from the Kubernetes nodes. This action requires a cluster wide permission. To avoid this, a non empty domain must be provided before the platform installation in any case.

I will try to fix it in the install by asking for a domain, if the configured domain is empty after the initialisation phase.

**Comment by rawlingsj** [comment]
yeah pretty sure we used to prompt for the domain, my hunch above was correct about it missing.

> I will try to fix it in the install by asking for a domain, if the configured domain is empty after the initialisation phase. 

perfect!

**Comment by bygui86** [comment]
@ccojocar "Did you have any other ingress controller installed in the cluster?" > No

@ccojocar @rawlingsj thanks a lot for effort and replies :)

**Comment by ccojocar** [comment]
I think the installation will fail if you don't have any ingress in the cluster when it tries to generate the Jenkins API token.

Hopefully now it will fail explicitly in the initialisation phase.

**Comment by bygui86** [comment]
Great!! Waiting for the merge of PR to try again :)
