### ISSUE TITLE
Pipeline Git user not respected on Gitlab

### ISSUE THREAD

**Issue by stieler-it** [jenkins-x/jx#2816]
### Summary 

Jx uses the local Git user instead of the pipeline Git user in the pipeline.

### Steps to reproduce the behavior

- jx install (with Gitlab as provider)
- select user1 as local user
- select user2 as pipeline user
- answer all questions until default environments are setup

### Expected behavior

- Jenkins folder is created for user2
- Jenkins credentials are created for user2

### Actual behavior

- Jenkins folder is created for user2
- Jenkins credentials are created for user1

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 [32m1.3.756[0m
jenkins x platform [32m0.0.3286[0m
Kubernetes cluster [32mv1.11.6[0m
kubectl            [32mv1.12.1[0m
helm client        [32mv2.12.1+g02a47c7[0m
helm server        [32mv2.12.2+g7d2b0c7[0m
git                [32mgit version 2.18.0.windows.1[0m
Operating System   [32mWindows 10 Home 1803 build 17134[0m
```

### Jenkins type

- [X] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

Cluster was created using Rancher 2 and RKE on OpenStack.

### Operating system / Environment

Windows 10

**Comment by ccojocar** [comment]
@stieler-it What do you mean by `Jenkins folder ` and `Jenkins credentials`? Please could you elaborate a bit?

**Comment by stieler-it** [comment]
Of course,

Jenkins folder: Logical group of projects as provided by [Folder plugin](https://plugins.jenkins.io/cloudbees-folder). I assume Jenkins X tries to create one folder per user or organization because my folder is called like my username. 

Jenkins credentials: Allows Jenkins users to store credentials globally, so they don't have to be part of a build job / pipeline. Usually at least Git credentials are stored there. You can access them at `www.your.jenkins/credentials/`.

My expectation was that the selected "pipeline Git user" would be the one created as credentials in Jenkins.

**Comment by deanesmith** [comment]
Hi @stieler-it, We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
