### ISSUE TITLE
Bitbucket Cloud: No comment with preview environment on pull request

### ISSUE THREAD

**Issue by nlamot** [jenkins-x/jx#2856]
### Summary 
When the preview environment of a Pull Request is ready, the pull request in Bitbucket Cloud doesn't receive a comment with the URL to the preview environment. Currently, the logs display the message "Bitbucket Cloud doesn't support adding PR comments via the REST API", but this now implemented: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/comments

### Steps to reproduce the behavior

1. Commit a change to your codebase to a new Branch.
2. Create a pull request in Bitbucket Cloud
3. Check the build logs for the pull request in Jenkins.
4. Find "Bitbucket Cloud doesn't support adding PR comments via the REST API"

### Expected behavior

- No warning in the logs.
- A comment with the URL to the preview environment attached to your pull request in Bitbucket.

### Actual behavior

- No comment with the preview environment on the pull request.
- A warning in the logs: "Bitbucket Cloud doesn't support adding PR comments via the REST API"

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.798
jenkins x platform 0.0.3286
Kubernetes cluster v1.10.11-gke.1
kubectl            v1.10.11
helm client        v2.12.1+g02a47c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.20.1.windows.1
Operating System   Windows 10 Pro 1803 build 17134
```

### Jenkins type
- [ X] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
GKE Cluster, created with jx create cluster gke

### Operating system / Environment
Windows 10 Pro 1803 build 17134

**Comment by jstrachan** [comment]
the code is here https://github.com/jenkins-x/jx/blob/master/pkg/gits/bitbucket_cloud.go#L828 when we wrote it there wasn't a REST API we could call so should hopefully be fairly straight forward

**Comment by wbrefvem** [comment]
@nlamot So we should be able to get this going pretty quick. We hadn't been able to incorporate changes to the Bitbucket Cloud API because the OAI spec they provide, which we used to generate a client lib, was broken and Atlassian had said they weren't going to fix it. Apparently that was wrong, because it now seems to be fixed. So it's a now a matter of regenerating the client lib and then adding just a bit of logic in Jenkins X to call into the lib. I'll reference this issue as soon as I've got a PR going.
