### ISSUE TITLE
Rebase the jenkins-x/charts fork to the latest stable upstream

### ISSUE THREAD

**Issue by sboardwell** [jenkins-x/jx#2991]
### Summary

The helm/charts upstream project has moved on considerably and the current fork is over 3000 commits behind the upstream.

The idea would be to rebase and
* see which jx fork additions need changing
* see which jx fork additions need merging upstream
* determine whether and how the current environment values.yaml need to be changed after rebasing.

**Comment by stormmore** [comment]
An alternative to rebasing would be to have the platform chart use the stable upstream chart as a sub-chart instead of forking it. Use the mechanisms in the upstream chart to make the customization necessary for Jenkins X.

I would also like to see using the upstream Jenkins Docker container to make it easier for core Jenkins upgrades especially with the recent rash of security issues that they have had.
