### ISSUE TITLE
PR comment on bitbucketcloud fail

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3076]
### Summary 
When a PR passes a build, bitbucket comment fails with an error and hence there is no url posted.

### Steps to reproduce the behavior
Import a private bitbucket repository. Create a PR and let it's build succeed.

### Expected behavior
A new comment is added to PR with the link to the URL

### Actual behavior
No comment is added and an error is seen in the logs:

```
Preview application is now available at: http://APP.jx-ORG-APP-pr-2.ORG.com



Failed to comment on the Pull Request with owner ORG repo APP: Status: 400 Bad Request, Body: {"type": "error", "error": {"fields": {"updated_on": "extra keys not allowed", "created_on": "extra keys not allowed", "type": "extra keys not allowed"}, "message": "Bad request"}}
```

### Jx version

The output of `jx version` is:

```
jx                 1.3.872
jenkins x platform 0.0.3368
Kubernetes cluster v1.11.6-gke.6
kubectl            v1.13.3
helm client        Client: v2.12.3+geecf22f
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type
- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
GKE - Manually created

### Operating system / Environment

Mac OSX Mojave

**Comment by hajowieland** [comment]
Same issue here with up-to-date Jenkins-X on EKS with bitbucketcloud.

Hopefully Bitbucket will be a first-class git server kind in the near future.


**Expected behavior**
A new comment is added to PR and/or in _Activity_ section of Bitbucket's PR view with the link to the URL to the preview environment.


**Actual behavior**
No comment is added and an error is seen in the logs (reformatted for easy read - same as @heroic above):

```
Failed to comment on the Pull Request with owner xxxxxxxx repo xxxxxxxx:
Status: 400 Bad Request,
Body:
{"type": "error", "error":
    {"fields": {"updated_on": "extra keys not allowed",
                "created_on": "extra keys not allowed",
                "type": "extra keys not allowed"},
    "message": "Bad request"}}
```

**Jx version**

```
jx version                                                                                                                                   ✔  10233
NAME               VERSION
jx                 1.3.1071
jenkins x platform 0.0.3636
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.13.4
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```


**Jenkins type**

- [X] Classic Jenkins
- [ ] Serverless Jenkins


**Kubernetes cluster**

EKS - Manually created
EKS AMI:  `amazon-eks-node-1.12-v20190329 (ami-0d741ed58ca5b342e)`


**Operating system / Environment**
Mac OSX 10.4.4 Mojave
