### ISSUE TITLE
Support releases from branch names with "/"

### ISSUE THREAD

**Issue by bkuszewski** [jenkins-x/jx#3122]
### Summary

jx promote fails when releasing a branch name that includes a /

### Steps to reproduce the behavior

Create a branch (release/V123, for example) with a Jenkinsfile that includes a release step which calls jx promote
Tell Jenkins to build that branch.  

### Expected behavior
The release is deployed

### Actual behavior
```
+ jx promote -b -e v123-10 --timeout 1h --version 0.0.7 --verbose
Using helmBinary helm with feature flag: none
Promoting app trading-airclient version 0.0.7 to namespace jx-v123-10
Using pipeline: liquidxinc/trading-airclient/release%2FV1.2.3-10 build: #0.0.7
Created Pull Request: [redacted]environment-jx-v123-10/pull/4

Failed to update PipelineActivity: PipelineActivity.jenkins.io "trading-airclient-release-2fv1-2-3-10-0-0-7" is invalid: metadata.labels: Invalid value: "release%2FV1.2.3-10": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
error: PipelineActivity.jenkins.io "trading-airclient-release-2fv1-2-3-10-0-0-7" is invalid: metadata.labels: Invalid value: "release%2FV1.2.3-10": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.884
jenkins x platform 0.0.3402
Kubernetes cluster v1.10.11-eks
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.12.2+g7d2b0c7
git                git version 2.19.2
Operating System   Ubuntu 18.04.1 LTS
```

### Jenkins type

<!--
Select which Jenkins installation type are you using. 
-->
- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS, Created via eksctl

### Operating system / Environment

Ubuntu running under Windows

**Comment by sboardwell** [comment]
Similar to #2563

**Comment by deanesmith** [comment]
Hi @bkuszewski, this is likely resolved in a recent release, but we are closing it because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
