### ISSUE TITLE
node-js worker goes offline due to low ephemeral-storage

### ISSUE THREAD

**Issue by gerrito333** [jenkins-x/jx#3243]
## Summary 

nodejs worker node goes offline during build. 

### kubectl events:

nodejs-qc2lb.15877af0bf79909c
The node was low on resource: ephemeral-storage. Container nodejs was using 40Ki, which exceeds its request of 0. Container jnlp was using 60Ki, which exceeds its request of 0.

### Jenkins log:

Step 5/6 : COPY . .
Cannot contact nodejs-7pmmr: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from ip-XXX-XXX-X-X.eu-central-1.compute.internal/XXX.XXX.X.X:41874 failed. The channel is closing down or has closed down

### Steps to reproduce the behavior

sporadically happens when building npm apps.

### Expected behavior

I tried to set a ephemeral-storage request in the nodejs template, but it looks like jenkinsci/kubernetes-plugin does not allow to set this.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 ?[32m1.3.809?[0m
jenkins x platform ?[32m0.0.3402?[0m
Kubernetes cluster ?[32mv1.11.5-eks-6bad6d?[0m
kubectl            ?[32mv1.11.5?[0m
helm client        ?[32mv2.12.3+geecf22f?[0m
helm server        ?[32mv2.12.2+g7d2b0c7?[0m
git                ?[32mgit version 2.15.1.windows.2?[0m
Operating System   ?[32mWindows 10 Enterprise 1709 build 16299?[0m

### Jenkins type
Jenkins-X

- [X ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
jenkins-x on EKS 

### Operating system / Environment
AWS EKS
<!--
In which environment are you running the jx CLI?
Windows

**Comment by damian87x** [comment]
Experience same issue @gerrito333 did you find a solution?

**Comment by jigar-komodo** [comment]
The pod's drive runs out of storage while building the docker image. @damian87x and @gerrito333 , were you able to find a solution?

**Comment by jigar-komodo** [comment]
Solution was to just increase the size of EBS volume thats attached to the worker node.

**Comment by plucury** [comment]
Experience same issue too

**Comment by dbitkowski** [comment]
I've struggled with this issue for several months.  Even if you increase the EBS volume size, eventually, you'll still run out of space.  I had to drain all of the nodes in order to reclaim the space being held onto.

That being said, I came across a fix if draining nodes and bringing everything down isn't an option.

Note: This still feels like a hack and you'll still have to do this on occasion to clear things out, I haven't figured out a way of automating this yet.

1) Create a privileged-pod.yaml file with the following contents:

`apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
    stdin: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root-volume
      mountPath: /host
      readOnly: true
  volumes:
  - name: host-root-volume
    hostPath:
      path: /
  hostNetwork: true
  hostPID: true
  restartPolicy: Never`

2) Run `kubectl create -f privileged-pod.yaml`
3) Log into the new pod `kubectl exec -ti privileged-pod sh -n default`
4) Run as root using the node's filesystem `chroot /host/`
5) Run `docker system prune` to clean up docker.
6) After the process has reclaimed your lost space, exit out and delete the pod with `kubectl delete pod privileged-pod -n default`

Not ideal, but hopefully this helps someone.

**Comment by scones** [comment]
i would assume that, having a bare metal cluster, the response of @dbitkowski boils down to `docker system prune`

**Comment by deanesmith** [comment]
Hi @gerrito333, We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.  It would appear this matter is no longer not an issue when leveraging Tekton pipelines in Jenkins X.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
