### ISSUE TITLE
batch mode prompts for input that i've already given it when invoking jx create cluster gke

### ISSUE THREAD

**Issue by alphabettispaghetti** [jenkins-x/jx#3346]
### Summary 
batch mode prompts for already specified input when running jx create cluster gke
### Steps to reproduce the behavior
running the command
```
jx create cluster gke \
 --batch-mode \
 --cluster-name "${cluster_name}" \
 --default-environment-prefix "${environment_prefix}" \
 --disk-size "${disk_size}" \
 --git-api-token "${git_api_token}" \
 --git-private \
 --git-username "${git_username}" \
 --kaniko \
 --machine-type "${machine_type}" \
 --max-num-nodes "${max_num_nodes}" \
 --min-num-nodes "${min_number_nodes}" \
 --project-id "${project_id}" \
 --zone "${zone}" \
```
with the variables
```
cluster_name='fierynandos'
environment_prefix="${cluster_name}"
disk_size='25'
git_api_token='xxxx'
git_username='alphabettispaghetti'
machine_type='n1-standard-1'
max_num_nodes='5'
min_num_nodes='1'
project_id='xxxx'
zone='europe-west2-a'
```

### Expected behavior
jx proceeds to create the cluster as specified
### Actual behavior
I am prompted me for the minimum number of nodes to create. (which I have already specified)
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.974
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.10.11
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.20.1
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ x] Classic Jenkins

### Kubernetes cluster

created with jx

### Operating system / Environment
MacOS 10.14.3

**Comment by tdcox** [comment]
There are a couple of additional items that also are related:

1. Options explicitly set to false are often not respected and a prompt is issued.
2. For some prompts, it is unclear if an option exists to pre-configure or disable them.

As a result, it isn't possible to write a definitive description of the configuration of a cluster since someone may be presented with choices that allow them to vary from the expected configuration. This makes it hard to reproduce a cluster accurately and repeatably.

**Comment by alphabettispaghetti** [comment]
I forgot to add that this script worked yesterday without prompting (on Wednesday 13th) but not today

**Comment by cyclingwithelephants** [comment]
Any news on this? I can't automate the creation and provisioning of a cluster because of this
