### ISSUE TITLE
Unclear what git user is required on project creation

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#3382]
### Summary 

When creating a new project the phrases "local Git user for GitHub server" and "pipelines Git user for GitHub server" are used. It's not 100% clear what these are used for and when a "bot" user should be/needs to be used.

### Steps to reproduce the behavior

Run any `jx create quickstart`.

**Comment by davidcurrie** [comment]
As a starting suggestion (and I'm positive this can be bettered) how about "GitHub user to be used for interactions on this machine" and "Shared GitHub user to be used by the CI/CD pipeline"?

**Comment by jglick** [comment]
There is a Prow RFE https://github.com/kubernetes/test-infra/issues/10423 for conversion to a GitHub App. We should at least consider having a (recommended) option to do the same for JX generally rather than relying on bot accounts and their personal access tokens. This would provide a better UX and better security. The workflow for installing JX would be somewhat different, because as I understand it the CLI would need to somehow guide you the organization admin to set up the app on github.com while offering an ingress URL to enter when prompted.

**Comment by tdcox** [comment]
This is still a current issue.

/remove-lifecycle stale
