### ISSUE TITLE
jx create cluster gke terraform issue

### ISSUE THREAD

**Issue by danielleffler** [jenkins-x/jx#3641]
### Summary 
When installing a cluster with terraform it fails to update cluster labels because it is missing zone or region flag
### Steps to reproduce the behavior
jx create cluster gke terraform --skip-login \
--project-id ${PROJECT_ID} \
--service-account ${GOOGLE_APPLICATION_CREDENTIALS} \
--cluster-name devops-australia-dev \
--enable-autoupgrade \
--machine-type n1-standard-2 \
--zone us-central1-a \
--min-num-nodes 3 \
--max-num-nodes 3 \
--git-api-token ${GIT_API_TOKEN} \
--skip-installation \
--batch-mode
### Expected behavior
It should finish without errors
### Actual behavior
```
ERRO[0928] Error: Command failed  gcloud container clusters update devops-australia-dev --update-labels=created-by=root,created-with=terraform,created-on=20190416032513 
ERRO[0928] error creating cluster exit status 1         
error: exit status 1
```

Manual execution of the previous command outputs the following
```
ERROR: (gcloud.container.clusters.update) One of [--zone, --region] must be supplied: Please specify location.
```
### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               1.3.1114
git              git version 2.7.4
Operating System Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

1.11.7-gke.12 created with terraform files generated by jx

### Operating system / Environment

Ubuntu 16.04.6 LTS running in docker

**Comment by deanesmith** [comment]
Hi @danielleffler, We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.  It would also appear that recent efforts by the Jenkins X team to better support Terraform with Jenkins X and Tekton may address your issue.  Refer to https://github.com/jenkins-x/terraform-google-jx.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
