### ISSUE TITLE
Jenkinsx - 503 service temporary available

### ISSUE THREAD

**Issue by skatkar** [jenkins-x/jx#3681]
### Summary 
I set up the CI CD pipeline on GKE using JenkinsX. The build step is successful, but if I hit the staging URL, it shows me the page with 503 Service temporarily unavailable. I know that JenkinsX deploys the application behind nginx. Do I need do to any configuration so that nginx can lookup the application? I tried reinstalling the jx command, I could see that nginx is installed. INFO[0463] nginx ingress controller installed and configured. 

### Expected behavior
Application endpoint should be available using the command: jx get --env staging

### Actual behavior
503 Service temporarily available

### Jx version
2.0.21

The output of `jx version` is:

```
NAME                     VERSION
jx                             2.0.21
jenkins x platform   0.0.3877
Kubernetes cluster  v1.11.7-gke.12
kubectl                    v1.11.9-dispatcher
helm client              Client: v2.13.1+g618447c
git                            git version 2.11.0
Operating System   Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type
- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
Kubernetes version 1.11.7-gke.12
Created using - jx create cluster gke --skip-login

### Operating system / Environment
Debian GNU/Linux 9.8 (stretch)

**Comment by pmuir** [comment]
Please provide the build logs for the staging env.

**Comment by deanesmith** [comment]
Hi @skatkar, We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
