### ISSUE TITLE
Jenkinsx - Production promote failing due to connection refused error

### ISSUE THREAD

**Issue by skatkar** [jenkins-x/jx#3682]
### Summary 
I am trying to build a CI/CD pipeline on GKE. But the promotion from staging to production is failing due to connection refused error.

To resolve the issue, I referred the solution suggested at https://github.com/jenkins-x/jx/issues/469 by updating the version of exposecontroller. Still, it is not resolved. I could see error like this:

```
+ jx step helm build

{"level":"warning","msg":"No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080\n","time":"2019-04-17T01:17:40Z"}

{"level":"info","msg":"Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io\n","time":"2019-04-17T01:17:42Z"}

{"level":"info","msg":"Successfully added Helm repository chartmuseum.jenkins-x.io.\n","time":"2019-04-17T01:17:43Z"}

{"level":"info","msg":"Adding missing Helm repo: jenkins-x-chartmuseum:8080 http://jenkins-x-chartmuseum:8080\n","time":"2019-04-17T01:17:43Z"}

{"level":"info","msg":"Successfully added Helm repository jenkins-x-chartmuseum:8080.\n","time":"2019-04-17T01:17:43Z"}

error: failed to build the dependencies of chart '.': failed to run 'helm dependency build' command in directory '.', output: 'Hang tight while we grab the latest from your chart repositories...

...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):

    Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
```

### Steps to reproduce the behavior
Promote the application from staging to production using
```
jx promote -v 0.0.3 production
```

### Expected behavior
Build promoted to production

### Actual behavior
```
Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
```
### Jx version

The output of `jx version` is:

```
NAME                     VERSION
jx                             2.0.21
jenkins x platform   0.0.3877
Kubernetes cluster  v1.11.7-gke.12
kubectl                    v1.11.9-dispatcher
helm client              Client: v2.13.1+g618447c
git                            git version 2.11.0
Operating System   Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type
- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
Kubernetes version 1.11.7-gke.12
Created using - jx create cluster gke --skip-login

### Operating system / Environment
Debian GNU/Linux 9.8 (stretch)

**Comment by jstrachan** [comment]
is this step running in a pipeline? It looks like a bad helm repository has been added - what’s the output of `helm repo list`

**Comment by skatkar** [comment]
```
helm repo list
NAME            URL
stable          https://kubernetes-charts.storage.googleapis.com
local           http://127.0.0.1:8879/charts
jenkins-x       http://chartmuseum.jenkins-x.io
myservices      http://chartmuseum.jx.35.192.107.89.nip.io
```
If I click on the second URL(i.e. local), it says '_Ensure your server is listening on port 8879 and try again_.'

**Comment by pmuir** [comment]
local shouldn't be there, try removing it from help

**Comment by gurushub** [comment]
Facing the same issue:
NAME                            URL
stable                          https://kubernetes-charts.storage.googleapis.com
local                           http://127.0.0.1:8879/charts
jenkins-x                       https://storage.googleapis.com/chartmuseum.jenkins-x.io
chartmuseum.jenkins-x.io        http://chartmuseum.jenkins-x.io


How to remove the local and update to what? Can someone help?

/area jenkins

**Comment by srehmanproov** [comment]
same issue here without any local helm repo
`stable                  	https://kubernetes-charts.storage.googleapis.com
jenkins-x               	https://storage.googleapis.com/chartmuseum.jenkins-x.io
charts.bitnami.com      	https://charts.bitnami.com/bitnami
charts.jetstack.io      	https://charts.jetstack.io
chartmuseum.jenkins-x.io	http://chartmuseum.jenkins-x.io`

**Comment by jatikuma29iv** [comment]
### Solution
**Open `git` repo of `production` env**
1. switch to `jx` namespace
  `jx ns jx`
  assuming `jenkins X` is installed in namespace `jx`
1. switch to `dev` env
  `jx env dev`
1. run cmd `jx get env`
Click on `production` env `url` to open `git` repo eg. https://github.com/<user>/environment-<your_env_name>-production.git

**Remove following lines from the file `env/requirements.yaml`**
In the `git` repo of `production` open file `env/requirements.yaml` and delete following lines
```yaml
- name: env
  repository: http://jenkins-x-chartmuseum:8080
  version: x.x.x
```

**Now execute promote cmd again**
1. Go to cmd line and change to root folder of you source code
  `cd /path/of/you/source/code`
2. switch to `jx` namespace
  `jx ns jx`
  assuming `jenkins X` is installed in namespace `jx`
3. switch to `dev` env
  `jx env dev`
4. run promote cmd (replace `0.0.2` with your version)
  `jx promote --version 0.0.2 --env production`
  answer questions and approve newly created `Pull request` on `production` `git` repo
5. check activity logs
  `jx get build logs`
6. you can also activity logs (replace <your_app_name> with name of ur `app`)
  `jx get activity -f <your_app_name> -w`
  select the first filter, should be ending with `#xx production`

Promotion to production should succeed.

### Reason
If cmd `jx promote --version 0.0.2 --env production` is executed from folder of source `git` folder, `Jenkins X` does a `env promote` instead of `app promote`
This adds following config in the `env/requirements.yaml`, setting env version to the `--version x.x.x` provided
```yaml
- name: env
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
```
after this promotions keeps failing.

Execute promote cmd from within the source root folder.

**Comment by stepanselyuk** [comment]
It can be related to OOM Killer. Just after an attempt to build you need to check every of your Node machine logs for OOM: 
```
sudo grep -i 'killed process' /var/log/messages
```

I got these because there was not enough memory for agent builder (like 128MB for template jx-base). So I modified builder template jx-base (namespace jx, config maps), increased memory. It won't be applied before you will restart Jenkins pod (not just restart Jenkins via UI, but the pod).
