### ISSUE TITLE
GetLifecycle does not include the Promote

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3733]
### Summary 

The Promote lifecycle is missing from the GetLifecycle function but it is available in the `jx create step` command.

### Steps to reproduce the behavior

```bash
jx create step

? Pick the pipeline kind:  pullrequest
? Pick the lifecycle:  promote
? Pick the create mode:  post
? Command for the new step:  jx get preview --current
```

### Expected behavior

The step was added to jenkins-x.yml

### Actual behavior

An error is thrown.

```
error: unknown pipeline lifecycle stage: promote
```

### Jx version

The output of `jx version` is:

```
jx               2.0.38
git              git version 2.20.1 (Apple Git-117)
Operating System Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Any

### Operating system / Environment

macOS

**Comment by hferentschik** [comment]
I tried the promote lifecycle example using jx 2.0.399 and it works as expected. I also see that there was a PR merged referencing this issue. I am going to close it.

That said, `jx create step` seems a bit out of date. For example you cannot specify an image and it uses the command for with commands and args on the same line. So it really would need to be  updated in general. However that's a different issue. I am also tempted to suggest to remove the commands altogether, since it adds little value and is imo more of a maintenance burden.

@vfarcic, wdyt about the usefulness of this command?

**Comment by vfarcic** [comment]
I think that `jx create step` is very useful, at least to those who are beginning with pipelines. I like that it is simple and provides very basic (but commonly used) features. Extending it to support everything we can do in pipelines would probably make it too complex for what it's meant to be.

**Comment by hferentschik** [comment]
> I think that jx create step is very useful, at least to those who are beginning with pipelines.

Interesting. Would proper/better documentation not suffice? I have a hard time keeping an overview over all the commands we have in `jx`. In fact I was not even aware of `create step`. I think it takes quite some effort to "find" this command and understand what it does. And once you have found it it quickly outlives its usefulness. I cannot see that anyone would use it to build a whole pipeline. It also suffers from the fact that you still need to see the actual YAML file to see the final result or to decide where to insert the next step.

IMO there are already too many commands in `jx` as it stands now. Each command must carry its weight, if not it should be removed. One can always add it back if people ask for a feature like this.
