### ISSUE TITLE
jx-app-jenkins not installed and unable to login

### ISSUE THREAD

**Issue by mikelear** [jenkins-x/jx#3760]
**Summary**

After I've run a JX create cluster with some parameters (on Azure aks) , I can't run 
JX console 
I get an error 

error: No Jenkins App services found in namespace jx with selector jenkins.io/kind=jenkins
Are you sure you installed a Jenkins App in this namespace?
Try jx add app jx-app-jenkins

When I was previously trying out Jenkins-X , jx console worked after the initial create cluster command.

I then ran
jx add app jx-app-jenkins

and JX console now launches , but I can't log in using the admin password.

The create cluster including the parameters were , so nothing that different 
 
jx create cluster aks -n mqube  --cluster-name mqubeaks  --default-environment-prefix mqube
 
**Steps to reproduce the behavior**

Run the command 
jx create cluster aks -n mqube  --cluster-name mqubeaks  --default-environment-prefix mqube

**Expected behavior**

Install the jx-app-jenkins and log in using the admin password.

**Actual behavior**

Didn't install the app and after manually installing the admin password won't allows login.

Jx version

NAME               VERSION
jx                 2.0.46
jenkins x platform 2.0.120
Kubernetes cluster v1.12.7
kubectl            v1.11.9
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.13.4 build 17E199

**Jenkins type**

- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Kubernetes cluster**

Azure AKS using the create cluster aks (shown above)

**Operating system / Environment**

MacOS

**Comment by jstrachan** [comment]
I wonder if your new cluster you setup does not have Jenkins server installed due to the new default to use serverless jenkins X pipelines with tekton? 
https://jenkins-x.io/about/status/#16th-april-2019-jenkins-x-2-x

if you really want to use a static jenkins server as the execution engine when installing make sure you pick the `Static Jenkins Server` option instead of the serverless one. (there's a new `--static-jenkins` CLI coming soon on the installer).

The custom jenkins app is intended for custom Jenkinsfiles rather than for the automated CI/CD in Jenkins X for kubernetes workflow: https://jenkins-x.io/architecture/custom-jenkins/ 

There's a known limitation though - here's how to get the login/pwd https://jenkins-x.io/architecture/custom-jenkins/#getting-the-login-password

**Comment by mikelear** [comment]
thanks @jstrachan that is/was the case , I hadn't noticed the default changes and had picked serverless , thanks again
