### ISSUE TITLE
add better CI tests for maven projects to validate plugins?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#390]
it looks like odd things can happen for spring boot apps if folks remove the parent pom.xml.

I wonder if we can add a nice CI test that fails if someone makes a PR that leaves some common plugins (like jar / compiler / deploy / surefire) without versions? Then the CI would fail until folks added an explicit version

**Comment by jtnord** [comment]
you can use the enforcer-plugin from the command line to ensure that all plugins have versions specified for the lifecycle (however it may be that needs to be part of the lifecycle to work out what plugins are excersized, rather than just defined)

> like jar / compiler / deploy / surefire

these should all be locked down if using maven 3 or higher in the super pom (but relying on that is not great as you can get different things depending on the version of maven that you are using).
