### ISSUE TITLE
jx promote hangs in loop waiting on staging pr

### ISSUE THREAD

**Issue by GingerBuffalo** [jenkins-x/jx#3936]
### Summary 
jx promote hangs waiting to get status of pr on staging repository. Webhooks don't appear the culprit. 

### Steps to reproduce the behavior
1. Source repo hosted on gitlab EE running in jenkinsx cluster. 
2. jx import a project. 
3. Verify webhooks created as expected on code repo, and staging and prod gitops repos. 
4. Trigger a change on master branch in code repo. 
5. Verify code repo webhook fired without error.

### Expected behavior
- Jenkins build job runs successfully. 
- pr is created on staging, and auto-approved, merged, and closed. 
- jx promote detects pr is auto-approved and merged, and exits gracefully. 

### Actual behavior
- jx promote hangs on pr forever. 
- Even when pr is manually approved, jx promote does not seem to tell. 

### Jx version

The output of `jx version` is:

WARNING: Failed to find helm installs: Cannot parse gitlab	3       	Tue May  7 08:12:22 2019	DEPLOYED	gitlab-1.8.4  	11.10.4    	varmygitlab as helm list output
NAME               VERSION
jx                 2.0.108
Kubernetes cluster v1.12.7-3+1a4d39a9763d23
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E227
WARNING:
A new jx version is available: 2.0.119

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [X ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

OKE (Oracle)
Created via terraform

### Operating system / Environment

MacOS, Mojave

**Comment by dodwyer** [comment]
I believe we are seeing a similar issue

`+ jx promote -b --all-auto --timeout 10m --pull-request-poll-time=60s --no-wait=true --version 0.0.7
Promoting app service-1 version 0.0.7 to namespace jenkins-x-staging
Created Pull Request: https://gitlab.example.com/jenkinsx/environment-faceheather-staging/merge_requests/6`

`WARNING: Failed to query the Pull Request last commit status for https://gitlab.example.com/jenkinsx/environment-faceheather-staging/merge_requests/6 ref 6d94f2300084efb12f1462ab887cfd500cc72261 could not find a status for repository 209 with ref 6d94f2300084efb12f1462ab887cfd500cc72261`

`WARNING: Failed to merge the Pull Request https://gitlab.example.com/jenkinsx/environment-faceheather-staging/merge_requests/6 due to PUT https://gitlab.example.com/api/v4/projects/209/merge_requests/6/merge: 405 {message: 405 Method Not Allowed} maybe I don't have karma?`

`error: Timed out waiting for pull request https://gitlab.example.com/jenkinsx/environment-faceheather-staging/merge_requests/6 to merge. Waited 10m0s`

But the promote command has worked, the merge request was created, merged and our staging environment was updated.

**Comment by blademainer** [comment]
same issue

**Comment by bnerDY** [comment]
same issue
