### ISSUE TITLE
cant login password wrong

### ISSUE THREAD

**Issue by djholly123** [jenkins-x/jx#3939]
### Summary 

Cant login to set token password is wrong whatever I try

### Steps to reproduce the behavior
jx install --docker-registry ldsdevacr.azurecr.io --default-admin-password #password#

### Expected behavior
Login OK with specified password and complete the install and configure JenkinsX manually 

### Actual behavior
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode Jenkinsfile

        ********************************************************

             NOTE: Your admin password is: ←[32m<password>←[0m

        ********************************************************

Configure Jenkins API Token
Generating the API token...
←[33mWARNING←[0m: Failed to log in via modern security realm: 500 Server Error
←[33mWARNING←[0m: failed to generate API token over REST API of server http://jenkins.jx.40.118.17.20.nip.io due to: log
ging in: cookies did not work; bad login or not using legacy security realm: 403 Forbidden
So unfortunately you will have to provide this by hand...

Please go to ←[32mhttp://jenkins.jx.40.118.17.20.nip.io/me/configure←[0m and click ←[32mShow API Token←[0m to get your A
PI Token
Then COPY the token and enter in into the form below:

### Jx version

The output of `jx version` is:
C:\Users\mc>jx version
NAME               VERSION
jx                 ←[32m2.0.119←[0m
jenkins x platform ←[32m2.0.276←[0m
Kubernetes cluster ←[32mv1.12.7←[0m
kubectl            ←[32mv1.13.1←[0m
helm client        ←[32mClient: v2.13.1+g618447c←[0m
git                ←[32mgit version 2.7.0.windows.1←[0m
Operating System   ←[32mWindows 10 Enterprise 1809 build 17763←[0m
```
COPY OUTPUT HERE
```

### Jenkins type
Classic

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Operating system / Environment
AKS

Windows 10

**Comment by ozdemirkan** [comment]
I had similar problem and setting both username and password worked for me. 

--default-admin-password string         the default admin password to access Jenkins, Kubernetes Dashboard, ChartMuseum and Nexus
      --default-admin-username string         the default admin username to access Jenkins, Kubernetes Dashboard, ChartMuseum and Nexus (default "admin")

**Comment by deanesmith** [comment]
Hi @djholly123, 

We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
