### ISSUE TITLE
Custom build agents for windows

### ISSUE THREAD

**Issue by deepakkt-a** [jenkins-x/jx#4110]
Team,

I am reviewing this document - https://jenkins-x.io/getting-started/create-custom-builder/#readout - about building custom build agents.

Assuming my k8s cluster will have windows nodes, is there anyway to build custom windows build agents? Specifically

* Both base images are linux images
* How would I tell jx to filter nodes to use only the win agents for builds?

Is this at all possible now or am I missing something?

Thanks!

**Comment by warrenbailey** [comment]
I'm not sure I understand your question. I'm assuming your Windows nodes have the container runtime on them, i.e docker? If so, you should be able to run linux based build images on them?

Or do you want build agents that are running window based containers?

**Comment by DenisPalnitsky** [comment]
We want build-agents that runs Windows containers.  To implement .NET Framework CI pipeline (build and unit-tests) we need to run build tools like MSBuild that works only on Windows. 

Please don't confuse with .NET Core that could run on Linux.

**Comment by warrenbailey** [comment]
Ah ok, I understand now. Basically you want a builder image that extends from the windows container. This is not something we have right now but definitely something to add in the future.

**Comment by DenisPalnitsky** [comment]
I wonder how long it will take to add this?
I would be happy to help with implementation however I need some guidance on what has to be done. 
Right now my understanding is that we need builder-base based on Windows but would that be enough to just have an image similar to [this](https://hub.docker.com/_/microsoft-windows-base-os-images) but based Windows?

_We work on POC based on JenkinsX that will potentially run  150+ products, 30% of them are .net so it will make a big difference if we could support it. That's why we will be more than happy to help._
