### ISSUE TITLE
Vault not starting up

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#4205]
### Summary 

Vault not starting up during `jx create cluster gke ...`

```
Lets set up a Git user name and API token to be able to perform CI/CD

ERROR: error creating cluster configuring the git auth: creating the git auth config service: wait for vault to be initialized and unsealed: reading vault health: Error making API request
```

### Steps to reproduce the behavior

`jx create cluster gke -n [clustername] --docker-registry=gcr.io --vault=true --tekton=true`

### Expected behavior

Has worked in the past, should work once again

### Actual behavior

Exits jx in error state after having created cluster but fails to finish setup.

`bank-vaults` container has this error message:
`level=fatal msg="error initializing vault: error testing if vault is initialized: Get http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: connect: connection refused"`

`vault` container has this error message:
`[WARN] storage migration check error: error="failed to read value for "core/migration": googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>jx-vault-[clustername]-sa@[project-id].iam.gserviceaccount.com does not have storage.objects.get access to jx-vault-[clustername]-bucket/core/migration.</Details></Error>"`

### Jx version

The output of `jx version` is:

same happens with `jx 2.0.237`

```
jx                 2.0.230
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.12.8-dispatcher
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS

**Comment by sdoxsee** [comment]
I believe I had a stale IAM permission left over on a service account that wasn't deleted by `jx uninstall platform`. Deleting this seemed to fix. See: https://console.cloud.google.com/iam-admin/iam

**Comment by freeo** [comment]
I would like to see this issue reopened, as the suggest "fix" isn't working for me: I have the exact same issue, but with "Classic Jenkins". I've two clusters in two separate projects. In one, installing vault went fine using:
```
jx create addon vault-operator
jx create vault -n jxvault vault-sandbox
```

The 2nd has crash loops on the containers `bank-vault` and `vault` due to the errors in your "Actual Behaviour" (Access Denied, connection refused, etc.)

I've configured IAM identically for both projects, as are clusters (using the same terraform plan). Matching the service accounts did NOT fix the issue for me. I can't make out what makes the vault installation fail (both during `jx install` and `jx create vault`). Any ideas?
