### ISSUE TITLE
verify Jenkins X works on OpenShift

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#435]
e.g. so we can do `jx install --provider=openshift` and check things all work

**Comment by jstrachan** [comment]
I just tried out minishift and after adding `cluster-admin` to the `developer` via 
```
oc adm policy add-cluster-role-to-user cluster-admin developer
```
then jx install fails like this:
```
$ jx install --provider=minishift
Context "default/192-168-64-39:8443/developer" modified.
Trying to create ClusterRoleBinding developer-192-168-64-39-8443-cluster-admin-binding for role: cluster-admin for user developer-192-168-64-39-8443
clusterrolebinding "developer-192-168-64-39-8443-cluster-admin-binding" created
Created ClusterRoleBinding developer-192-168-64-39-8443-cluster-admin-binding
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
retrying after error:Failed to create ClusterRoleBindings tiller: the server could not find the requested resource
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
retrying after error:Failed to create ClusterRoleBindings tiller: the server could not find the requested resource
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
helm init failed: after 3 attempts, last error: Failed to create ClusterRoleBindings tiller: the server could not find the requested resource
error: after 3 attempts, last error: Failed to create ClusterRoleBindings tiller: the server could not find the requested resource
```

I wonder if openshift 3.7.x supports k8s RBAC cluster roles? maybe the API versions are different?

**Comment by rawlingsj** [comment]
I saw this a little while ago - wonder if there's something here https://blog.openshift.com/getting-started-helm-openshift/

**Comment by jstrachan** [comment]
thanks! good catch

FYI @rukkus

**Comment by rukkus** [comment]
Thanks that link helped, moving the RBAC API to v1beta1 in [common_kube](pkg/jx/cmd/common_kube_rbac.go) got past the tiller account issues.

What would be the knock on effect of moving to that API instead of V1 RBAC?

Next issue is due to the lack of an ingress controller. Maybe we should consider using routes instead of ingress when running on OpenShift? I was reading that routes were being reworked to use ingress under the hood but I'm not sure what state that is in at the moment. 

`? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Error: incompatible versions client[v2.8.2] server[v2.6.1]
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: incompatible versions client[v2.8.2] server[v2.6.1]
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: incompatible versions client[v2.8.2] server[v2.6.1]
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: incompatible versions client[v2.8.2] server[v2.6.1]
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found
`
I'll keep digging...

**Comment by rawlingsj** [comment]
> What would be the knock on effect of moving to that API instead of V1 RBAC?

Not too sure about this one, wonder if we can create different versioned resources depending on the cluster @jstrachan?

> Next issue is due to the lack of an ingress controller. Maybe we should consider using routes instead of ingress when running on OpenShift?

As it happens Jenkins X uses a controller called exposecontroller which we can use to generate Ingress rules or OpenShift routes.  It's not been tested but using the latest jx you should be able to run with these flags to switch to Routes being created and avoid the ingress controller being installed..
```
jx install --provider=minishift --skip-ingress-true --exposer=Route
```

**Comment by rukkus** [comment]
That seems to go further again, looks like I have a helm version clash. I'll sort that and see where it finishes.

**Comment by rawlingsj** [comment]
Ok great - keep us posted!

**Comment by rukkus** [comment]
Next one seems to be another RBAC issue, this time when installing the platform helm chart. 

`helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.364 --values=/Users/davidconde/.jx/gitSecrets.yaml --values=/Users/davidconde/.jx/adminSecrets.yaml --values=/Users/davidconde/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: apiVersion "rbac.authorization.k8s.io/v1" in jenkins-x-platform/charts/cleanup/templates/role.yaml is not available
make: *** [install] Error 1`

I'll have a look at changing around the charts a bit tomorrow evening :)

**Comment by tdcox** [comment]
Would be good to solve the cluster-specific resource issue as 1.9 has moved Deployment to apps/v1

**Comment by jstrachan** [comment]
I just took a stab at using 3.9.0.x of openshift via minishift.
```
minishift start --vm-driver=xhyve --memory=9000 --cpus=5 --disk-size=50g --openshift-version=v3.9.0-alpha.3
```
and tried
```
oc login -u system:admin
jx install --provider=minishift --skip-ingress=true
```
then I got the following failure in the jenkins pod - I guess we need some more karma or something:

```
    message: 'pods "jenkins-7c5f478f64-" is forbidden: unable to validate against
      any security context constraint: [spec.initContainers[0].securityContext.securityContext.runAsUser:
      Invalid value: 0: must be in the ranges: [1000080000, 1000089999] spec.containers[0].securityContext.securityContext.runAsUser:
      Invalid value: 0: must be in the ranges: [1000080000, 1000089999]]'
```

**Comment by billyfoss** [comment]
Does the following help?
https://docs.openshift.org/3.9/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root

It looks like Jenkins X is trying to run as root.

**Comment by jstrachan** [comment]
@billyfoss thanks I'll give that a try!

**Comment by jstrachan** [comment]
@billyfoss many thanks; adding that things work much better on `minishift` with 3.9.0; jenkins runs perfectly now. I also switched to using `Route` instead of `Ingress` too. 

The remaining issue seems to be mongodb (from monocular) barfs - its stuck in a crashloop:
```

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> Starting mongodb...
sed: can't read /bitnami/mongodb/conf/mongodb.conf: No such file or directory
INFO  ==> Starting mongod...
error: failed switching to "mongo": unable to find user mongo: no matching entries in passwd file
```

**Comment by jstrachan** [comment]
OK I'm past the mongodb issue  (adding anyuid to `default` ServiceAccount) - seems fixing that has now broken nexus ;)

**Comment by jstrachan** [comment]
think I've a fix in the new nexus release... getting close!

**Comment by jstrachan** [comment]
ok so the next issue is now Jenkins can't create pods using the docker socket:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/jx/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "maven-6wqbh" is forbidden: unable to validate against any security context constraint: [spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed].
```

**Comment by jstrachan** [comment]
very very close now....

**Comment by jstrachan** [comment]
works now on 3.9.0 - for example for minishift: http://jenkins-x.io/commands/jx_create_cluster_minishift/

**Comment by rukkus** [comment]
Awesome, apologies for not getting back to look at it. I’m tied up in a very busy release lately. Looking forward to taking it for a spin and getting it up and going.

**Comment by metmajer** [comment]
Wow, great work @jstrachan. Has anybody taken an attempt to run this on an OpenShift Enterprise cluster?

**Comment by jstrachan** [comment]
@metmajer not that I know of yet. We've tested 3.9.0 in MiniShift which works great. It'd be good to test on 3.9.x of OpenShift Enterprise too.

Totally agreed on the `anyuid` comment. We're currently using these commands so that the current images all work on OpenShift: https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/install.go#L502

We'd need more work on things like Jenkins + Monocular so that we can run on OpenShift Enterprise with weaker security restrictions. Hopefully we can iteratively make it easier to install on OpenShift Enterprise

**Comment by jstrachan** [comment]
@metmajer agreed! Plus if we need to we can tweak values for OpenShift (e.g. using different base images and so forth) in the OpenShift [values.yaml](https://github.com/jenkins-x/cloud-environments/blob/master/env-openshift/myvalues.yaml)

**Comment by metmajer** [comment]
Nice tip, @jstrachan. I'll might open a new issue and look into this as soon as I find the time.

**Comment by jstrachan** [comment]
@metmajer great stuff - many thanks!

**Comment by metmajer** [comment]
@jstrachan here's a question with regards to selecting an appropriate container image when running on OpenShift. If I understand your code in https://github.com/jenkins-x/jx/blob/be339383169066028ddd4709ed99727af11ff7e9/pkg/jx/cmd/import.go#L479 you're deferring the task of image creation to `draft` (imported from `github.com/jenkins-x/draft-repo`). Now, since draft packs define the image name hard-coded in the Dockerfile, I am not sure that placing values in `values.yaml` would be a viable approach. Being new to this project, I might very well be totally off here.

Here's a suggestion. Red Hat created a project named `s2i` (https://github.com/openshift/source-to-image) that is also used by the `oc` CLI, and which does a very similar job to `draft` (aimed towards K8S users). I think it would make sense to run `s2i` instead of `draft` within `jx` when the OpenShift provider has been selected. `s2i` basically combines a base (builder) image and source code into an executable target image, but it doesn't come with Helm charts. Typically, you'd select a builder image provided by Red Hat, which produces a target image that is ready to run on OpenShift. However, we'd need to do the technology guessing and technology->base image mapping ourselves, since this is not offered by `s2i`. This in turn, could very well be mapped out within the openshift `values.yml`. Thoughts?

**Comment by jstrachan** [comment]
so yeah, we're using [draft style build packs](http://jenkins-x.io/architecture/build-packs/) to default missing files for things like `Dockerfile` or `Jenkinsfile` and add default charts etc.

I know `s2i` quite well - TBH I'm not a huge fan as it does not let you use `Dockerfile`s which are the industry standard way of defining docker images with a [massive community of reusable docker images](https://hub.docker.com/). So while you're free to go with `s2i` on your own projects & could create your own build packs to move away from `Dockerfile`s in favour of `s2i` if you want to make your projects OpenShfit specific - we prefer folks stick to file formats and technologies that work in all kubernetes clusters really.

BTW we're using [skaffold](https://github.com/GoogleContainerTools/skaffold) to actually make the docker image so that we can use different strategies for the docker image creation; like local daemon, Google Cloud Builder or kaniko etc. Maybe one day someone may add an `s2i` like addon to skaffold?
