### ISSUE TITLE
lets use cloud provider native storage for chartmuesum 

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#457]
so we don't loose released charts if a PVC linked to a helm release get's deleted

**Comment by jtnord** [comment]
@rawlingsj this is not clear to myself of @oswaldohp, can you add some more details please?
PVCs are (so we understood) already cloud native.

**Comment by ccojocar** [comment]
@jtnord @oswaldohp The idea is to use a more durable storage solutions such as Google Cloud Storage or AWS S3 instead of PVC (e.g. PVC needs to be resized, backed up etc.). Chartmuseum supports various cloud storages as backend. 

In the meantime, we have an alternative solution which stores the charts in GCS for jx production infrastructure, I am not sure if a HA Chartmuseum is still a subject for us since is not anymore publicly exposed.

**Comment by jtnord** [comment]
@markbsigler @jennbriden one for you two.
