### ISSUE TITLE
JX Promote returns 404 and exits from the job

### ISSUE THREAD

**Issue by baskar030** [jenkins-x/jx#4573]
### Summary 
jx installed in GKE(Google Kubernetes engine) and configured bitbucket cloud repository.

When trying to promote the build using jx promote returns 
```
Promoting app sample-spring version 0.0.11 to namespace jx-staging

error: finding existing PRs using filter  on repo baskar030/environment-XXX-staging: listing open pull requests on baskar030/environment-XXX-staging: Status: 404 Not Found, Body: {"type": "error", "error": {"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}

script returned exit code 1
```
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
NAME               VERSION
jx                 2.0.398
jenkins x platform 2.0.744
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.12.8-dispatcher
helm client        Client: v2.13.1+g618447c
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G65
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [Y ] Classic Jenkins

### Kubernetes cluster

GKE Cluster  version 1.12.8-gke.10
### Operating system / Environment
Ubuntu

**Comment by hervelemeur** [comment]
Looking at your error message, it's almost certainly related to https://github.com/jenkins-x/jx/issues/2149

**Comment by baskar030** [comment]
@jstrachan Could you help me on this issue.

**Comment by baskar030** [comment]
Since it's issue with bitbucket integration I did below workaround 

For me only jx promote alone throws 404 from bitbucket, so using the charts folder of microservice I directly used helm install / upgrade to promote the builds to kubernetes.

**Comment by valiksb** [comment]
@baskar030 could you provide the precise syntax you used to promote the microservice using helm install/upgrade?

**Comment by baskar030** [comment]
@valiksb Command to promote from Jenkins pipeline for first time deployment:
 helm install deploymentName --namespace namespace-name

To upgrade the existing deployment I will use helm upgrade

**Comment by valiksb** [comment]
@baskar030 I'm not sure how to execute the above. I tried this
`helm install http://chartmuseum.jx.x,x,x,x.nip.io/charts/new-jx-project-0.0.1.tgz --namespace jx-staging`
but the I see that a new release is added
`hoping-buffoon               1           Mon Aug 19 16:39:14 2019    DEPLOYED    new-jx-project-0.0.1          0.0.1          jx-staging`
while I believe it should be under jx-staging
`jx-staging                   114         Thu Aug  8 17:57:13 2019    DEPLOYED    env-82                                       jx-staging`

I also have the issue that the ingress part is not added after running helm install. Hope you can help

**Comment by valiksb** [comment]
Ok guys I was finally able to solve this issue through the following workaround

1. `git clone urltoyourstagingorproductiongitopsenvironmentonbitbucket`
2. cd into the above folder
3. `git checkout by-nameofthedeveloper-promote-nameoftheservice-versionnumber`, normally jenkinx-x would name the branch promote-nameoftheservice-x.y.z, I just propose to prefix with the name of the person who manually is making the changes instead of the jx promote command
4. `vi env/requirements.yaml` (or your favorite editor)
5. Depending whether your are updating the version of an existing service that previously successfully deployed or a new service you would follow different steps
5.1. If you are adding a new service that has not been deployed before, copy one of the existing services and add it at the bottom of the file
`- name: nameofexistingservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4`
and edit the name and the version to something line
`- name: nameofthenewservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1`
5.2 If you are updating the go to that service increase the version number to the appropriate number
6. Save the file
7. `git commit .`
8. `git push` (you will get a response with the right command)
9. goto ` https://bitbucket.org/nameoforganization_or_bitbucketaccount/environment-name_of_staging_production/branches/` you should see the branch your create above
10. Create a Pull Request and then Merge, that will trigger the build of the staging or production environment and deploy the services
11. After several minutes you should see your new application/service with `jx get applications`
