### ISSUE TITLE
jx version always fails

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4866]
### Summary 
jx diagnose is failing with `error: package jx is on version 2.0.513 but the version stream requires version 2.0.404 exit status 1`

### Jx version

The output of `jx version` is:

```
jx                 2.0.513
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

**Comment by abayer** [comment]
So the issue here is that https://github.com/jenkins-x/jenkins-x-versions/commit/542d1089a5824fdb7acd0cfe6fce276877239097 added a `jx.yml` package, with a specific version in it, meaning that `jx version --no-version-check` is always going to return an error unless you're using that very specific version. I'm assign this to @jstrachan since I'm not sure why that was added.

**Comment by abayer** [comment]
Bumping this to urgent - under the hood, `jx version --no-version-check` is failing with errors like ```[failed to parse semantic version for current version git version 2.8.4 for package git: Invalid character(s) found in major number "git version 2", package jx is on version 2.0.537 but the version stream requires version 2.0.404, package kubectl is an old version 1.13.1. The version stream requires at least 1.13.2]```

The new `git.yml`, `jx.yml`, and `kubectl.yml` files in `jenkins-x-versions`'s `packages` directory is what's causing this, and it seems like a real problem.

**Comment by jstrachan** [comment]
this PR should fix it https://github.com/jenkins-x/jenkins-x-versions/pull/369
