### ISSUE TITLE
Vault should not be exposed via ingress

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#4925]
### Summary 

Vault is currently exposed via ingress. The need to expose Vault via ingress adds complexity and adds the need to have TLS correctly setup out of the box. To add an extra layer of security and to simplify the out of the box experience we should investigate removing the vault ingress and instead use something like `kubectl port-forward` so jx can access vault from outside the cluster.

**Comment by jstrachan** [comment]
`kubectl port-forward` is a great idea btw!

until we have a simple OOTB solution to the problem; maybe we just add a big warning if folks use Vault + no TLS and force them to enter `Yes` to agree things are gonna be insecure

**Comment by jstrachan** [comment]
maybe we can add an environment variable for vault; which if not specified uses the internal k8s service name? Then when running locally on your laptop we set the environment variable to point to the `kubectl port-forward` host/port?

**Comment by jstrachan** [comment]
I like the option of never creating an ingress to vault really!

**Comment by ccojocar** [comment]
The tunnel would need to be opened almost all the time because almost all commands dealing with git for instance will fetch the secrets from vault. 

Also the vault CLI is using the URL set by the vault config. Probably you will have to set up the tunnel when a user gets the config for vault client and keep it open that the user can access the vault over the vault CLI (e.g. to add secrets). 

IMO it is more robust to setup the TLS instead of making sure that the tunnel is always opened. Most likely the tunnel needs to be monitored to make sure is not closed and the user cannot executed jx commands.

**Comment by jstrachan** [comment]
pipelines would run inside the cluster so could use the local service name right? so we just need a way to mimic that behaviour when doing install/upgrades on a laptop don't we?

the `kubectl proxy` is really only intended for the duration of the `jx boot` interpreted pipeline - usually everything would be inside the cluster so have access to the vault service

**Comment by pmuir** [comment]
Dropping to `critical` as we now have a warning and docs in place for this.

**Comment by daveconde** [comment]
@garethjevans It would be good to get your thoughts on this one

**Comment by daveconde** [comment]
needs #3593
