### ISSUE TITLE
Garbage in Jenkins console

### ISSUE THREAD

**Issue by arun-gupta** [jenkins-x/jx#495]
`NaNy NaNd` is shown in `CI Build and push snapshot` stage.

<img width="712" alt="screen shot 2018-03-23 at 3 14 58 pm" src="https://user-images.githubusercontent.com/113947/37855556-0da5c45e-2ead-11e8-81d2-21c5f9d93340.png">

**Comment by rawlingsj** [comment]
@arun-gupta hey it's been a while and great to see you here! :)

I suspect this is because the CI step is skipped in Jenkinsfile, I think blueocean presents this better..

<img width="1343" alt="screen shot 2018-03-27 at 19 12 30" src="https://user-images.githubusercontent.com/1457180/37986252-e1e32016-31f2-11e8-9df8-815f36ce1d51.png">

FWIW we will be defaulting to blueocean https://github.com/jenkins-x/jx/issues/470 shortly but for now just append `/blue` to the end of the root Jenkins URL.  e.g. `http://jenkins.jx.1.2.3.4.nip.io/blue`

**Comment by arun-gupta** [comment]
@rawlingsj good to hear from you as well!

If the step is missing from `Jenkinsfile`, then we should clean up the output. `NaN` seems like a left over code?

**Comment by davidcurrie** [comment]
Looks like https://issues.jenkins-ci.org/browse/JENKINS-48881

**Comment by ccojocar** [comment]
@arun-gupta I am going to close this issue since it seems to be related to Jenkins. Thanks
