### ISSUE TITLE
Make it possible to disable metapipelines with an environment variable

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5085]
### Summary 
It should be possible to disable metapipelines wihtout having to modify the Prow chart.

A good way would be to disable it with an environment variable that could be added when building the values of the chart.

This way we could disable for the next CJXD release.

**Comment by hferentschik** [comment]
> A good way would be to disable it with an environment variable that could be added when building the values of the chart.

So we are talking about an environment variable for pipelinerunner, right? As part of building the values for the Prow chart, a env variable is added to the deployment config of the pipelinerunner, right?

I am asking since there seems to be two levels to it. The actual pipelinerunner deployment config and the rendering of the Prow chart. I would think the latter would need to be able to handle some sort of flag/env variable as well in order to then set or unset the variable for the pipelinerunner.

**Comment by hferentschik** [comment]
@dgozalo ooi why did you go from "in progress" to "on hold" on this issue?
