### ISSUE TITLE
Improve output of `jx get build logs`

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5169]
`jx get build logs` displays a header row for each container of the pipeline, followed by the plain logs. This makes it sometimes hard to know the context of the a given line:

![Screenshot 2019-08-22 at 11 11 07](https://user-images.githubusercontent.com/296354/63507685-94cdb500-c4d8-11e9-84b4-9cf7d469a03a.png)

I suggest we do something similar to the `tkn` log view, where each line gets prefixed with the contextual information:

![Screenshot 2019-08-22 at 11 18 11](https://user-images.githubusercontent.com/296354/63507730-b169ed00-c4d8-11e9-957c-50c01176b587.png)

We can make this also partly configurable via an option.

**Comment by tdcox** [comment]
That makes it very difficult to read the logs because most of the useful data is shifted off the screen to the right or wrapped. Also, the start of the important info will be staggered due to the variable length of the header, making it even worse to read. 

Colour should be reserved for extremely important items only.

**Comment by hferentschik** [comment]
This is a matter of taste I think. For just tailing the log in order to see the progress I much prefer the suggested new format. In other cases it the current format might be better. I think it is a matte of taste as well as use case. 

It does not have to be either or. We can add an option for it.
