### ISSUE TITLE
Fix flaky tekton logging tests

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5171]
`TestGetRunningBuildLogsWithMatchingBuildPods` and `TestGetRunningBuildLogsWithMultipleStages` failing  with e.g.

```Pipeline failed on stage 'from-fakebranch' : container 'build-step-promote-**-promote'. The execution of the pipeline has stopped.
    tekton_logging_test.go:425: 
        	Error Trace:	tekton_logging_test.go:425
        	Error:      	Not equal: 
        	            	expected: 21
        	            	actual  : 20
        	Test:       	TestGetRunningBuildLogsWithMatchingBuildPods


DONE 1112 tests, 5 skipped, 1 failure in 1486.637s
make: *** [test-slow-integration] Error 1
Step: step-stash-test-results:
```

**Comment by hferentschik** [comment]
The tests can be improved, however, they fail rightfully. There are a couple of issues with the current implementation of retrieving the build logs:

1. The logs are truncated and we are loosing messages from the end of the log, which is why what we have seen in the test runs and which led to the creation of this issue
1. Log lines can appear out of order, this happens specifically between the header line printed for each container and the actual log for this container

The problem is the unsynchronized use of goroutines (WaitGroup should be used if needed) and unsynchronized writes to the underlying writer (`WriteLog` vs `StreamLog`).
