### ISSUE TITLE
Allow the use of Self Signed Certificates for webhooks

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5187]
### Summary 

We are recommending using TLS always with Jenkins X. We can make this a bit less onerous on the user by allowing them to use self signed certs with webhooks, warning them appropriately.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by ccojocar** [comment]
The self-singed certificates have well known security exploitations. It is worth reading this:
* https://security.stackexchange.com/questions/8110/what-are-the-risks-of-self-signing-a-certificate-for-ssl
* https://www.venafi.com/blog/self-signed-certificates-cyber-criminals-are-turning-strength-into-a-vulnerability

They are more commonly used to secure internal communication rather than a public endpoint. In our case, webhook is a public endpoint registered into GitHub. This means that GitHub won't be able to trust our certificate (e.g. by disabling the certificate verification). Now imagine that someone can impersonate the jenkins-x domain (less likely but possible) and listen to GitHub events which contain also the webhook secret. GitHub has not way to detect that someone else than jenkins-x is eavesdropping on this connection. It is true that self-signed certs provides a better security than HTTP but also present a moderate security risk. I think is important to not provider users a false sense of security. IMO for a production ready installation, TLS is required period. 

@madchap What's your opinion on this?

**Comment by madchap** [comment]
I agree with @ccojocar and I would also be against authorizing the use of self-signed certs.

Could we leverage some automation around letsencrypt as to further the user experience around security?

**Comment by madchap** [comment]
After further discussions with @ccojocar , it seems you guys already have what's needed?

e.g. https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/templates/cert-manager-prod-issuer.yaml
