### ISSUE TITLE
jx create: support GitHub enterprise provider

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#525]
On a fresh install:
```
$ jx install --domain='cd.foo.bar' --git-provider-url='https://github.foo.bar' --git-username='bot-jenkinsx' --git-api-token='SSBhbSBjbGVhciB0ZXh0IG9tZwo=' --provider=gke
...
Created user admin API Token for Jenkins server  at http://jenkins.jx.cd.foo.bar
Creating default staging and production environments
Using git provider GitHub at https://github.com
error: Server https://github.com has no user auths defined!
```
It never asked me for any credentials (logic cause I provided one to the command line) but it keeps asking me for github.com even if I specified github.foo.bar.

Only github.com provider works for now.
It would be great to support others urls ;)

I'm willing to work with the github enterprise integration.
I saw in #37 that you need help on that part ?

**Comment by jstrachan** [comment]
I’ve added docs on adding git servers & tokens
http://jenkins-x.io/developing/git/

I wonder if you add the GHE server first you can then add a token?

**Comment by jstrachan** [comment]
@vgallissot btw would love help testing things on GHE! More than happy to lend a hand on the code side of things

**Comment by vgallissot** [comment]
Creating the `git server` before creating `git token` worked for me with `jx 1.1.44`

**Comment by jstrachan** [comment]
@vgallissot I'm about release a new version soon with full GitHub Enterprise support; where you can install Jenkins X using only GHE for environments and create projects, issues with working GitOps etc. Just doing a bit more testing before releasing the new platform chart - but the jx binary changes should be released now

**Comment by maniankara** [comment]
@jstrachan when you say GHE, I presume you meant any git server? Then this would be great. Well, we all know that there are lots of private (onpremise/cloud) instances of git who would like to use `jenkins-x`

**Comment by jstrachan** [comment]
@maniankara sorry I meant GitHub Enterprise. We've support for git integrations (along with issue trackers, chat etc too). So far GitHub + GHE are fully supported, bitbucket cloud + gitea are super close and others like gitlab are in the works: http://jenkins-x.io/contribute/roadmap/

**Comment by allen-servedio** [comment]
@jstrachan - it looks like this issue is still happening on the version of JX from today. I followed the instructions on https://jenkins-x.io/developing/git/ to add the provider and token. I tried an install where it prompted me to select the provider AND I tried doing the install where I set the `--git-provider-url`, `--git-username`, and `--git-api-token`.

In both cases the install failed with: 

```
logging in
Getting the API Token...
Found API Token
2018/07/03 16:26:54 error: could not perform (attributeModified) operation on node 88 (wait node): context canceled
Created user admin API Token for Jenkins server jenkins.jx.my-server-here.my-region.containers.mybluemix.net at http://jenkins.jx.my-server-here.my-region.containers.mybluemix.net
Creating default staging and production environments
Using git provider GitHub at https://github.com
error: Server https://github.com has no user auths defined!
```

Here are the two install commands I tried (again, on the first one, I was prompted for the git repo and selected our enterprise repo - the second one did not prompt me as I supplied it via command line params):
```
jx install --provider ibm --domain my-server-here.my-region.containers.mybluemix.net

# And after doing a `jx uninstall` and deleting the `~/.jx/` directory, I tried this one:

jx install --provider ibm --domain my-server-here.my-region.containers.mybluemix.net --git-provider-url='https://github.foo.com' --git-username='my-name-here' --git-api-token='my-token-here'
```

I guess that part of the install is loosing or ignoring what we are setting for those values.

**Comment by allen-servedio** [comment]
Okay, I think I know what is wrong now - this is more of a documentation issue than anything. I did NOT also create a token for github.com. I suspect what is happening here is that it was not able to get the repos that it was trying to clone from github.com and then be able to use our enterprise repo to set up the base environments. I have since added that token and can try destroying and recreating the install (will try later tonight or Thursday).

**Comment by allen-servedio** [comment]
Okay, confirmed, you have to add the git token for BOTH `github.com` and your enterprise repo (`github.foo.com`). After doing that, I was able to install with this command:

```
jx install --provider ibm --domain my-server-here.my-region.containers.mybluemix.net --git-provider-url='https://github.foo.com' --git-username='my-name-here' --git-api-token='my-token-here'
```

**Comment by allen-servedio** [comment]
However, it looks like it ignores `--git-provider-url` for WHERE to create the staging and production git repos - they are created on `github.com` instead (which is not what I wanted). Is this the expected behavior @jstrachan  (meaning this is actually a closed issue...)?

**Comment by empath** [comment]
when you say you need to add a token from both github and ghe, how do you do that?

**Comment by rawlingsj** [comment]
We have some docs here that should help https://jenkins-x.io/developing/git/#github-enterprise

**Comment by allen-servedio** [comment]
@empath - these are the docs for adding the token: https://jenkins-x.io/developing/git/#adding-user-tokens

You should run that for BOTH the enterprise github (after adding it per the docs that @rawlingsj  references) and for github.com. You need the later one because Jenkins X needs repos from the public github.com for some of its functionality (see #1241).

**Comment by softjake** [comment]
Excuse my ignorance but what is GHE stands for? I googled and got Green House Effect, Gaseous Hellium, ... but nothing that includes Git or Google. 

It's general practice that the first time you use an acronym in a text to add it's full meaning in parentheses. Helps newcomers like me to follow the conversation and not disturb the flow with a stupid question like this one. :-)

**Comment by jstrachan** [comment]
@softjake GitHub Enterprise  - apologies for not being more clear
