### ISSUE TITLE
Import/create should allocate team to git repos

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#527]
Currently, new git repos are created with access permissions for the creator only. This includes environment repos. Because of this, if another member of an organisation attempts to create a new project using jx, their build will fail when a write is attempted against the shared environment. 

Ideally, all members of the organisation sharing a jx instance should belong to a team and jx should allocate team permissions to all repos created. 

Workaround: Manually add the team to shared repos via the github UI (under <repo>/Settings)

**Comment by jstrachan** [comment]
yeah, we should really associate a git organization to a team & then default all the git repo creation wizards to that git org - so that environments & apps are all in that git organization- then folks can easily add users to the team in the git provider.

I’d love a CLI for managing teams which should add those users to the team git organization too - like

    jx create team user --team cheese --user someUsername

**Comment by hmcmanus** [comment]
I think the same problem occurs with bitbucket (cloud) and a project owning the repository. When I have assigned the access keys to be my user for testing jx assumes that this user will be the owner of the repositories. 

And during a jx import I get the following error:

{"type": "error", "error": {"message": "Repository username/repository-name not found"}}

But the repository which exists is under project ownership. 

If I was thinking about how to get around this the username would need to be matching the ownership of the repositories. App access keys would need to be created for the same. 

Not sure how this would work in a team environment where some needs control over the jx command line. 

Any ideas?

**Comment by mathieusama** [comment]
There appears to be no way to control access rights on new GitHub repositories created by JX. Our organisation has very strict security policies (ie: principle of least privilege) and members of the `engineering` GitHub team are only allowed access to repos specifically granted to that team. Therefore, as myself member of that team, I cannot even see the `environment-xxx-staging` repo created by JX. Is there any way to configure JX to automatically grant admin access to a specific GitHub team when creating new repos?

My colleagues don't understand why JX seems to require that all users be granted full access to the entire github organisation, but I assume there must be a reason or better way to go about it.

If that feature is really lacking, I would be willing to contribute it as a PR, if only someone on the JX team could give me some guidance on how to approach this. I already have all my environment setup for building `jx` and I've already explored the relevant code, but some guidance would still be greatly appreciated! :)

**Comment by hferentschik** [comment]
@mathieusama, atm there is no way to control this. The environment repos are created using the credentials of the Jenkins X bot user. Repositories created by `jx create quickstart` or `jx import` are created with the credentials of the developer executing these commands.

This works fine when everyone is in the same organisation and has access to all repositories in this organisation. In the scenario where permissions are configured on a per repo basis, it won't work w/o manual configuration. 

The question is where and how would you add the concept of a team to be added to a given repository? @mathieusama, do you have any suggestions?

**Comment by mathieusama** [comment]
I was hoping to get some insights from you guys on how to approach this, but I can definitely start with hypotheses and you tell me whether that's realistic! ;)

For us, the most important cases to cover in the short term seem to be:

- `jx create env`
  - We could pass the team name as an optional command-line argument.
  - Question: Would the team name need to be persisted in the `env` CRD? Because that would be a bit more involved.
- `jx create quickstart`
  - We could prompt for an optional team name as part of the quickstart prompts.

In general, there seems to be 2 sub-scenarios to cover (but I'm still unclear whether both apply to the above cases):

- When repository is created from scratch
  - Pass additional `team_id` parameter to POST request
  - see https://developer.github.com/v3/repos/#create
- When repository already exists or is being forked:
  - Add team to repository
  - see https://developer.github.com/v3/teams/#add-or-update-team-repository

What are your thoughts about that?

**Comment by hferentschik** [comment]
My concern around adding a new GitHub specific flag to `jx create env` and `jx create quickstart` is that it might end up to be too GitHub specific. In the end, the aim for Jenkins X is to support multiple git provider. Will all have the same concept of a team id? There might be an additional level of abstraction needed. 

I think it would be better to somehow model dev teams and users (either via the existing Team and User CRDs or something new) and then make sure that access to git repos is configured transparently according to these settings. I guess basically what @jstrachan said :-)
