### ISSUE TITLE
Go Builds Failing on Fresh JX Install on AWS EKS

### ISSUE THREAD

**Issue by ScottyVG** [jenkins-x/jx#5470]
### Summary 
Specifically, Golang pipeline builds are failing on the build release step of the pipeline. Other builds work for me, such as NodeJS and Python.

### Steps to reproduce the behavior
I created a new EKS cluster (separate to the one I was experiencing the issue with) by running `jx create cluster eks --cluster-name={{domain}} --skip-installation=true`

Then I ran `jx install --provider=eks --domain={{domain}} --default-environment-prefix={{prefix}}`

I verified the install was up and running and then ran a `jx create quickstart` and selected the golang-http build pack, and after about 5 minutes into the build, the build failed with the following error:
```
process apparently never started in /home/jenkins/go/src/github.com/{{redacted org}}/{{redacted repo}}@tmp/durable-84b1ccab

(running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)

script returned exit code -2
```

### Expected behavior
The output of `jx create quickstart` for golang-http builds should build without failing.

### Actual behavior
Builds created from a `jx create quickstart` golang-http build pack are failing.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.721
jenkins x platform 2.0.1125
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.14.1
helm client        Client: v2.14.1+g5270352
git                2.19.1
Operating System   Mac OS X 10.14.6 build 18G95


verifying packages

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

Using the `jx create cluster eks --cluster-name={{domain}} --skip-installation=true` command

### Operating system / Environment

Operating System   Mac OS X 10.14.6 build 18G95

**Comment by bluebenno** [comment]
FYI: I have the same issue on a two node new(ish) EKS cluster built via eksctl and then jenkinsx installed. Python quickstart (via jx create quickstart) works, golang does not.  With the same error as above.

```jx version
NAME               VERSION
jx                 2.0.892
jenkins x platform 2.0.1490
Kubernetes cluster v1.14.6-eks-5047ed
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.2
Operating System   "Fedora release 28 (Twenty Eight)"
```

``` > git fetch --no-tags --progress -- https://github.com/bluebenno/<redacted>-golang-test.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision 5b97b40457c967b81a423edb16b4c5ebff328df9 (master)
Commit message: "Draft create"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5b97b40457c967b81a423edb16b4c5ebff328df9
[Pipeline] sh
process apparently never started in /home/jenkins/go/src/github.com/bluebenno/<redacted>-golang-test@tmp/durable-ac775672
(running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
[Pipeline] }```

**Comment by bluebenno** [comment]
with thanks to https://issues.jenkins-ci.org/browse/JENKINS-58791

In your (go)repo change all references of: /home/jenkin/<stuff> to /home/jenkins/agent/<stuff>

If I can figure out where this gets set I'll raise pull-request

**Comment by 85matthew** [comment]
Looks like it happens right here. I've never made a PR on the jx project but should be an easy one if you have. Ran into the same issue today testing jx out.

https://github.com/85matthew/jx/blob/8d336b0ce533ec37bf74db743f960f29d80bca5a/pkg/jenkinsfile/pipeline.go#L817

**Comment by 85matthew** [comment]
https://github.com/jenkins-x/jx/blob/8d336b0ce533ec37bf74db743f960f29d80bca5a/pkg/jenkinsfile/pipeline.go#L817

That's the link to the official repo.

**Comment by q131172019** [comment]
Since January 17, 2020, I have experienced same issue relating to buildpack of 'go' in stage 'build release' when running 'jx create quickstart' for go-http.

Stage: build release
  Step: Check out from version control (note: it was successful to run 'checkout scm')

  Step: Shell Scripts:
        process apparently never started in /home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701@tmp/durable-6e78e55b

        (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)

        script returned exit code -2

Jenkins installation type: Static Jenkins Server and Jenkinsfiles
Two installation tools - 'jx install' and 'jx boot'.
The clusters are all AWS EKS cluster built with Terraform AWS EKS module.

Installation method #1: jx install --provider=eks --gitops=false --no-tiller --vault=false

NAME               VERSION
jx                 2.0.1123
Kubernetes cluster v1.12.10-eks-aae39f
kubectl            v1.16.2
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G103

Installation method #2: jx boot (using file jx-requirements.yml under directory jenkins-x-boot-config)

NAME               VERSION
jx                 2.0.1186
jenkins x platform 2.0.1860
Kubernetes cluster v1.12.10-eks-aae39f
kubectl            v1.17.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G103


Debug issue:
1. Added -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true at JAVA_OPTS in jenkins deployment by typing command 'ke deployment/jenkins -n jx'. If the change does not take effect, please run command 'kubectl rollout restart deployments/jenkins -n jx'.

FROM:

value: '-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Djenkins.displayurl.provider=org.jenkinsci.plugins.blueoceandisplayurl.BlueOceanDisplayURLImpl '

TO:
value: '-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Djenkins.displayurl.provider=org.jenkinsci.plugins.blueoceandisplayurl.BlueOceanDisplayURLImpl '

2. Tried to run 'jx create quickstart' for go-http again and saw the following error in detail.

   sh: line 1: cd: /home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701/charts/golang-http-jxboot-2020020701: No such file or directory

   sh: /home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701/charts/golang-http-jxboot-2020020701@tmp/durable-eb1ea78a/jenkins-log.txt: No such file or directory

   sh: /home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701/charts/golang-http-jxboot-2020020701@tmp/durable-eb1ea78a/jenkins-result.txt.tmp: No such file or directory

   mv: cannot stat ‘/home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701/charts/golang-http-jxboot-2020020701@tmp/durable-eb1ea78a/jenkins-result.txt.tmp’: No such file or directory

  process apparently never started in /home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701/charts/golang-http-jxboot-2020020701@tmp/durable-eb1ea78a

  script returned exit code -2

3. Checked the file Jenkinsfile under Repo 'golang-http-jxboot-2020020701'

stage('Build Release') {
      when {
        branch 'master'
      }
      steps {
        container('go') {
          dir('/home/jenkins/go/src/github.com/q13117god/golang-http-jxboot-2020020701') {
            checkout scm

            // ensure we're not on a detached head
            sh "git checkout master"

4. Login to container 'go' in pod 'go-xxxx' to see where the repo golang-http-jxboot-2020020701 is.  There was blank in /home/jenkins/go/src, /home/jenkins/go/bin, /home/jenkins/go/pkg. There was repo in /home/jenkins/agent/workspace.

5. Checked buildpacks of go at the file .jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-classic/packs/go/pipeline.yaml and saw the key words.

REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME

6. Because 'jx create quickstart' for spring, php, nodeJS, python were successfully, I compared go/pipeline.yaml with javascript/pipeline.yaml, python/pipeline.yaml and maven/pipeline.yaml. Only go/pipeline.yaml contained REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.

7. Checked key word "REPLACE_ME_GIT_PROVIDER" and got the result "https://github.com/jenkins-x/jx/blob/e76d56b88bc08acf06b40c4d139e6db9ce716a0b/pkg/tekton/syntax/pipeline.go#L1167".

8. Checked the file pkg/jenkinsfile/pipeline.go

9. Finally saw the issue https://github.com/jenkins-x/jx/issues/5470 and  https://issues.jenkins-ci.org/browse/JENKINS-58791

10. Make the change for parameter 'dir:' in two files .jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-classic/packs/go/pipeline.yaml and .jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/go/pipeline.yaml

FROM:
  /home/jenkins

TO:
  /home/jenkins/agent

11. Successfully run 'jx create quickstart' for go-http to go through pipelines (Dev->Staging-Production).

Also, I used 'jx boot' to select Jenkins installation type:  Serverless Jenkins X Pipelines (Tekton + Prow). I did not experience same issue relating to buildpack of 'go' in stage 'build release' when running 'jx create quickstart' for go-http.
