### ISSUE TITLE
provide an exclusive lock step in a pipeline to avoid concurrent builds

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#5471]
### Summary 

When performing a release via GitOps we don't want to allow concurrent builds; as odd things can happen due to concurrency.  We can happily process PRs concurrently - but often for releases we want to mark those as running one at a time for a given repository + branch.

Eventually this may end up being a core part of tekton: https://github.com/tektoncd/pipeline/issues/1305

Until then a workaround could be to write a leadership election step of sorts - a step which blocks until it grabs a lock for being the 1 allowed pipeline for a given string (the git URL + branch)

### Steps to reproduce the behavior

Run 2 release pipelines on a staging/production environment and issues can occur

### Expected behavior

We force a 2nd pipeline on a given environment release to block until the first one complets

### Strawman design

We already expose the pod logs into each pod via `/etc/podinfo` via the downward API. Though we should maybe be more explicit and expose the current `PipelineRun` name into pipeline via the `$PIPELINE_RUN` environment variable.

We could create a new step - say - `jx step pipeline lock` which does this:

* grab the current pod's`PipelineRun` name and the repository owner/repo/branch
* find the `SourceRepository` for the owner/repo (we could expose this as a label/env var too to simplify the code)
* use an annotation key of `jenkins.io./lock/owner/repo/branch` on the `SourceRepository`
* lookup the annotation for the key. 
* if empty, set the value to the `PipelineRun` name
* if the update works and the value of the updated `PipelineRun` annotation has the current `PipelineRun` name, the current pod is the leader and the step can terminate.
* if not the value of the key is the `leaderPipelineRun` resource to watch. The step then watches the `leaderPipelineRun` until its complete/deleted _and_ all pods which have the label `tekton.dev/pipelineRun=leaderPipelineRun` complete/fail
* once there is no running `leaderPipelineRun` or pods then its time to try become the leader again, so try update the `SourceRepository` again
* repeat until some timeout and then fail?

**Comment by msvticket** [comment]
After getting the urgent issue (#5281) fixed with my PR I continued to think in a similar direction. The principal difference is that your solution seems to put the lock on the whole pipeline run while I was thinking of having the lock on a particular step (so rather TaskRun). The reasoning beaning that there might be time consuming steps that can be concurrent. Both varieties would be useful though.

**Comment by msvticket** [comment]
There are also cases where the order of PipelineRuns are of importance so a lock with FIFO behaviour would be preferable. Maybe store a queue of runs in the SourceRepository? But then you need to take into consideration that the pod first in the queue might die while waiting.

**Comment by keskad** [comment]
That would be nice to actually limit concurrency for specific jobs or even stages to avoid overlapping, especially, when external services are used.

**Comment by ankitm123** [comment]
I think we want to solve it upstream in tekton, instead of jx (There's a TEP for that: https://github.com/tektoncd/experimental/issues/699). We have something basic in lighthouse using max_concurrency I believe (https://github.com/jenkins-x/lighthouse/blob/main/docs/trigger/github-com-jenkins-x-lighthouse-pkg-config-job.md)
