### ISSUE TITLE
Setup WhiteSource scanning

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5714]
### Summary 

Setup WhiteSource scanning as requested by Product Security.

**Comment by ccojocar** [comment]
cc @madchap

**Comment by hferentschik** [comment]
> @hferentschik Do you have any details how to create an app extension?

That still needs to be written :-( That said, this might not yet work until we have #4660 in place. The build pipeline needs to be able to see any pipeline modifications by the meta pipeline.

**Comment by abayer** [comment]
Should still be possible, if a bit more awkward than ideally, without #4660 - the step added could be fetching a shell script that does all the stuff in the configuration/running of the scanner, including downloading things.

**Comment by hferentschik** [comment]
Well, you either need to run the scanner in the meta pipeline or you need to somehow commit and pull out the changes you need in the build pipeline. IMO not worth the effort, since it is a poor workaround which one would need to change once more when we have meta pipeline "proper".

If I'd were you I'd spend my time trying to get the Tekton changes which will enable this feature ready. IMO that would give us ways more benefits and unlock us eventually on many things.
