### ISSUE TITLE
jx promote behaviour thoughts

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#5781]
### Summary 
Playing a lot with `jx promote` recently, I want to surface some behaviours that might not be optimal.

### Observations
- When you run `jx promote`manually it's adding a Promote stage to the latest master build of the app you want to promote. Which does not really make sense if you are actually trying to promote another version of the app that is not the latest.
- When trying to promote the same version that is already in the env, we don't create a PR which is fine but we add the Promote stage to the master build of the app and it keeps running forever.

### Proposals
- Should `jx promote` not add anything to the app master build and just let the environment builds do the promotion ?

**Comment by romainverduci** [comment]
cc @abayer

**Comment by abayer** [comment]
Working on #5755, I realized that how we handle promotion in `PipelineActivity` with Tekton (rather than static masters) is a bit unformed. `controller_workflow` handles a lot of the `PipelineActivity` interaction for promotion with static masters, but that controller isn't used with Tekton. The result is that things like #5755 itself (manual promotion resulted in the relevant `PipelineActivity` never "completing") and the `Update` step always having a `0s` duration, and other weirdness like:
```
jenkins-x/jx/PR-5780 #3                                                                          Running Version: 0.0.1
  Release                                                                          3m2s     1m0s Succeeded
  Promote: production                                                              2m2s    1m28s Succeeded
    PullRequest                                                                    2m2s    1m28s Succeeded  PullRequest: https://github.com/jenkins-x-bot-test/environment-pr-5780-3-tekton-gkebdd-production/pull/1 Merge SHA: 6f8caea41db4826fff6d10d5e0422d310c14dddc
    Update                                                                          34s       0s Succeeded
```
(that's coming from a BDD test execution - the manual `jx promote` to production run outside of a pipeline is seeing it's actually still run within a pipeline, albeit the BDD test pipeline, and creating a new `PipelineActivity` using the BDD test pipeline's information - I believe that running `jx promote` outside of any pipeline will result in the behavior @romainverduci is seeing, where a `Promote` stage is added to the latest master build)

I don't know what we _should_ be doing instead, I just know that what we _are_ doing w.r.t. promotion, particularly manual promotion, and `PipelineActivity` without `controller_workflow` enabled is not quite right.
