### ISSUE TITLE
jx commands should detect git/credentials files created by tekton

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6031]
the tekton approach to secrets generates a `git/credentials` file from the available secrets on startup of a pipeline: https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#git-basic-auth

it would be great to have `jx` respect the same git credentials file by default for user/pwd values. Then we can avoid explicitly looking at the `Secrets` and instead just reuse the `ServiceAccount => Secret` bindings we reuse in tekton pipelines.

So lets also detect `git/credentials` files and enrich whatever is found at `~/.jx/gitAuth.yaml` (which will be empty inside pipelines)

**Comment by ccojocar** [comment]
This has more implications:
- This Tekton's credentials are set by us in boot, see https://github.com/jenkins-x/jenkins-x-boot-config/blob/7d088ae938eae89fb976d763e1fe47d65038a8f6/env/tekton/values.tmpl.yaml#L14
- They are the same like the pipeline user/token 
- Also they are duplicated in a lot of places see #5514 
- We are trying to improve this and only use the secrets to lookup this credentials when vault is not enabled, otherwise they should be fetched by jx from vault, which will allow users to easily rotated them in vault

It's true that we can read them from the git/credentials file when `jx` is executed in the tekton created Pod, but hat only works with Pods created by Tekton. In case, jx is executed in other pods (e.g. job, build controller etc), this credentials file is not available. It would be rather cleaner to have a uniform approach which fetches them directly from vault when is enabled.
