### ISSUE TITLE
Communicate and collect feedback for deprecation of jx commands

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#6120]
### Summary 

We plan to mark soon some commands as deprecated but before doing that we would like to communicate this to the community to collect more feedback.

**Comment by MarckK** [comment]
Hi @ccojocar, thank you for opening this issue. 

Let's list here the commands that are being considered for deprecation, to elicit discussion from the community and get feedback on the mooted changes.

**Comment by ccojocar** [comment]
This is the [document](https://docs.google.com/document/d/1PLGFoGrSFzGgsFJKUyrjWb976Mkcmp_7ww5OmCTYld8/edit?usp=sharing) with the list of commands considered for deprecation.

**Comment by MarckK** [comment]
Copying the [Jenkins X Commands Deprecation document](https://docs.google.com/document/d/1PLGFoGrSFzGgsFJKUyrjWb976Mkcmp_7ww5OmCTYld8/edit) here:

Command | Replacement | Removal Date | Info | Reason of removal
-- | -- | -- | -- | --
install | boot | 01-02-2020 | dld install command | Replaced by boot command
init | boot | 01-02-2020 | Old pre install command used to initialize the ingress controller | Replaced by boot command
upgrade platform | upgrade boot | 01-02-2020 | Old upgrade platform command | Replaced by upgrade boot command
upgrade ingress | boot and step expose | 01-02-2020 | Use the expose controller to recreate all the ingress resources in a namespace (e.g. dev). This are now statically created in boot | Replaced by boot command
create terraform | boot | 01-02-2020 | Creates a Jenkins X Terraform plan for GKE and install Jenkins X using the install command | Replaced by boot command
upgrade cluster | boot | 01-02-2020 | Upgrades the Jenkins X Cluster tools | Replaced by boot command and the version stream.
update cluster | gcloud container cluster upgrade | 01-02-2020 | Upgrades an existing GKE cluster | Not in our core functionality and doesn’t bring much value on top of gcloud
create cluster minikube |   | 01-02-2020 | Create minikube cluster | Boot command expects an existing cluster. This is not in our core functionality.
create cluster minishift |   | 01-02-2020 | Create minishift cluster | Boot command expects an existing cluster. This is not in our core functionality
create cluster openshift |   | 01-02-2020 | Create openshift cluster | Boot command expects an existing cluster. This is not in our core functionality
create cluster icp (IBM Cloud Private) |   | 01-02-2020 | Create icp cluster | Boot command expects an existing cluster. This is not in our core functionality
create cluster aws |   | 01-02-2020 | Create kops managed aws cluster, replaced by eks | Boot command expects an existing cluster. This is not in our core functionality
create cluster oke |   | 01-02-2020 | Create oracle cloud cluster | Boot command expects an existing cluster. This is not in our core functionality
create cluster kubernetes |   | 01-02-2020 | Creates vanila kubernetes cluster using kubeadm | Boot command expects an existing cluster. This is not in our core functionality
get clusters | gcloud container clusters list | 01-02-2020 | List the existing GKE clusters | Doesn’t bring any value on top of gcloud and is not in our core functionality
upgrade extensions | upgrade apps | 01-02-2020 | Upgrades the Jenkins X extensions available to this Jenkins X install if there are new versions available | Replaced by apps as extension model
step create jenkins |   | 01-02-2020 | Creates the Jenkins config.xml file from a number of ConfigMaps for Pod Templates | This doesn’t seem to be anymore in the current scope of the project.
console | ui | 01-03-2020 | Opens the Jenkins console in a browser.This should be only deprecated but not removed as long as the classic Jenkins is supported. | Replaced by Jenkins X UI
controller workflow |   | 01-02-2020 | Workflow controller | It doesn’t seem to be used anymore.
get workflows |   | 01-02-2020 | Get Workflows | Related to workflow controller which doesn’t seem to be used anymore
delete aws |   | 01-02-2020 | Deletes given AWS VPC and resources associated with it (like elastic load balancers or subnets) | Boot command expects an existing cluster. This is not in our core functionality
get aws |   | 01-02-2020 | Display the AWS information for the current user | This is not in the core functionality
get eks | eksctl get clusters | 01-02-2020 | List EKS clusters | Doesn’t have any value on top of eksctl
delete eks | eksctl delete cluster | 01-02-2020 | Delete EKS clusters | Doesn’t have any value on top of eksctl
get post |   | 01-02-2020 | Gets the jobs which are triggered after a Preview is created. | It seems to be related to extensions which seems to be replaced by apps
create post |   | 01-02-2020 | Create a job which is triggered after a Preview is created | It seems to be related to extensions which seems to be replaced by apps
delete post |   | 01-02-2020 | Deletes a job which is triggered after a Preview is created | It seems to be related to extensions which seems to be replaced by apps
step post |   | 01-02-2020 | step post build: Performs post build actions in a pipeline  step post instal: l Runs any post install actions  step post run: Runs any post build actions | It seems to be related to extensions which seems to be replaced by apps
step pre |   | 01-02-2020 | step pre build Performs actions before a build happens in a pipeline  step pre extend Adds any extensions configured for this pipeline | It seems to be related to extensions which seems to be replaced by apps
step credential |   | 01-02-2020 | Returns a credential from a Secret for easy scripting in pipeline steps. | This is replaced by Tekton mounted sects either in volumes or env variables
step git credentials |   | 01-04-2020 | Creates the Git credentials file for the current pipeline.This needs to be carefully removed from all pipeline files. The git credentials file is already created by the Tekton’s git-init container. | This is replaced by Tekton git init which created the git credentials file in the right place.
create step |   | 01-02-2020 | Creates a step in the Jenkins X PipelineThis should be renamed to edit pipeline instead of being removed. | Very little benefit in this command. Confusing in its name. Not at all clear what it does. Currently out of date.
step split monorepo |   | 01-02-2020 | Mirrors the code from a monorepo into separate microservice style Git repositories so its easier to do finer grained releases. | Not essential to Jenkins-X. Unclear on how to use this. Maintenance burden.
edit deploy |   | 01-02-2020 | Edits the deploy kind to use for your project or team | Does this even still make sense?It seems to be editing the deploy kind: kubernetes vs knative
create archetype | create quickstart | 01-02-2020 | Create a new app from a Maven Archetype and import the generated code into Git and Jenkins for CI/CDMerge functionality in create quickstart. | Replaced by create quickstart
create micro | create quickstart | 01-02-2020 | Creates a new micro application and then optionally setups CI/CD pipelines and GitOps promotion.Merge functionality in create quickstart. | Replaced by create quickstart
create spring | create quickstart | 01-02-2020 | Creates a new Spring Boot application and then optionally setups CI/CD pipelines and GitOps promotion.Merge functionality in create quickstart. | Replaced by create quickstart
create lile | create quickstart | 01-02-2020 | Creates a new Lile application and then optionally setups CI/CD pipelines and GitOps promotion.Merge functionality in create quickstart. | Replaced by create quickstart
create camel | create quickstart | 01-02-2020 | Create a new Camel based application and import the generated code into Git and Jenkins for CI/CDMerge functionality in create quickstart. | Replaced by create quickstart
create jhipster | create quickstart | 01-02-2020 | Create a new JHipster based application and import the generated code into Git and Jenkins for CIMerge functionality in create quickstart. | Replaced by create quickstart
create addon knative-build | Tekton | 01-02-2020 | Create knative-build addon | Knative-build is deprecated and replaced by Tekton
delete addon knative-build | Tekton | 01-02-2020 | Delete knative-build addon | Knative-build is deprecated and replaced by Tekton
edit extensionsrepository | Replaced by apps | 01-02-2020 | Sets Extensions Repository in use | It seems to be replaced by apps
delete extension | Replaced by apps | 01-02-2020 | Deletes one or more Extensions from Jenkins X | It seems to be replaced by apps
create etc-host |   | 01-02-2020 | Creates /etc/hosts entries for all current exposed services | No sure where this is useful since kubernetes comes with service discovery and every service can be reached into the cluster
step nexus drop |   | 01-02-2020 | This pipeline step command drops a Staging Nexus Repository | Not sure for what is this useful?
step nexus release |   | 01-02-2020 | This pipeline step command releases a Nexus staging repository | No sure for what is this useful?

**Comment by bnerDY** [comment]
May i know any replacement of creating project from archetype? i cannot find the ability of using custom archetype form quickstart. any suggestion would be very helpful.

**Comment by ccojocar** [comment]
The plan is to migrate these commands to quickstarts before removing them.
