### ISSUE TITLE
Boot fails with Helm 3

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6124]
### Summary 

When using Helm 3, the `jx boot` command fails. It should be specified as a requirement that only Helm 3 is supported and the error message should be clearer, at least until `jx` is adapted to use it.

### Steps to reproduce the behavior

Install Helm 3

```bash
jx boot
```

The output:

```
...
error: initializing helm with config: {jx true false true false  }: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
```

### Expected behavior

`jx boot` works

### Actual behavior

`jx boot` fails

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.979
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Any

### Operating system / Environment

MacOS

**Comment by cloudtagger** [comment]
I will second that

**Comment by daniyalj** [comment]
Running into the same thing. Any temporary workarounds for this other than downgrading?

**Comment by RafalKorepta** [comment]
@daniyalj `brew install helm@2`

**Comment by RafalKorepta** [comment]
The issues with a helm that I saw:

- Using the JX_HELM3 doesn't work. Even if I create a symbolic link from helm to helm3.
- The init command does not exist with helm3
- The template command does not have --name parameter, because it was changed to mandatory field
- The upgrade command has a problem with existing resources. It complains about `existing resource conflict: kind: XXX, namespace: XXX, name: XXX`

If jx need to support version 2 and 3 of the helm, there could be an option to create 2 versions of [helm_cli.go](https://github.com/jenkins-x/jx/blob/master/pkg/helm/helm_cli.go). Maybe extending [Environment with helmVersion](https://github.com/jenkins-x/jx/blob/master/pkg/apis/jenkins.io/v1/types_environment.go#L203-L204) could help with defining the helm version or users could leverage [helmMajorVersion in jx-requirement.yaml](https://github.com/jenkins-x/jx/commit/5cb052e8166529be008273db1d7eb549d0a6200a#diff-188932e694490f76bfe175ad0aa84fe7R212) to adjust jx behavior.

**Comment by missing-cn** [comment]
> Running into the same thing. Any temporary workarounds for this other than downgrading?

me too.

**Comment by deanesmith** [comment]
This is going to be investigated.  We're not ready to support Helm 3 so better handling is needed.  Described  here - https://github.com/jenkins-x/jx/issues/6181

**Comment by polothy** [comment]
Would be great to have Helm3 support sooner rather than later.  It seems like it would solve some big problems with Helm2 due to tiller and JX's home grown tillerless option, which has problems with custom CRDs and deploying to multiple namespaces.

**Comment by deanesmith** [comment]
Hi @polothy, Agreed.

**Comment by jp-gorman** [comment]
More than 2 months from issue opening and all docs still show helm 3 support despite known issue and jx install and jx boot failing to work with helm 3. How about rip it from the docs as being supported and remove the --helm3 option until it is fully supported.

https://jenkins-x.io/docs/reference/components/helm3/

**Comment by deanesmith** [comment]
Hi @jp-gorman, Indeed ,you're correct!  The expectation that JX would have Helm 3 support at the time of GA is completely incorrect due to the amount of effort required.  I'll update that statement.   In the meantime, if you can attend the Jenkins X Community Office Hours on Thursday Jan 23rd, @rawlingsj will be discussing Helm3 a bit - https://jenkins-x.io/community/

**Comment by ankitm123** [comment]
I can work on this, if it is ok, helm3 support would be nice

**Comment by vfarcic** [comment]
@jstrachan ^^^

**Comment by RafalKorepta** [comment]
I found enhancements proposal for helm3: https://github.com/jenkins-x/enhancements/tree/master/proposals/2/docs

**Comment by deanesmith** [comment]
Hi @ankitm123, please review the aforementioned proposal document.  I believe this is WIP right now and your feedback in comments could prove useful.  There may be tasks where your development contributions could become quite valuable.

**Comment by yelhouti** [comment]
@ankitm123 @deanesmith although I found the proposal really great, I think that for now we should just be able to skip the helm init when using helm 3. This clearly a blocking issue for a lot of folks.

**Comment by yelhouti** [comment]
These are the workarounds:
- first disable verify helm since it run helm init that doesn't exist on helm3 (add `- --disable-verify-helm=true` in step verify preinstall in jenkins-x.yml
- configure jx to use helm3: `export JX_HELM3=true`
- disable velero since not available yet for baremetal (kubernetes) by deleting velero stepS in jenkins-x.yml
- I also had to remove everything already installed in my cluster from jenkins-x (ingress, certificates issuers, external-dns...), hope this helps someone

**Comment by ankitm123** [comment]
AFAIK You can work off this PR: https://github.com/jenkins-x/jx/pull/6664. Build it locally, and use the resulting binary, if you want to use helm3.

**Comment by jstrachan** [comment]
here's the way you can use helm 3 with boot:
https://jenkins-x.io/docs/labs/boot/

**Comment by jx-bot-demo** [comment]
The link above about how to use helm 3 with boot goes to a non-existent page now.
