### ISSUE TITLE
How to change registry

### ISSUE THREAD

**Issue by masonCaminer** [jenkins-x/jx#6235]
### Summary 
I use jx in China, I use jx install - provider = kubernetes - default - environment - the prefix = treelab - cn - docker-registry=405945335668.dkr.ecr.cn-northwest-1.amazonaws.com.cn
Installing jx in the cluster, which I thought would replace gcr.io or k8s.gcr.io, didn't work.
### Steps to reproduce the behavior
Changing myvalues.yaml only replaces parts.
### Expected behavior
Use the registry I specified，405945335668.dkr.ecr.cn-northwest-1.amazonaws.com.cn/jenkinsxio/exposecontroller:2.3.111
and i want to change the https://storage.googleapis.com/chartmuseum.jenkins-x.io
### Actual behavior
Failed to pull image "gcr.io/jenkinsxio/exposecontroller:2.3.111"

```
COPY OUTPUT HERE
```
NAME               VERSION
jx                 2.0.1011
jenkins x platform 2.0.1673
Kubernetes cluster v1.13.10
kubectl            v1.16.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

Static Jenkins Server and Jenkinsfiles

**Comment by hferentschik** [comment]
I think your issue is that you are not able to pull the Jenkins X images itself, like e.g. the exposecontroller. 

The registry you specify is the registry to host the images you are building from your applications. It is not replacing where the Jenkins X images itself are coming from.

Not sure how far you get with installing Jenkins X w/o being able to access the Google registries.
