### ISSUE TITLE
Creation of 'preview' from PR does NOT pull in the master branch

### ISSUE THREAD

**Issue by igwejk** [jenkins-x/jx#6287]
### Summary

To avoid having a _`preview`_ that is potentially too different from the main branch (e.g. `master`),  the `preview` creation process should `pull` the main branch into a PR (or `rebase` the PR on top of the project's main branch) prior to the creation a _`preview`_  of the PR.

### Steps to reproduce the behaviour

Execute

```bash
jx create pullrequest ...
```

### Expected behaviour

The preview creation task should execute along the following lines
```bash
git checkout <pr-branch>
git pull --rebase origin/master
<create-preview-exec> . # creates preview from current working tree
```

### Actual behaviour

The preview creation appears to execute along the following lines
```bash
git checkout <pr-branch> # this may have diverged too far from the main branch 😕
<create-preview-exec> . # creates preview from current working tree
```

### Jx version

The output of `jx version` is:

```
2.0.1045
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Irrelevant

### Operating system / Environment

Irrelevant

**Comment by igwejk** [comment]
/cc @vfarcic 

We discussed this in our the training.

**Comment by bitfactory-henno-schooljan** [comment]
I'm wondering how you would handle conflicts in this case, seeing that this thing also runs from the pr-build pipeline.

**Comment by igwejk** [comment]
Conflicts shouldn't be handled at all. After all there's no value in previewing a change that cannot make it into the main branch.

So `jx create pullrequest ...` should fail fast when a merge conflict is detected.

**Comment by hferentschik** [comment]
I am wondering whether we would not do too much magic in this case. IMO it is the responsibility of the pull request creator to decide the branch point of the pull request. If you want to be closer to master you should rebase and push an update to the pull request.

I also think it is a valid case to create a pull request which in itself is perfectly fine which however does not merge directly to master due to not being fully up to date. I still argue that you should get a preview environment in this case. 

If anything, I could imagine this as a option in some form.

**Comment by igwejk** [comment]
Any additional feedback on the progress of this issue?

/remove-lifecycle stale
