### ISSUE TITLE
Race condition when a PR and Release builds are triggered too closely, resulting in conflicts calculating the pipeline / pipelinerun, etc names

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#6320]
Follow up for https://github.com/jenkins-x/jx/issues/6240

Way to reproduce:

- Open a PR
- Merge the PR right after it's been created
- It will trigger a run of the PR build and the master build and eventually cause conflicts in naming for pipeline, pipelinerun or other k8s resource

Example of error:
```
PipelineActivity for cb-kubecd-environment-pr-1050-5-bdd-frontend-dev-master-1
Applying changes 
upserted PipelineResource cb-kubecd-environment-pr-1050-5 for the git repository https://github.com/cb-kubecd/environment-pr-1050-5-bdd-frontend-dev.git
upserted Task cb-kubecd-environment-pr-1050-5-release-1
upserted Pipeline cb-kubecd-environment-pr-1050-5-1
error: failed to apply Tekton CRDs: failed to create the pipelineRun in namespace jx: Failed to create PipelineRun cb-kubecd-environment-pr-1050-5-1: pipelineruns.tekton.dev "cb-kubecd-environment-pr-1050-5-1" already exists
Pipeline failed on stage 'meta-pipeline' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

**Comment by abayer** [comment]
So the problem is that we try to check if a pipeline name is unique by getting the `PipelineResource` with that name, and if it exists, we add a random suffix. But with a tiny enough gap between the first PR build and first release build of a repo being kicked off (like, 3-5 seconds - not a common case), we don't actually retrieve the `PipelineResource` and just use the same name twice. And then things go bad.
