### ISSUE TITLE
jx delete application fails on Failed to get ProwJobs

### ISSUE THREAD

**Issue by iftachsc** [jenkins-x/jx#6381]
### Summary 
when trying to delete application using jx delete application it fails on
error: deleting application: Failed to get ProwJobs

digging into jx source code it seems it is looking for prox configmap named config in jx namespace but this doesnt exists i guess because i am using classical jenkins and not prow
### Steps to reproduce the behavior
import application on classic jenkins webhook jx
### Expected behavior
it should delete the app
### Actual behavior
getting error: deleting application: Failed to get ProwJobs
### Jx version

The output of `jx version` is:

```
jx                 2.0.1082
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.13.11-dispatcher
helm client        Client: v2.14.3+g0e7f3b6
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ x] Classic Jenkins

**Comment by mrageh** [comment]
Hey, @iftachsc

We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/
If you'd like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we'd be happy to discuss further. 
If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
