### ISSUE TITLE
Review command deprecation proposal and generate issues accordingly

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6439]
### Summary 
In an effort to ensure deprecated commands are properly removed, the current list should be reviewed and issues generated for code removal, renaming, and any other enhancements related to deprecated commands.

As part of the review, any command deprecation date that is unreasonable should be altered accordingly with proper justification.

The full listing of commands proposed for deprecation is located here:
https://github.com/jenkins-x/jx/blob/8a4dac4e0bc5882e91d2d66d371a16c6f97485ee/pkg/cmd/deprecation/deprecated.go

**Comment by ccojocar** [comment]
In addition to define the tasks required to clean up the deprecated commands from source code, we should also define a task to close all related GitHub issues (e.g. there are a lot of minikube/minishift related issues which can be mostly closed, and so on).

**Comment by tdcox** [comment]
We have some dependencies on post preview jobs in the OWASP-ZAP addon, so we need to make sure we retain that functionality until an alternative solution and plugin are in place.

**Comment by ccojocar** [comment]
See the discussions on Slack on this tread in `jenkins-x-user` channel: https://kubernetes.slack.com/archives/C9MBGQJRH/p1579799269040900

The following commands will need to be delayed:
- `install` ( the `--ng` options should be removed as soon as possible to avoid confusion with boot)
- `init`
- `upgrade platfrom`
- `create spring` (should be renamed instead of removing it)
- `post` (still used by @tdcox for OWASP-ZAP addon - see comment above)
- `step credentials` (heavily used in the build-packs and many pipelines - but it is not recommended as a secure way to handle secrets in a Tekton based Jenkins X installation)

**Comment by deanesmith** [comment]
https://github.com/jenkins-x/jx/issues/5310#issuecomment-578938266
