### ISSUE TITLE
GitOps approvals blocked under Boot install

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6457]
### Summary 
I attempted to add the SSO app with `jx add app jx-app-sso` and this uses a PR on Dev to install a chart. The promotion build succeeds but the PR is never merged. If I try to `/lgtm` the PR, I see the `This PR is not approved' message and a request to add additional approvers.

The dev environment for a cluster created using boot is instantiated with an OWNERS file that is populated with the accounts of the Jenkins-X team, only.

Not sure if this is an extension of the Github Case Sensitivity Saga or a failure to authorise users on the Dev environment. I am seeing webhooks being logged.

If I force the merge, the deployment kicks off automatically and boot runs, although it fails subsequently due to what appears to be another bug.

There is no OWNERS file in the Dev environment of legacy clusters, so this looks like a config problem.

### Jx version

The output of `jx version` is:

```
AME               VERSION
jx                 2.0.1103
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

**Comment by tdcox** [comment]
@abayer

**Comment by abayer** [comment]
Same as #5035 - you can cheat around by adding the `updatebot` label, I believe, but yeah, we need to fix this.

**Comment by abayer** [comment]
I'm trying to figure out if there's a way to do this that won't have merge conflicts whenever the upstream `OWNERS` changes. Wondering whether we can do something with `OWNERS_ALIASES` - having an alias group as an approver/reviewer in `OWNERS`, and no `OWNERS_ALIASES` file upstream, then populate it during boot...or the other way around, with upstream `OWNERS_ALIASES` populated with groups named `upstream-approvers` and `upstream-reviewers`, and upstream `OWNERS` always just has the aliases in its `approvers` and `reviewers`, so that it never changes going forward. Then during boot, we would overwrite `OWNERS` with the appropriate user.

Of course, that leaves the question of who the appropriate user would be...

**Comment by abayer** [comment]
Oh, wait, I think we exclude `OWNERS` from boot upgrade anyway!

**Comment by abayer** [comment]
Ah-ha, quick workaround - call `jx add app jx-app-sso --auto-merge` and the PR that gets created should merge, well, automatically.
