### ISSUE TITLE
improve initial boot UX and allow folks to customise jx requirements before booting

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#6472]
The UX for jx boot could do with being a little more intuitive.  

My flow:
```
jx create cluster gke --skip-installation
jx boot # this clones locally the latest version of the jx boot config
```
The boot wizard it bombs out because the jx requirements default to private repos and the org I use is public.
I now need to go to the CLI docs on the website and figure out how to use my public github org (this isn't that easy either).  I then change into the locally cloned  boot config repo, update the desired fields and re-run `jx boot`.

It feels like we should be able to have a step / command that helps build up the initial requirements.  There's already a flag for boot to specify an existing `jx-requirements.yml` but even then it's not obvious where to get an initial version of this so that folks can then customise.

Some suggestions on this thread in slack on how to get the initial default requirements and begin to customise before initially running boot - https://kubernetes.slack.com/archives/C9MBGQJRH/p1578505392064500

-  add a `jx boot --init` flag that clones the boot config repo locally and nothing else
-  add a `jx create requirements` or `jx setup` command, this starts a wizard to help generate a jx-requirements.yml

/area boot
/kind improvement

I don't use a paid github org which means I need to change the initial jx requirements to use public git repo settings.

**Comment by MarckK** [comment]
Yes please!

I've been working on a walkthrough tutorial for starting with Jenkins X OSS for the first time. And because of this issue my workaround was to have users:

-  create a cluster 

- then clone the jx boot config repo

- edit `jx-requirements.yml` to set `environmentGitPublic` to true 

- then run `jx boot`

<img width="1680" alt="Screenshot 2020-01-10 at 17 13 37" src="https://user-images.githubusercontent.com/15032115/72172664-9dfae800-33cd-11ea-9a9c-a8eda0af1503.png">

The suggestions you've made to improve the UX are very good improvements to have.

**Comment by jstrachan** [comment]
FWIW we made those improvements in the `jxl boot` command: we [create the git repository](https://jenkins-x.io/docs/labs/boot/getting-started/repository/) first then let folks [configure git](https://jenkins-x.io/docs/labs/boot/getting-started/config/) + [modify secrets](https://jenkins-x.io/docs/labs/boot/getting-started/secrets/) before [running boot](https://jenkins-x.io/docs/labs/boot/getting-started/run/) on the git repo
