### ISSUE TITLE
bug: jx ui not working with latest cli and boot

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6515]
### Summary 

When running `jx add app jx-app-ui` with the latest cli and boot-config,
the jx-ui `Pod` is permanently crashing with the following error:

```
error: error getting Requirements from TeamSettings to determine if in GitHub app mode: validation failures in requirements from team settings:
velero: Additional property schedule is not allowed
velero: Additional property ttl is not allowed
cluster: Additional property devEnvApprovers is not allowed
```

looks like incompatibility issues to me.

### Steps to reproduce the behavior

Install latest `jx` CLI and boot-config, then run `jx add app jx-app-ui`,
wait till it promotes and run `kubectl get pods` to see the crashing pod,
now run `kubectl logs <pod-name> -c <backend-container-name>`

### Expected behavior

Pod starts

### Actual behavior

Pod stuck in `CrashLoopBackOff` 

### Jx version

The output of `jx version` is:

```
jx                 2.0.1120
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

```
gcloud container clusters create <name> --machine-type n1-standard-2 --scopes=storage-full
```

### Operating system / Environment

Operating System   Mac OS X 10.15.2 build 19C57

**Comment by abayer** [comment]
cc @romainverduci @jstrachan - I think we just need a new UI release with a current jx binary in it?

**Comment by romainverduci** [comment]
This should be fixed in the coming days :)

**Comment by TonyNoble** [comment]
Is there an ETA on this fix?  (and how do we update when it arrives?)

**Comment by romainverduci** [comment]
@TonyNoble a new release of jx-app-ui containing the fix should be published with the new release of Cloudbees Jenkins X Distribution by the end of the week.
In order to install it, you will just have to run `jx add app jx-app-ui --version the-next-version` as per the documentation here: https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/user-interface/install

Please take into consideration that this has been mainly tested against Cloudbees Jenkins X Distribution so depending on your jx configuration you might have unexpected behaviours.

**Comment by tomfrenken** [comment]
Fixed with the latest release, therefore I'll close this 👍
