### ISSUE TITLE
sso-operator service annotations for cert manager issuer are invalid for cert manager 0.11

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6536]
We moved to cert-manager 0.11 in boot clusters recently, because LetsEncrypt doesn't work with older cert-managers any more. A problem we're seeing as a result of this is that the annotation used by sso-operator, `certmanager.k8s.io/issuer`, is not valid with cert-manager 0.11 - it needs to be `cert-manager.io/issuer`. While there are configuration workarounds that can be done to get past this, the fact is that `jx-app-sso` out of the box with boot just doesn't do what it's supposed to do.

I'm not 100% sure what to do here due to concerns about legacy `jx install` clusters - I think that the cert manager they'd install, 0.9, won't work anyway, so changing the annotation won't break them any further than they are already?

I'm marking this as an `estimate/M` because while at first glance this looks like it may be trivial, I have a feeling I'm underestimating it.

**Comment by ccojocar** [comment]
This needs to go to https://github.com/jenkins-x/sso-operator.

**Comment by ccojocar** [comment]
The annotations have to be adapted in https://github.com/jenkins-x/sso-operator/blob/260c88f57783ce424473df4581f218ead5b5d611/pkg/proxy/proxy.go#L114.

**Comment by abayer** [comment]
@ccojocar @rawlingsj @jstrachan - so do we believe that switching to the current annotation at https://github.com/jenkins-x/sso-operator/blob/260c88f57783ce424473df4581f218ead5b5d611/pkg/proxy/proxy.go#L47 will fix things and not break `jx install` cases any more than they're already broken?

**Comment by ccojocar** [comment]
I think we need to keep both and detect dynamically the cert-manager version to avoid breaking the install.

**Comment by ccojocar** [comment]
If I am not mistake the install uses `0.6.x`.

**Comment by abayer** [comment]
Ok, that makes sense.

**Comment by tdcox** [comment]
All versions of cert-manager prior to 0.8.0 were blocked by LetsEncrypt at the end of October.

**Comment by tdcox** [comment]
If I manually edit the Ingress for an application to set the correct issuer, I see some very strange behaviour...

If I visit the https URL for the service, I get a security error in the browser as the default K8S dummy TLS cert is issued. This is repeatable.

If I then visit one of the https services exposed by Jenkins-X, such as Nexus, I get the correct LetsEncrypt certificate for that service and can access that application.

Subsequently, if I revisit the original service, I am now passed to Dex for authentication and can access the previously broken service using a LetsEncrypt certificate.

Since this is a wildcard certificate on the domain, it suggests that the problem is at the point that K8S is being configured to hand out the certificate.

If I use the browser feature to clear the cookies and site data for the domain, the problem returns when I try to access the original service. So, it appears that the certificate isn't being attached to the ingress for that service but browsers will cache the certificate if they have visited other pages in the same domain. That's going to create some interesting debugging issues.

I can reproduce this in Firefox, Chrome and Safari.

**Comment by tdcox** [comment]
Ok, the ingress-controller logs are showing:

```
Error getting SSL certificate "jx-staging/tls-kill-9-uk-p": local SSL certificate jx-staging/tls-kill-9-uk-p was not found. Using default certificate
```

jx-staging/tls-kill-9-uk-p exists but is marked 'READY: false' and appears to be missing some certificate information.

**Comment by ccojocar** [comment]
I think an easy fix for now is to add both annotations for old and new cert-manager. The certmanger will pick the proper annotation based on its version. The other one will be just ignored.
