### ISSUE TITLE
Documentation Needed for Vault Setup

### ISSUE THREAD

**Issue by GLStephen** [jenkins-x/jx#6547]
If a vault isn't created at the initial setup, then this page leaves out a critical step.

https://jenkins-x.io/docs/reference/components/vault/

The @ccojocar comment at the end of https://github.com/jenkins-x/jx/issues/3628 indicates a needed step which is:

jx create addon vault-operator

The failure of "jx get vaults" saying "No vault found." versus "NAME URL AUTH-SERVICE-ACCOUNT" seems to indicate this state.

**Comment by ccojocar** [comment]
it is possible to create a vault later on following those commands but I would rather recommend to change in the `jx-requirements.yml` file the key:
```
secretStorage: vault
```

and run boot again. Unfortunately there isn't yet a way to migrate the secrets from local storage into vault when changing the secrets store.  

Also vault requires TLS to be enabled in order to have a secured boot setup.
