### ISSUE TITLE
Dev environment fails with auth errors after `jx upgrade boot`

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6583]
### Summary 
After running `jx upgrade boot`, my environment fails to restart with the following error:
```
error: no auth server found for git server https://github.com from gitURL https://github.com/Bootstrap-Jersey/environment-d81-dev.git
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''
```
The `jx-auth-config` configmap and `jx-pipeline-git-github-github` secret are not present.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1140
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

**Comment by abayer** [comment]
This cluster started with boot config 1.0.60, appears to have upgraded a few times since then, the most recent time being to 1.0.77, and this time things went...bad.

**Comment by abayer** [comment]
The first time this cluster upgraded, to 1.0.68, which should have cherry-picked the commits adding the `jx-auth-config` steps/directory, there were no cherry-picks, just version stream and builder image updates. The next upgrade bumped to boot config 1.0.71 and cherrypicked the changes from 1.0.68 to 1.0.71 fine, followed by an upgrade that just bumped version stream/builder versions, because the boot config hadn't updated in that time, and the most recent upgrade bumped to boot config 1.0.77 and cherrypicked changes from 1.0.71 to 1.0.77.

**Comment by abayer** [comment]
@hferentschik - since you may have spent more of your life beating your head against the `jx upgrade boot` cherry pick mess, can you think of any way that it would just not even _try_ to cherry pick for one upgrade? `upgrade_boot.go` hasn't changed in the relevant time period, so I don't _think_ the local jx version matters, but I could be wrong.

**Comment by hferentschik** [comment]
Do you have the logs upgrade logs? Have you tried to reproduce? Do you have the shas of the commits which should in your opinion have been cherry-picked? Did you do the upgrades from the same directory/checkout or did you clone the dev repo into a new directory and did the upgrade from there?

**Comment by abayer** [comment]
SHAs that should have been cherrypicked - i.e., the ones in `jenkins-x-boot-config` `v1.0.68` but not `v1.0.60` (ignoring merge commits, which actually get ignored, to my surprise, and the empty tag commit for `v1.0.68`):

```
63e9974f4e4506ca30d8306f428af32eb04a87ce
2918c5d31263b81dec6c2675a0c6716774274d08
3bd3ebd5287789f6f6a56a377a6a33716f6c0379
63e9974f4e4506ca30d8306f428af32eb04a87ce
2918c5d31263b81dec6c2675a0c6716774274d08
3bd3ebd5287789f6f6a56a377a6a33716f6c0379
25203220504cbf77d3895b801fcc3d76193fa4ea
59afbeb0cf17ffd3960350d6d28f610da943907e
d033704920aa7dc180cbd80472fb05e773219478
1d2d77772bd1f0782229c0fae6bc490da7a2b293
0d076e6dc776b9d858e926d6c0064ec3f8e9052a
a8c13a36ef84c99a194a66c2601fbf5127fb5149
649cff7ed20f600b82ec4ed12f0b11b416307855
fb5ebb3ab6d914feab609980ed8622058a98098a
1252c062af8cfef618a080371992ae7a6274bd9d
242ae80c197d5454fc76699ff767d6261e043cde
fa92b65c0a5b61801ee7ad481ce2e6899318839c
```

That's oldest to newest. As I said, the subsequent `jx boot upgrade` runs where there was a change in `jenkins-x-boot-config` did have their commits cherry-picked (including the empty tag commit, but not including the merge commits).

I tried to reproduce - using version stream 1.0.276 and jx version 2.0.1100 (the ones corresponding with `jenkins-x-boot-config` `v1.0.60`), and upgraded all the way to boot config `v1.0.77`, the most recent as of this moment, with jx binary 2.0.1142 and the current version stream, `v1.0.313`. That failed to reproduce. I tried again with the appropriate version stream for when the upgrade to `v1.0.68` was attempted, 1.0.293, but still using jx binary 2.0.1142 because I forgot to switch to 2.0.1116, the one in use at the time, and it went fine.

**Comment by daveconde** [comment]
@tdcox would it be possible for one of us to please get temporary read access to your dev environment repository so that we can see what got applied in the upgrade PR? Also if you had the logs from `jx upgrade boot` that would be really helpful.

**Comment by daveconde** [comment]
It would also be interesting to see the version of jx used in the builder image that is executing the boot pipeline.

**Comment by hferentschik** [comment]
> SHAs that should have been cherrypicked ....

OOI, how did you produce this list?

> ignoring merge commits, which actually get ignored, to my surprise

There is something fishy going on here

**Comment by abayer** [comment]
I have read access to the dev env repo. =)

If you look at the history of `jenkins-x-build-config`, it is _full_ of merge commits until very recently, since that was how all merges were done until I switched that last week. So something in the cherry picking logic is not working as we had thought, or every upgrade ever would be failing due to them.

**Comment by hferentschik** [comment]
So I am mistaken, there is code to skip merge commits -  https://github.com/jenkins-x/jx/blob/1e4ea3adaa21632382eefb7aff93d40b631832af/pkg/cmd/upgrade/upgrade_boot.go#L370

**Comment by hferentschik** [comment]
The tricky bit here is that parts of the interesting information is lost. The code checks out the boot config into a temporary directory to determine the commits to cherry-pick. Would have been nice to see the state of these checkouts, but that's lost. 

There are temporary branches created for the upgrade, that would be also interesting to see. Really the local checkout and its branches and state are more interesting than what's currently in the repo.

**Comment by abayer** [comment]
@tdcox We got past this, right? We never figured out what the root cause for the commits not getting cherry-picked was, but you did get unblocked. So I'm gonna move this to critical.

**Comment by tdcox** [comment]
Yeah. No guarantee that we won’t see it again in another update operation.

**Comment by abayer** [comment]
Gotcha - that's why I left it at critical. =)
