### ISSUE TITLE
Vault pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6591]
### Summary 
I have come in this morning to find that the vault pod of my recent boot cluster is stuck in CrashLoopBackOff. Checking the pod description, I see the following error:
```
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/33546a3f-3b70-11ea-bce4-42010aa401ed/volume-subpaths/jx-vault-ice-01-gcp-sa/vault/0\\\" to rootfs \\\"/var/lib/docker/overlay2/15270ee54309d3160575247a8606684700e6f38daba67d4e7a58d385e7e45736/merged\\\" at \\\"/var/lib/docker/overlay2/15270ee54309d3160575247a8606684700e6f38daba67d4e7a58d385e7e45736/merged/etc/gcp/service-account.json\\\" caused \\\"no such file or directory\\\"\"": unknown
```

### Jx version

The output of `jx version` is:

```
2.0.1139
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

**Comment by ccojocar** [comment]
Did you upgrade the Kubernetes cluster, out have auto-upgrade on?

**Comment by ccojocar** [comment]
If you delete the vault POD, and let it to be recreated what's happening?

**Comment by tdcox** [comment]
Auto-upgrade is configured but doesn't seem to do anything. There are no pull requests indicating an upgrade.

**Comment by tdcox** [comment]
Deleting the pod manually restarts the services correctly.

**Comment by ccojocar** [comment]
It seems to me that the error says that the mounted GCP service account which is coming from a secret in the vault Pod somehow had vanished. It might be related to the underlying Kubernetes infra, but it is difficult to say what did cause this.

**Comment by ccojocar** [comment]
@tdcox Can we close this as a transient issue?

**Comment by tdcox** [comment]
I’m wondering if there is a race condition during deployment of the secrets that can leave the pod in an unstable condition? Given the critical nature of vault, we should at least be looking at something to improve the monitoring and recovery of this pod.

**Comment by ccojocar** [comment]
During deployment, the vault health is really checked and also the state of the vault. This is going underneath when the message `wait for vault to be initialised and unsealed` is printed out. The boot doesn't sore any secrets until the vault is ready. 

Did this happen immediately after a boot deployment or at runtime? My impression is that this happened somehow at runtime because the volume for GCP service account secret somehow despaired from the vault Pod. As I understand, it seems that the kubernetes health probe was restarting the Pod but after a number of restarts, it ended up in a CrashLoop since wasn't able to recover. 

There is an option to enable HA mode on vault (e.g. with 2 Pods). One pod waiting in stand-by to be elected as leader when the other Pod goes away. We had this setup in the past but there were some race conditions during vault unsealing, so because of that we decided to use only one instance. (See here https://github.com/jenkins-x/jx/blob/2393eea3509c6dec3d2444165c15e3c5bfaeba99/pkg/kube/vault/vault.go#L46). 

I agree that we need better monitoring across the board. I think this is a more generic requirement for Jenkins X.

**Comment by tdcox** [comment]
It's not clear whether this happened during an update to the dev environment or during normal operation.

**Comment by ccojocar** [comment]
Alright, probably we should keep an eye on it to collect more data. Let's keep this open until there is more clarity when exactly it happens.
