### ISSUE TITLE
Vault fails in EKS with Boot

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6654]
### Summary 

Jenkins X Boot is missing the configuration for Vault.

### Steps to reproduce the behavior

```bash
git clone \
    https://github.com/jenkins-x/jenkins-x-boot-config.git \
    environment-jx-eks-dev

cd environment-jx-eks-dev
```

Modify jx-requirements.yml by changing the `provider` to `eks` and set `secretStorage` to `vault`

```bash
jx boot
```

The process fails. The last few lines of the output are as follows.

```
Vault operator installed in namespace jx
Applying vault ingress in namespace jx for vault name jx-vault-jx-eks
ingress.extensions/jx-vault-jx-eks created
error: unable to create Vault creation parameter from requirements: missing AWS configuration for Vault in requirements
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders' command in directory 'systems/vault', output: ''
```

### Expected behavior

It works

### Actual behavior

It fails

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1162
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.17.0
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G2022
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

macOS

**Comment by dgozalo** [comment]
Vault for EKS requires some extra configuration compared to GKE.

Right now, Vault is not working with IAM Roles for Service Accounts so it's expecting at least the user to provide an existing IAM User in the `jx-requirements.yml` file.

It would be under:

```
vault:
  aws:
    autoCreate: true
    iamUserName: <IAMUsername>
```
We will create a new pair of Access Keys for this user. There's a limit of 2 access keys per User so make sure that there's at least one slot left.

You can also provide already existing keys instead of having Jenkins X create a new pair with the following Env variables:

**VAULT_AWS_ACCESS_KEY_ID** and **VAULT_AWS_SECRET_ACCESS_KEY**.

There will be documentation coming out very shortly, I'll update this issue once it's out.

**Comment by deanesmith** [comment]
@vfarcic OSS docs will be updated soon.
