### ISSUE TITLE
Install serverless jenkins x on kubernetes --on-premise with gitlab or any other repository but except github

### ISSUE THREAD

**Issue by arfiqbal** [jenkins-x/jx#6692]
Just want to install serverless jenkins on kubernetes without github as we are using bitbucket and gitlab and Is there any way to use lighthouse ? 

Our kubernetes is build on top of  openstack 

` jx install --provider='kubernetes' --on-premise --domain="k8sapp.xxx.com" --git-provider-kind="gitlab" --git-provider-url="http://git.apps.ocp.xxx.com" --git-username="arif" --skip-ingress=true  --default-admin-password=admin --exposecontroller-urltemplate='{{.Service}}-{{.Namespace}}.{{.Domain}}' --urltemplate='"{{.Service}}-{{.Namespace}}.{{.Domain}}"' --namespace='jx-serverless' 
Command "install" is deprecated, it will be removed on Jun 1 2020. We now highly recommend you use jx boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
error: checking the provided flags: Git provider: gitea is not yet supported for Tekton.
You can work around this with '--static-jenkins'
For more details see: https://jenkins-x.io/about/status/`

**Comment by abayer** [comment]
Please try again with `jx boot`, specifying the `webhook` as `lighthouse` instead of `prow` in your `jx-requirements.yml`, rather than `jx install`. Basic functionality with GitLab should then work, but note that GitLab support in Lighthouse is still pretty immature, with chatops definitely not working right and possibly other issues. If you hit issues with GitLab + Lighthouse, please open issues in https://github.com/jenkins-x/lighthouse/issues. Thanks.

**Comment by abayer** [comment]
Oh, and Gitea is not supported with Tekton at all, and Bitbucket is...really not there yet, with chatops not working at all and builds not getting triggered by new commits pushed to an existing PR.
