### ISSUE TITLE
Discovery - Enable integrated testing of the jx stack for PRs spanning multiple repositories

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#6736]
# Summary

Create a proposal and backlog items for the problems listed in #6726

**Comment by abayer** [comment]
So messing around with `jenkins-x-platform` isn't really viable. This means that basically the scope is combining `jx`, `jenkins-x-boot-config`, and probably `jenkins-x-versions`. We'll need to ensure that the builders have the PR's `jx` binary in the `PATH` before the baked-in one, and that pod templates used in BDD tests and relevant cronjobs and controllers have the right `jx` binary in them as well.

The last part is the easiest, albeit a bit awkward. We already override [the build controller and specific pod templates from `jenkins-x-platform`](https://github.com/jenkins-x/jx/blob/15eeaf5aa349a4faf1d33f572745fe484442f146/boot-vault.platform.yaml.template) and [the image used in the pipelinerunner](https://github.com/jenkins-x/jx/blob/15eeaf5aa349a4faf1d33f572745fe484442f146/boot-vault.prow.yaml.template) for `jx`'s `boot-vault` test context - we just need to add more controllers, cronjobs, and possibly pod templates to check that off.

Picking up a PR of `jenkins-x-boot-config` is fairly trivial - just check out the PR ref when we clone `jenkins-x-boot-config` before running `jx boot` and we're generally good to go (things can get a bit wonky w.r.t. the version in the version stream, though). And in theory, `jx step bdd` also supports using an arbitrary PR for the version stream, though I think that's a bit buggy, so some work may be needed there to get it to function correctly. The open question on this front is whether we need to create a new version stream branch to point to the `jenkins-x-boot-config` PR ref rather than the latest release - I'm legitimately not sure if that's necessary at this point, we'll have to see.

That leaves us with two hard parts: how to tell the new test context in `jx` that it should use PRs in `jenkins-x-boot-config` and/or `jenkins-x-versions`, and how to make sure that builders used in pipelines run as part of the BDD tests run the `jx` PR's binary, not the baked-in one. If every pipeline just used the pod template names, nothing would need to be done on that front, and in practice, I think that may be the case for almost everything. But [charts like the staging and production envs](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/charts/pipeline.yaml) and [`jenkins-x-boot-config` (and therefore the dev env)](https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jenkins-x.yml) use `gcr.io/jenkinsxio/builder-...`, not pod template names. We could trivially hack the dev env to use the "right" builder version (i.e., the one built/pushed before we spin up the cluster), but that doesn't help with the other charts, and frankly, it feels like it'd be good to have a solution for this in general.

@daveconde had an idea on that front: we add an arbitrary guaranteed-to-be-empty-by-default directory to the path of every builder before `/usr/local/bin` (i.e., where we copy the `jx` binary when building the images). We then add a new PV to be generated in `jenkins-x-boot-config` - by default, it'll be empty, but if specified, we'll put the `jx` binary built in the test context into the volume. Then we configure every container in the metapipeline and generated pipeline to read-only mount that volume to the new directory we created on the builder for every step using a builder image. So in the normal case, the baked-in `jx` will be run by any `sh: jx ...` step, but if we've put a different `jx` binary in that volume, that will get run instead. Need to figure out exactly how we'll get the new `jx` binary onto the volume, though. (The original idea was to use a `ConfigMap`, but there's a max size of 1mb for those.)

Assuming that the volume approach can be done, that means the remaining challenge is how to pass in the information on which other PRs to incorporate. I do not yet have a good idea there - our Prow and pipeline setup doesn't let us pass arbitrary parameters via `/test ...` (I'm not even sure that's doable at all with `/test`, but there definitely isn't a way to pass parameters to pipelines with our setup), so the best I've come up with is either looking for a YAML file in the `jx` repo, which you'd presumably need to nuke before merging to avoid conflict hell and general confusion, or having an additional new repo (like `jenkins-x/jx-cross-repo-test-configuration`) and looking in there for a file called `pr-123.yml` for the info. I'm leaning towards the latter.

There are some other purely mechanical things that would need to be resolved - which tests to run (as many as humanly possible, including possibly upgrade), how to deal with TLS (since we'd want this to be comprehensive, we'd really want TLS involved, but then we have to have a set of domains and a fast enough rotation system to allow for the possibility of two different PRs kicking off the test context within a few minutes of each other), etc - but those are just implementation details.

**Comment by abayer** [comment]
Worth mentioning re: the volume thing, if we're only thinking about scoping this for BDD tests run on GKE, we could just create a persistent disk (and a persistent volume using that persistent disk) as part of `jx step bdd` and use that, with the only configuration in `jenkins-x-boot-config` being specifying the "special `jx`-containing volume" name. In that scenario, we wouldn't mount the volume at all if no name was specified.

**Comment by abayer** [comment]
I've done a proof-of-concept of the cross-repo part with https://github.com/jenkins-x/jx/pull/6755 (which failed, but is meant to have failed - the PR it pulled from `jenkins-x-boot-config` tweaked its `jenkins-x.yml` to fail immediately to demonstrate that it was picked up), using a YAML file in https://github.com/abayer/jx-cross-repo-test-configuration to drive it. This was the simple part, of course, but also the most important part, so yay.

**Comment by abayer** [comment]
So here's my proposal for the near-term:

* Trying to deal with `jenkins-x-platform` is a pain, so I'm just going to target combining `jx`, `jenkins-x-boot-config`, and `jenkins-x-versions` for the moment. I believe the overwhelming majority of cases will be covered by those three, particularly by `jx`+`jenkins-x-boot-config`, so this will provide real value without requiring any changes to how things actually function normally.
* A new repo (gonna go with `jenkins-x/jx-cross-repo-test-configuration` if no one has a better name) will be created, to contain `pr-1234.yml` files, where `1234` is the number of a `jx` PR. These YAML files will contain one or both of `jenkins-x-boot-config: 567` and `jenkins-x-versions: 890` (or `pr-567` - the logic will be able to handle either and won't be case sensitive), pointing to PRs in the other repos that should be pulled in for cross-repo testing of `jx` PR `1234`.
* When you run `/test cross-repo` (a new, optional context), a new BDD test context will run. In its `ci.sh`, it will look for the `pr-1234.yml` in the config repo mentioned above, and if the file exists, it'll get pulled down and the values, if set, for `jenkins-x-boot-config` and `jenkins-x-versions` will be fetched. This will be done _before_ building the binary to be used in the BDD tests.
  * Comments will be left on the relevant `jenkins-x-boot-config` and `jenkins-x-versions` PRs linking back to the `jx` PR, stating that a cross-repo PR test is running. (Eventually, I'd like to have Lighthouse actually create/update statuses for the cross-repo PR on the other PRs, but that's not in scope for the near-term.)
  * The values for the other repos will be used, if set, to bake in the default version stream and default boot config repo and branch in the build of the binary. (note - I am not 100% sure on this part, since it would make upgrade testing difficult at best, so I may walk this back.)
  * After building the binary and test images, the boot config PR, assuming it's specified, will be cloned/checked out rather than the boot config release from the version stream.
  * If a version stream PR is specified, it will be used for getting the boot config release to use (if no boot config PR is specified), and the `jx-requirements.yml` we'll use to boot with will have its version stream ref set to use the version stream PR.
  * We will then boot as normal from there.
* A full battery of tests will be run in a standard GKE/boot/vault/gitops/Prow (until Lighthouse is the default in boot config) configuration. At a minimum, this set of tests will include the following targets from `bdd-jx`'s `Makefile`:
  * `test-create-spring` (for adding a repo, releasing, going to staging, opening a PR, verifying the preview, merging the PR, promoting to production)
  * `test-single-import` for `node-http` (verifying import with something other than a golang quickstart)
  * `test-quickstart-golang-http` (verifying the full quickstart suite with the fastest quickstart to test that we've got)
  * `test-import-golang-http-from-jenkins-x-yml` (verifying more advanced Tekton syntax behavior, such as multi-stage)
  * `test-app-lifecycle` (which in the gitops case will install the UI and make sure it is serving properly, and then will remove the UI)
* Upon completion, the `jx` PR will have its status updated as normal, and the `jenkins-x-boot-config` and `jenkins-x-versions` PRs, if specified, will have comments added to them linking to the context's result. (Again, down the road, I'd like to have standard GH statuses on the other PRs.)

Alongside actually implementing that, I'll also be creating a task for identifying things we _should_ be testing in BDD that aren't being tested currently. As further tests are added to `bdd-jx`, those tests will be invoked by the cross-repo test as well.

Additional areas we may want to be testing with existing tests but that may be a hassle to incorporate into this test context for various reasons:
* Upgrade testing. This will probably require initially booting with the standard values for default boot config/version stream repo/version, then rebuilding the binary with our custom values, so may take some work. If that work is sizable enough, adding upgrade testing will be done after the initial "release".
* TLS. The challenge here is entirely around domain assignment - we would need a separate pool of domains from those used in `jenkins-x-versions`'s `boot-vault-tls` context, and we'd need to ensure that multiple PRs could run the cross-repo context without domain collision, so this will also be a follow-up task.
