### ISSUE TITLE
Is there any plan to add node-ip parameter for jx command?

### ISSUE THREAD

**Issue by J-Tera** [jenkins-x/jx#682]
Regarding to exposecontroller commit [970bd36](https://github.com/jenkins-x/exposecontroller/commit/970bd360043424d08e393d9d855529363357c9a0) the there is node-ip config for NodePort. But jx command does not support node-ip parameter.
Is there any plan to enable to use node-ip parameter?

**Comment by jstrachan** [comment]
@J-Tera I'd prefer to avoid it if we can ;) If there's a real need we could consider it but networking via a node's IP is a little bit of a hack really, not something you'd ever want to use for real - on a cloud you typically don't have access to the IPs of the nodes. We prefer folks to use things as close to what production would look like; so using Ingress sounds better really. 

Plus technologies like Istio/Ambassador for doing things like blue/green or canarying is very handy which only works with ingress: https://github.com/jenkins-x/jx/issues/582

I guess this is just for trying things out on a single machine right?  I wonder if the OOTB ingress can work for you instead? Then you get to use nicer URLs rather than having to deal with lots of random port numbers to access services inside your node IP address?

**Comment by jstrachan** [comment]
am gonna mark this as closed for now - but let us know if you really need Node-IP support and we can reconsider
