### ISSUE TITLE
Use Kaniko directly instead of the hack that overrides skaffold build inside jx

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#6885]
### Summary 
there is a hack in the code that modifies the step from skaffold to use kaniko directly, until this is fixed this hack should removed, and pipelines should be updated
https://github.com/jenkins-x/jx/blob/d4dc45c69d6cd912cb4cb9fa4f909ceeb89bd76f/pkg/tekton/syntax/pipeline.go#L1206-L1237

### Jx version

The output of `jx version` is:

```
2.0.1234
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
So this is actually a pain to deal with because build packs aren't versioned, and static master users pick up the same build packs as Tekton-driven pipeline users do. Skaffold is needed for static master cases, so until we address the lack of versioning of build packs, we're stuck with the silly replacement logic.

**Comment by yelhouti** [comment]
Thanks for the explanation :)
