### ISSUE TITLE
Unable to create project from installation to use jx boot with tekton and gitlab

### ISSUE THREAD

**Issue by johnamac7** [jenkins-x/jx#6995]
### Summary 
I'm testing an installation of Jenkins X with http to gitlab and tekton pipelines (as the existing Jenkins masters will be unsupported after 20th April). The installation was successful, however now if I try to create a project, I get an error.

### Steps to reproduce the behavior
```
Attempt to create a project using the quickstart method.
jx create quickstart
? select the quickstart you wish to create golang-http
Using Git provider dungloe.local.belfast at http://dungloe.local.belfast
? Do you wish to use tester as the Git user name? Yes
? Who should be the owner of the repository? tester
? Enter the new repository name:  golang-http-project
Creating repository tester/golang-http-project
Generated quickstart at /root/jenkinsx/golang-http-project
Created project at /root/jenkinsx/golang-http-project
The directory /root/jenkinsx/golang-http-project is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
performing pack detection in folder /root/jenkinsx/golang-http-project
--> Draft detected Go (65.746753%)
selected pack: /root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/go
replacing placeholders in directory /root/jenkinsx/golang-http-project
app name: golang-http-project, git server: dungloe.local.belfast, org: tester, Docker registry org: tester
skipping directory "/root/jenkinsx/golang-http-project/.git"
Pushed Git repository to http://dungloe.local.belfast/tester/golang-http-project
```

### Expected behavior
Project created successfully and pipelines started as planned.

### Actual behavior
```
Error when trying to generate a pull request to the dev pipeline environment.
WARNING:
error: failed to create Pull Request on the development environment git repository http://dungloe.local.belfast/tester/environment-testcluster-dev.git: unable to create pull request: creating git provider for https://dungloe.local.belfast/tester/golang-http-project.git: no Git service resource found with URL 'https://dungloe.local.belfast' in namespace jx
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1261
Kubernetes cluster v1.17.2
kubectl            v1.16.3
helm client        2.14.1
git                2.16.6
Operating System   "CentOS Linux release 7.7.1908 (Core)"
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Kubernetes bare metal cluster. Created using an ansible script which also used to install the cluster which my existing instance of 'Classic Jenkins' which is working fine.

### Operating system / Environment

 Centos Linux

**Comment by jalonsoa** [comment]
Hi !
  can you review your ~/.jx/gitAuth.yaml file ? Yo must have a kind entry for all servers that you have in this yaml file. For example:

servers:
- currentuser: gitlab-group
  kind: "gitlab"
  name: mygitlab.com
  url: https://mygitlab.com
  users:
  - apitoken: 12345678890752
    bearertoken: ""
    username: gitlabuser

If you don't have the kind entry (and the default instalattion don't create it) the jx command thnks that your git server is a github and use this gitlab provider in many requests

**Comment by xiaomingkou** [comment]
facing the same issue.
The problem is my gitlab is http://gitlab.example.com but jx creates PR with https://gitlab.example.com. Why from http to https?


root@bootstrapper [ ~/quickstart/my_project_4 ]# jx create project
? Which kind of project you want to create:  Import existing code from a directory
? Which directory contains the source code:  /root/quickstart/my_project_4
? Which Git service do you wish to use http://gitlab.example.com
WARNING: No username defined for the current Git server!
? Do you wish to use my_username as the Git user name: Yes
The directory /root/quickstart/my_project_4 is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
trying to use draft pack: jenkins
selected pack: /root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/jenkins
? Who should be the owner of the repository? my_username
replacing placeholders in directory /root/quickstart/my_project_4
app name: my-project-4, git server: gitlab.example.com, org: my_username, Docker registry org: my_username
skipping directory "/root/quickstart/my_project_4/.git"
Draft pack jenkins added
Using Git provider gitlab.example.com at http://gitlab.example.com
? Using organisation: my_username
? Enter the new repository name:  my_project_4
Creating repository my_username/my_project_4
Pushed Git repository to http://gitlab.example.com/my_username/my_project_4
WARNING: 
error: failed to create Pull Request on the development environment git repository http://gitlab.example.com/my_username/environment-k8s-cluster-dev.git: unable to create pull request: creating git provider for https://gitlab.example.com/my_username/my_project_4.git: no Git service resource found with URL 'https://gitlab.example.com' in namespace jx

**Comment by johnamac7** [comment]
Ok, so I checked out the jx code and did some debugging and found that in the git_url.go file, there are some responses that are defaulted to https. I changed some of these to use http and rebuilt the jx module. When I re-ran the create quickstart it failed again at the same point, so I changed all the corresponding https to just use http for the moment and rebuilt the package and after I re-ran the quickstart again it worked.

I'll need to revisit the code again to see if I can make it use both, but I'll need to see how that can be done. For now, its working for me on a locally built jx.
