### ISSUE TITLE
No error handling when retrieving logs from Google long term Storage

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#7027]
### Summary 
Retrieving logs in Google Storage does not catch errors, making it hard to debug when there is a permission access issue or any other kind of problem.

See https://github.com/jenkins-x/jx/blob/master/pkg/cloud/gke/gcloud.go#L558, we only watch stdOut and do not check for exit status code nor stdErr:

```golang
func StreamTransferFileFromBucket(fullBucketURL string) (*bufio.Scanner, error) {
	args := []string{"cp", fullBucketURL, "-"}
	cmd := exec.Command("gsutil", args...)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	err = cmd.Start()
	if err != nil {
		return nil, err
	}
	scanner := bufio.NewScanner(stdout)
	scanner.Split(bufio.ScanLines)
	return scanner, err
}
```

**Comment by hferentschik** [comment]
This won't be so easy to fix I think w/o breaking the intended streaming behaviour.
Instead of trying to handle errors implicitly, what's about adding explicit code trying to access the bucket prior to copying it? We could execute a `gsutil -q stat` prior to the cp to check whether the bucket exist and if not return the error. If the bucket exists and is readable, it should be safe to use the current behaviour. You might still get generic IO error, but I don't think this matters for our case.

**Comment by romainverduci** [comment]
@hferentschik that's actually a good idea, I will give it a try. 
Also I was wondering if we really need streaming on that as it's not to get live logs but stored logs. If we don't we can just use cmd.Run() and the error handling would be easier.
