### ISSUE TITLE
Rollback minimum required kubectl version

### ISSUE THREAD

**Issue by briantopping** [jenkins-x/jx#7121]
According to https://github.com/jenkins-x/jx/issues/6384#issuecomment-586654525, Velero has been working with current versions of `kubectl` for some months. Roll back change to limit versions accordingly.

**Comment by deanesmith** [comment]
Hi @briantopping, I'm not entirely confident we have the means to test all functionality on that new of a version of kubectl.  One thing we are doing - loading binary dependency versions locally in /.jx/bin and referencing only those in code.  This would essentially remedy since we are incapable of fully supporting such a broad range of dependencies.

**Comment by briantopping** [comment]
Hmm, I can’t really advise that there is or is not a problem other than the problem that it doesn’t work the way it stands, either. What do you think the solution is? How did new versions used to get validated? I understand the predicament, it just seems like you’ll never be able to move beyond this version with that logic. 

Speaking for myself, I’ve never gotten JX to work a single time because of my environment. So it’s not like it is validated to work in every environment anyway. For that reason, I think this version limit is an unnecessary additional roadblock that seems have outlived its usefulness see referenced issue resolution) for the original reason it was changed in the first place.
