### ISSUE TITLE
The command "jx create tracker server jira" doesn't work

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/jx#7237]
### Summary 
Trying to link jira to jx, I've used the command [described here](https://jenkins-x.io/commands/jx_create_tracker_server/) with `jx create tracker server jira https://<my-org>.atlassian.net/`  but I've got this error:
> error: current user for "https://<my-org>.atlassian.net/" server is empty

I then tried the command `jx create tracker token -n jira <my-jira-username>`:
> error: Invalid option: --name jira
Possible values: 

And also `jx create tracker token`:
> error: Could not find a issues. Try creating one via: jx create tracker server

### Steps to reproduce the behavior
`jx create tracker server jira https://<my-org>.atlassian.net/`

### Expected behavior
A link between jx & Jira is created.
### Actual behavior
Error messages as seen above.
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.40
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.24.2 (Apple Git-127)
Operating System   Mac OS X 10.15.3 build 19D76
```

### Kubernetes cluster

GKE, but also AKS, manually created

**Comment by deanesmith** [comment]
Hi @hervelemeur, thank you for reminding us this exists!  We need to review the functionality and determine the cause of the issue.  Overall, it's not a priority for the CloudBees JX team, but you're welcome to diagnose and propose a fix.

**Comment by hervelemeur** [comment]
@deanesmith I didn't knew about this feature until [this thread in slack](https://kubernetes.slack.com/archives/C9MBGQJRH/p1589358661001300), and like Gazal I'm interested by having jira links in the changelog/releases page.

**Comment by gazal-k** [comment]
@deanesmith I started looking into this because the `jx step changelog` logs: `WARNING: Failed to enrich commit` for our commits that reference JIRA issues.

I looked into the code for `jx step changelog` and figured out that we can add this in `jenkins-x.yml`:

```yaml
issueTracker:
  kind: jira
  url: https://ourorg.jira.com/
```

It seems to need credentials for JIRA as a secret though. I hadn't gotten around to figuring out the spec for the required secret. Also `jx create tracker server` seems to indicate it can be set globally. We can contribute to fixing this command. But in the meantime can someone please share the resources that  `jx create tracker server` creates on the cluster? I'm assuming it must be a `ConfigMap` for issue tracker and a `Secret` for JIRA credentials

**Comment by deanesmith** [comment]
@gazal-k, someone will get back to you on your request.
