### ISSUE TITLE
dev environment PR build failing when performing 'step-verify-parameters'

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#7291]
### Summary 
When performing an environment PR build the following error stops the pipeline:
```
Showing logs for build ***-environment-jbx6n-1 stage pr-checks and container step-verify-parameters
error: resolve the secrets URIs: creating secret client: creating system vault URL client: error parsing Vault configuration from ConfigMap **-install-config in namespace **: service account name cannot be empty
```

**context**: This is a recent upgrade (https://github.com/jenkins-x/jx/pull/7267) on the cluster to `v1.0.484`, applied to the cluster using an older `jx` binary. This meant that the vault configuration which was expected to be written to the `jx-install-config` configmap during the upgrade wasn't performed.

**Work around**: re-running the jx boot of the environment should ensure the `jx-install-config` config map is updated to contain the necessary config.

**Comment by hferentschik** [comment]
The problem is that the pull request pipeline does not run _install-vault_ which would update the configuration as required. The pipeline "just" runs _verify-parameters_ which in turn tries to access the secret client which without prior _install-vault_ won't work.

Not quite sure what to do here. @cagiti any ideas/suggestions?

**Comment by hferentschik** [comment]
I think the easiest would be to relax the validation for the internal Vault case since we basically "know" that the service account name will be passed (by the way the code it written).
