### ISSUE TITLE
Running Boot Takes Too Much Time

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#7295]
Executing `jx boot` takes too much time after the initial setup. Even if we do not change anything, and just re-run it, it takes around 5-10 minutes to finish. The only step that could be justified as long-running is probably `Install Jenkins X`.

**Comment by hferentschik** [comment]
>  The only step that could be justified as long-running is probably Install Jenkins X

What's do you mean, the whole purpose of `jx boot` is to install Jenkins X, right? Which concrete step would you consider to be ok to be long-running and which steps are taking too long?

BTW, I am not disagreeing. It takes a long time, partly because we keep re-installing all Helm charts. In order to skip some of the steps, we would need to be able to determine whether a chart has changed. Not sure this is possible in the current for we apply them.

**Comment by vfarcic** [comment]
I'm fine with the time it takes to install. I'm referring to execution time after the initial install. Conceptually, 10 minutes to run the dev pipeline that does not install anything new or even upgrade anything is a lot, especially since `dev` pipelines are run every time someone adds a new project. When you execute `jx create quickstart`, a PR is created in the `dev` repo by adding the information about the new project which, in turn, probably only adds the info to a ConfigMap or a Secret.

P.S. This is not urgent or even very important. I just thought to file this as an issue for whenever the community is left with only less important things to work on :)
