### ISSUE TITLE
jx get urls doesn't show chart museum.. 

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#7340]
### Summary 

`jx get urls` used to display chart museum url now it doesn't show it anymore, but there is an ingress exposed for it. It will be really useful to have it back. This is a regression. 

### Steps to reproduce the behavior
`jx get urls`

### Expected behavior

show chart museum url in the output

### Actual behavior

does it show it 

### Jx version

The output of `jx version` is:

```
salaboy> jx version
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.16.9-gke.2
kubectl            v1.13.2
helm client        2.12.2
git                2.24.3 (Apple Git-128)
Operating System   Mac OS X 10.15.4 build 19E287
```

**Comment by ankitm123** [comment]
The problem is this:
The service name is `jenkins-x-chartmuseum` but the ingress name is `chartmuseum` , so jx tries to search for an ingress with the name `jenkins-x-chartmuseum`, and throws an error (which is not caught). There was a chart version update from 1.6 to 1.7 to support 1.16 apis (removing v1beta1), I am thinking if that changed anything. I will have a PR with the fix.

@salaboy  was it working for 1.15 cluster, and not working for 1.16? Would be good to know.

**Comment by ankitm123** [comment]
The issue actually comes from this file: https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/700-chartmuseum-ing.yaml#L14.
Interesting this value has not changed in 10 months (since initial creation :confused: )
