### ISSUE TITLE
tf-boot context frequently fails on destroy for non-empty bucket on object not found

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#7406]
Specifically with errors like:
```
Error: could not delete non-empty bucket due to error when deleting contents: googleapi: Error 404: No such object: vault-pr-7392-47-tf-boot-808f601781c9/sys/counters/requests/2020/06, notFound
```

Seems to be some kind of race condition/bad luck, but not sure. This is particularly annoying because it results in some non-trivial percentage of `tf-boot` runs failing on this.

**Comment by hferentschik** [comment]
I've seen the error now as well. It might be that as part of the `jx` namespace destruction, the Bank-Vault operator gets shut-down which deletes some files while at the same time the bucket itself gets destroyed. I think there are a few things we can try:

- In Terraform have a dependency between the bucket and the jx namespace, so that the bucket cannot be deleted while the jx namespace still exists
- As part of the teardown, we first run `jx uninstall` to uninstall. This might be a good idea anyway, since it seems "the right thing to do".  For this pull request #7353 should merge first
- Explicitly empty bucket via `gsutil` prior to the destroy
