### ISSUE TITLE
Updating or replacing exposecontroller, too many bugs and no maintainance

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#7587]
I have more and more problems with `exposecontroller` (https://github.com/jenkins-x/exposecontroller). But the project seems dead (last commit ten months ago, PRs go rotten), and seems anyway pretty old (it uses a very old version of kubernetes lib and doesn't event use go mod).

My current unsolvable problems are:
- ingress aren't properly updated when the ingress already exists, it just has a weird update logic. TLS configuration may not be applied (with all the securities issues it implies), old config parts are kept ... I don't see any reason to not just systematically replace the ingress, as long as it was created by exposecontroller. (https://github.com/jenkins-x/exposecontroller/pull/202)
- the `fabric8.io/ingress.annotations` is parsed without yaml, just by splitting. This can bug with any extra space, and doesn't allow to set annotation values with newlines. (https://github.com/jenkins-x/exposecontroller/issues/206)

My first PR got rotten, I don't expect any problem to be solved, and I think that in general the project is not worth maintaining. Creating a new exposecontroller would probably be better.

**Comment by aure-olli** [comment]
I developped my own fork: https://github.com/olli-ai/exposecontroller
It is updated, tested, many bugs fixed.
Anybody feel free to use it, honestly should become the official one.

**Comment by fforloff** [comment]
@aure-olli Tried your fork. Works great. One little thing - when running in a daemon mode Readiness and Liveliness probes fail because httpget to the port 10254 path /healthz returns status 503, while returning {"ready":true}. See:
`curl -vvvv localhost:10254/healthz
..
* Connected to localhost (127.0.0.1) port 10254 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:10254
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Date: Mon, 15 Feb 2021 05:00:51 GMT
< Content-Length: 15
< Content-Type: text/plain; charset=utf-8
<
{"ready":true}`

**Comment by aure-olli** [comment]
Thanks, let me know if you have any other problem with daemon mode :)

**Comment by msvticket** [comment]
This issue refers to Jenkins X 2, which isn't supported
