### ISSUE TITLE
Configure a Team with a default git organization 

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#764]
It would be nice to configure a Team as using a default git server & organization- so that we default that for any new repository

**Comment by jstrachan** [comment]
to implement this we'd just need to add git server + organisation name to the `TeamSetting` struct:
https://github.com/jenkins-x/jx/blob/master/pkg/apis/jenkins.io/v1/types.go#L117

then add CLI commands to let folks edit the git server + organisation names like the commands:
* [jx edit buildpack](https://jenkins-x.io/commands/jx_edit_buildpack/)

**Comment by rherrad** [comment]
and in this case git organization users will be the same that on jx team or it will be one jx service user who manage all git organization's users ?

**Comment by jstrachan** [comment]
The idea is each person will have an account on the git provider (github / bitbucket / whatever) and also have a login to the kubernetes clusters so we can do fine grained RBAC inside git, kubernetes and Jenkins etc

Though we suspect there will be a generic user that runs the CI/CD pipelines. e.g. all releases after a merge to master should be done by the 'Jenkins X' user; that could be different for each team or could be a global user.

**Comment by msvticket** [comment]
Don't we want that generic pipeline user to be put in the TeamSettings as well? This so it can be added as a collaborator of a repo when it is created.

**Comment by msvticket** [comment]
I plan to start working on this tomorrow. So the idea is to add fields in TeamSetting for:

- git server
- organisation
- pipeline user

Pipeline user is available in secrets (jx-pipeline-git-github-github), but I think it would be preferable to at least have the possibility to limit the access to secrets.

Another fields that would fit there would be docker registry. In AWS at least the registry repository needs to be created by `jx import` or equivalent. The problem is that now the logic relies on that environment variables are set the same during import as when installing jenkins-x in the cluster. An alternative could be to save the AWS region, but since that is specific to one cloud supplier I'm reluctant.

**Comment by msvticket** [comment]
All the fields I mention should be set automatically during jenkins-x installation. So normally there shouldn't be a need to edit them.

**Comment by msvticket** [comment]
Ah, I just realised that the docker registry already is in another configmap: jenkins-x-docker-registry
So not putting that in TeamSettings. But docker registry org would make sense to add to TeamSettings, in case a team wide override is required.
