### ISSUE TITLE
jx install failing on windows

### ISSUE THREAD

**Issue by shivasaxena** [jenkins-x/jx#769]
After entering the Github cradentials the tool is trying to download helm charts and failing with the following trace
```
Cloning the Jenkins X cloud environments repo to C:\Users\Shiva\.jx\cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Cloning the Jenkins X cloud environments repo to C:\Users\Shiva\.jx\cloud-environments
Counting objects: 529, done.
Total 529 (delta 0), reused 0 (delta 0), pack-reused 529
Generated helm values [32mC:\Users\Shiva\.jx\extraValues.yaml[0m
Installing Jenkins X platform helm chart from: C:\Users\Shiva\.jx\cloud-environments\env-minikube
process_begin: CreateProcess(NULL, uname, ...) failed.
The system cannot find the path specified.
The system cannot find the path specified.
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
"jenkins-x" has been added to your repositories
rm -rf secrets.yaml.dec
process_begin: CreateProcess(NULL, rm -rf secrets.yaml.dec, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
Error: Command failed  make ARGS=--values=C:\Users\Shiva\.jx\gitSecrets.yaml --values=C:\Users\Shiva\.jx\adminSecrets.yaml --values=C:\Users\Shiva\.jx\extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2  
```

I checked the .jx folder and the required folders are present inside it . Any pointers, to what could be the cause and where it should be fixed(even in code) will be helpful.

**Comment by bremnes** [comment]
@shivasaxena, I encountered the same issue.

The first problem is that "make" (build software usually used in unix systems) is not default installed in windows. So you've got to download/install that and add it to the PATH so that it's available for the installation. I downloaded the binary and dependency zips from [gnuwin32](http://gnuwin32.sourceforge.net/packages/make.htm) and added them to "c:\tools" which I've made [available to my PATH](https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho).

When that's been installed you might encounter the problem of a missing command "rm", which is a unix command for removing files. Instead of using the regular cmd/powershell I switched to bash which is installed as a part of [git for windows](https://git-scm.com/). Be aware that there seems to be a bug with the interactivity of the default terminal MinTTY/MSYS2, at least I had to [switch to using the regular command cli](https://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/).

That worked for me, drop a note if anything needs to be clarified.

**Comment by no-stupid-questions** [comment]
@bremnes, Thanks! that fix it for me, but now I'm getting stuck on later part in the "jx install":

https://github.com/jenkins-x/jx/issues/813[issue #813](url)

**Comment by blarojo** [comment]
Same here. Would be very useful to get the actual response of the failing command (or be able to execute with a --verbose option, so that we can fix without having to run the command manually

**Comment by jstrachan** [comment]
@blarojo btw I made all the helm commands use verbose logging for now so any helm related command failure should list all the error output now

**Comment by danizquierdo18** [comment]
any answer?

**Comment by ccojocar** [comment]
@shivasaxena  I am going to close this issue. The installation has improved in the meantime for windows. Please free to open another issue if you are facing this problem. Thanks
