### ISSUE TITLE
Why are tags being generated for pipeline artifacts when the pipeline fails in the first step? (Or, tags ready for releases should be differentiated from failed tags)

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#791]
I had a syntax error in a go application. The pipeline rightfully failed. A tag was generated 002. 

Another pipeline ran before I fixed the problem. Another tag was generated 003. 

See details at: https://github.com/junibutler/gojenx/tags

What's the business value for generating tags for failed pipelines? Is there any value in creating this audit trail? 

Even if you feel these tags should be generated, failed tags should be in a different color than good tags for fast visual indication to teams.

**Comment by jstrachan** [comment]
tags are created when changes are merged to master; though we're expecting folks to use Pull Requests to perform CI pipelines to validate changes before they hit master; to avoid tagging code that doesn't compile

**Comment by jstrachan** [comment]
I guess if a pipeline fails you can zap the tag; but we're hoping CI catches most of these errors before the merge to master

**Comment by junibutler** [comment]
yes i understand what you are saying @jstrachan. PRs are ideal and my only concern is that there is no way to enforce it. it can be confusing but at the same time, it is harmless confusion. 

perhaps, governance will take care of it some day. unless you have anything else to add, i can close this out. please let me know.

**Comment by jstrachan** [comment]
I guess the business value of generating tags whether a pipeline passes or succeeding is that it helps diagnose failing builds. If we removed tags on failing builds then a merge happens immediately after its going to be hard to diagnose why pipelines failed. The tag right now is an immutable snapshot of the code. Some releases fail. Some releases succeed but don't make it to production due to approvals or additional testing. Thats the Continuous Delivery way. With continuous delivery you keep moving forwards quickly so the idea of "0.0.2" being some magical fixed tag which you keep removing + adding again & keep repeating that loop until your app makes it to Production isn't really feasible any more. Its better to just keep moving forwards quickly, using immutable infrastructure + tags.
