### ISSUE TITLE
jx import should use git repository name for charts

### ISSUE THREAD

**Issue by sanketjpatel** [jenkins-x/jx#793]
When you do `jx import`, the generated `Makefile` in the `charts/${baseDir}` does the release for the helm chart with the NAME = $baseDir, while in the promote through all ‘Auto’ promotion Environments step, `sh 'jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)'`, jx autodiscovers the appName using the gitInfo. This is equal to the repository name, which may not necessarily be the same as the `baseDir` name.

IMO, we should use the git repository name, and not the baseDir name for creating charts.

Relevant methods in `pkg/jx/cmd/import.go`
https://github.com/jenkins-x/jx/blob/b1b110bd01acf80f74008c73f922de8be1ba0471/pkg/jx/cmd/import.go#L862

And `pkg/jx/cmd/promote.go`
https://github.com/jenkins-x/jx/blob/b1b110bd01acf80f74008c73f922de8be1ba0471/pkg/jx/cmd/promote.go#L454

**Comment by jrnt30** [comment]
We have our own internal, hacky version of something akin to Jenkins-X and ran into this problem as well.  People often have aliases or their own way of managing source that may not be 1-1 with the actual name they want to use "publicly".  

Ultimately we went with a `METADATA.yaml` approach to allow defining and customizing some of the default behavior and if a project didn't have one upon `import` then we would create one for them and make some sane defaults.

**Comment by ysaakpr** [comment]
I prefer it should be overridable while we importing. User should able to choose the name of your application rather than the source repo name or baseDir. because which is getting used to name the services as well.
1. If baseDir is getting used, use the same for promote as well
2. If git repo name is getting used use that for promote also
3. If a name which can be override on top of baseDir and git repo name , then support the promote also with that.

Looks like this is a broken feature. As of now you have to name the baseDir as same as your git repo and that will be your service name as well

**Comment by jstrachan** [comment]
so I've fixed the issue of the promotion not using the correct helm chart name. Right now the helm chart name is the `app name` or the `artifact id` when you create/import a maven project. So I think we're good to go - the promotion can handle an app name being different to the repo name and the user gets to pick both values which can be different
