### ISSUE TITLE
"Bootjob" task doesn't work in remote cluster

### ISSUE THREAD

**Issue by rupertgti** [jenkins-x/jx#7938]
Hi!

I think there is an error in remote cluster configuration and jx operations. I used: [Multicluster](https://jenkins-x.io/v3/admin/guides/multi-cluster/multi-cluster/) documentation and I created two kubernetes cluster in AWS. The process works with some repositories in the first (main) cluster but when I want a release of these repositories or I modified the jx-requirements in remote cluster, the bootjob tasks in remote cluster never finishes (it finished after 30min by timeout ;) )

![image](https://user-images.githubusercontent.com/9595550/130465720-d1656074-8a14-4947-8324-d0ca1a2e5ef8.png)
![image](https://user-images.githubusercontent.com/9595550/130469532-03218c4a-07ba-4a50-8f28-2241627ea994.png)

The finish log about this build:
```
+ echo 'viewing the git operator boot job log for commit sha: 937a6d0d45dd02d7bbe6bd944e58672e97ebeef5'
--
+ jx admin log --verbose --commit-sha 937a6d0d45dd02d7bbe6bd944e58672e97ebeef5
viewing the git operator boot job log for commit sha: 937a6d0d45dd02d7bbe6bd944e58672e97ebeef5
waiting for the Git Operator to be ready in namespace jx-git-operator...
pod jx-git-operator-75d5b6b469-2hkzp has status Ready
the Git Operator is running in pod jx-git-operator-75d5b6b469-2hkzp
--
waiting for boot Job pod with selector app=jx-boot in namespace jx-git-operator for commit SHA 937a6d0d45dd02d7bbe6bd944e58672e97ebeef5...
error: failed to wait for active Job in namespace jx-git-operator with selector app=jx-boot: timed out after waiting for duration 30m0s
--
Pipeline failed on stage 'from-build-pack' : container 'step-admin-log'. The execution of the pipeline has stopped.
```

1. The `jx admin log` it's `Succeed`
2. The `jx health status --all-namespaces` it's `OK`
3. My `jx version` is `3.2.127`
4. My kubernetes cluster version is `1.19`
5. My `jx gitops lint` It's `OK` in two cluster repositories
6. My `jx helmfile resolve` doesn't mark nothing

Apparently, the boot job process doesn't see the pod in remote cluster. Do you have any ideas? Is it a bug?
Thank you

Maybe it have relation with: https://github.com/jenkins-x/jx/issues/7761

**Comment by rupertgti** [comment]
Nobody else have this error with remote clusters? :(

**Comment by jrx-sjg** [comment]
Same here. The Dev environment is trying to read bootjob logs from Prod-remote environment but it can't.

This is a breaking issue. I "solved" it removing the jx-admin-log tekton step on the Remote repository, but that way we don't know when it finishes. Everybody wants to follow the operation on the UI rather than on console.

```
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: admin-log  <<< THIS
          resources: {}
```

**Comment by smerck** [comment]
I spent some time looking at this and I believe this boils down to two issues. I've been able to hack together a fix for this in my own environment (eks). For simplicity purposes, i'll refer to the cluster running jx/tekton/lighthouse as the "dev cluster" and the remote cluster as the "prod cluster":

1) `jx-admin log` uses the k8s service account presented to the pod to look for the jx-boot pod. Since It ends up using the credentials to access the local k8s cluster, but the jx-boot pod it's looking for actually runs on the remote cluster, it obviously never finds it and times out. To fix this problem, I created a custom step in my release pipeline that installs jx, aws, and kubectl clis. I pulled in the kubeconfig from aws (`aws eks --region XXXX update-kubeconfig --name XXXX`), and run the `jx admin log` against the commit sha (as seen in the admin-log step previously), but this correctly runs against the right cluster. 
2) The aws-auth configmap in the prod cluster has the mapRoles field that is populated with the role created by the [jx tf configurations](https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/cluster/variables.tf#L175-L183). However, for a request to call from one EKS cluster to another, the production cluster's configmap must have the dev cluster's tekton-bot role mapped to do this. 
old:
```
- "groups":
  - "system:bootstrappers"
  - "system:nodes"
  "rolearn": "arn:aws:iam::*:role/prod-cluster-role"
``` 
new:
```
- "groups":
  - "system:bootstrappers"
  - "system:nodes"
  "rolearn": "arn:aws:iam::*:role/prod-cluster-role"
- "groups":
  - "system:masters"
  "rolearn": "arn:aws:iam::*:role/dev-cluster-tekton-bot"
  "username": "tekton-bot"
```

After making these changes, i've been able to merge changes to our production cluster and view the `jx admin log` in the build logs as expected. I'm sure there's a _better_ way to do this, but I figured I would share this in case anyone else would find it useful.

**Comment by smerck** [comment]
There's a third piece of the pie here -- You have to add an IAM role to allow the tekton-bot role to assume prod-cluster-role. Per discussion on jx slack, i'm planning to add some docs around all the steps needed for this: https://kubernetes.slack.com/archives/C9MBGQJRH/p1637685695225600

**Comment by dicolasi** [comment]
This is still an open problem.

**Comment by msvticket** [comment]
I have simply removed the release pipeline in the git repos of my remote clusters. Security wise I don't think it's a good idea to let the dev cluster have access to a production cluster. Also I don't think it's needed. You can execute `jx admin log` yourself if you want to...

**Comment by babadofar** [comment]
The security consideration sounds very valid to me. What I don't understand is how can you then deploy to a remote cluster?

**Comment by babadofar** [comment]
The problem here is not that the boot log does not work, the deployments are update and all other stuff works ( on my machines), but the "admin-log" step never finishes, also, there are no logs returned into the dashboard anyway so it just sits and waits.

So, what you should do to "fix" this, is to remove the  admin-log step from the release pipeline 
in the cluster repo, the file .lighthouse/jenkins-x/release.yaml looks like this
```
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: admin-log
          resources:
```
change it to 
```
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}

```

**Comment by babadofar** [comment]
or just do what @msvticket says, remove the release pipeline. It is really not doing anything anyway

**Comment by rupertgti** [comment]
> The problem here is not that the boot log does not work, the deployments are update and all other stuff works ( on my machines), but the "admin-log" step never finishes, also, there are no logs returned into the dashboard anyway so it just sits and waits.
> 
> So, what you should do to "fix" this, is to remove the admin-log step from the release pipeline in the cluster repo, the file .lighthouse/jenkins-x/release.yaml looks like this
> 
> ```
>         steps:
>         - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
>           name: ""
>           resources: {}
>         - name: admin-log
>           resources:
> ```
> 
> change it to
> 
> ```
>         steps:
>         - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
>           name: ""
>           resources: {}
> ```

Thank you @babadofar but I think that information would be in the same place here -> [Multicluster](https://jenkins-x.io/v3/admin/guides/multi-cluster/multi-cluster/)

1 year ago we discard multicluster to avoid this problem to use argocd only in the part of release in other clusters

**Comment by gek0** [comment]
HI, any progress with this? We are experiencing the same issue.
Granting access from the dev cluster (where the build happens) to pre-prod and prod environments is not really an option.
And removing this step of the pipeline is not a fix, just hiding the issue and still having not deployment logs
