### ISSUE TITLE
create an app for the GitWebhookProxy for folks running behind firewalls

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#841]
see https://github.com/stakater/GitWebhookProxy

**Comment by rawlingsj** [comment]
on my recent travels in `Prow`  land I’ve stumbled across a github proxy which might be useful 

https://github.com/kubernetes/test-infra/blob/e3650ae/prow/cluster/ghproxy_deployment.yaml
https://github.com/kubernetes/test-infra/blob/e3650ae/prow/cluster/ghproxy_service.yaml

**Comment by msvticket** [comment]
I tried using GitWebhookProxy since our kubernetes setup isn't accessible from the public internet otherwise. The helm chart didn't work for me, but after some changes the configuration worked. Except that GitWebhookProxy doesn't support *not* having a secret configured for the webhook and jenkins-x don't set a secret... I added an option to disable validation in GitWebhookProxy. I've made a pull request. My changes can be found here:

https://github.com/deniedboarding/GitWebhookProxy

**Comment by msvticket** [comment]
For reference it might be good to explain why the supplied helm chart for GitWebhookProxy didn't work for me: My setup is a k8s cluster in aws that originally only had a loadbalancer in a private subnet. 

In the GitWebhookProxy helm chart the host you configure is used to create an Ingress. But this collides with the ingress for jenkins. Even if it had worked it would have been connected to the private load balancer. I resorted this by instead  removing the ingress and making the Service type Loadbalancer and adding the annotation "service.beta.kubernetes.io/aws-load-balancer: nlb".  So then an ELB is created in a public subnet.
