### ISSUE TITLE
Support kubernetes 1.25

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#8454]
Boot job logs show the following warnings
```
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
```

Running the boot job in kubernetes (k3s) 1.25, gives this error message:
```
error: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"
make[1]: *** [versionStream/src/Makefile.mk:320: kubectl-apply] Error 1
make[1]: Leaving directory '/workspace/source'
```

**Comment by ankitm123** [comment]
cron job stuff is all jx
PSP and autoscaling/v2beta1 comes from tekton, so if we upgrade we will be fine.

**Comment by ankitm123** [comment]
The latest release of tekton does not support kubernetes 1.25 yet, but the next release will support it.
https://github.com/tektoncd/pipeline/milestone/60

**Comment by aellwein** [comment]
@ankitm123 well, tekton 0.41 is released now

**Comment by ankitm123** [comment]
We just upgraded tekton in our version stream to 0.33.4, we will hopefully move to 0.41.0 in the coming months ...

**Comment by aellwein** [comment]
Meanwhile k8s is advanced to 1.26 GA and will soon be released in version 1.27. 
I'm just asking myself, if jx will ever support _current_ k8s release.

Please don't get me wrong: this is NOT a blame. I'm just wondering about priorities. 
FMPOV supporting current k8s version is more important, that having fancy feature XY on the roadmap.

**Comment by tomhobson** [comment]
@aellwein it's not really about that for us, as we aim to be supported on cloud providers (awk, aks, gcp). 

K8s 1.27.x isn't available on aks yet, the most recent version is 1.26.3 (uksouth). AWS is more behind than that, we're not chasing the latest version because we don't really have a good way to test it.

On this note, I've just done
lighthouse
jx-preview
jx

**Comment by tgelpi** [comment]
Our current GKE infra model defaults to the latest K8S version available which is now `1.25.7 `. Looked at modifying terraform to use version `1.24` but it gets a little sticky introducing a version variable into the current config. A version requires a new data source `google_container_versions`with some alterations to the existing resource `google_container_cluster` . The issue is when using this new data source you can't remove the default node pool (`remove_default_node_pool=true`). so you wind up with multiple pools... but at least you get version 1.24. Not sure if this type of config change is a suitable workaround.

**Comment by msvticket** [comment]
> `error: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"`

The problem is that in jx-boot we have version 1.21 of kubectl which tries to prune CronJobs with api version batch/v1beta1 (which doesn't exist in k8s 1.25). In this particular case I think 1.22 would suffice. But if we are to go with the Kubernetes recommendation of have a max version skew of +/- 1 between cluster and kubectl version we shouldn't have kubectl older than 1.24. I'll make a PR regarding that.

**Comment by aellwein** [comment]
> @aellwein it's not really about that for us, as we aim to be supported on cloud providers (awk, aks, gcp).
> 
> K8s 1.27.x isn't available on aks yet, the most recent version is 1.26.3 (uksouth). AWS is more behind than that, we're not chasing the latest version because we don't really have a good way to test it.
> 
> On this note, I've just done lighthouse jx-preview jx

@tomhobson this of course, but I don't think about complex production-grade scenarios on public clouds yet. 
A basic scenario: people just want to try jx and download rancher desktop or k3s in a recent version. 
Boom! Not a nice user experience at all.

**Comment by liangyuanpeng** [comment]
> A basic scenario: people just want to try jx and download rancher desktop or k3s in a recent version.
Boom! Not a nice user experience at all.

I agree with it.

**Comment by kespineira** [comment]
Hi there! Does anyone know how the support for new versions of Kubernetes is going? Versions 1.26 and 1.27 are now available on EKS, GKE, and AKS.

**Comment by jobcespedes** [comment]
Hi,

We are running JX on k8s version 1.26. We had two problems to solve. Other than that, it's been working fine. What we resolved was:
1) Use version >= `0.6.0` of the tekton-pipeline helm chart
2) Convert pipelines to use native tekton sintax (remove uses to import tasks). [This is one of the updated pipelines](https://github.com/krestomatio/container_builder/compare/26a571f7731ce0cee1ad01b2d4732ebdb7a01009..d6898828ddc8c15378665fc7f4faca897e0593e8?diff=unified#diff-4c9ea81d6f87421aa0c589d4fdc4a270361cd4e3835f5c5f15ff7dd9eb81d606)

**Comment by davidrmcgee** [comment]
Great news. I've been chasing this particular block for a few hours. Glad to hear that @jobcespedes is up and running. I am hoping that these instructions might lead to at least getting past the error with the outdated libraries using CronJobs of libraries that are out of compliance.

Working along. I updated the tekton-pipelines\helmfile.yaml as so.
`releases:
- chart: cdf/tekton-pipeline
  version: 0.6.0
  name: tekton-pipeline`

Note: tekton [has released](https://cdfoundation.github.io/tekton-helm-chart/index.yaml) version 0.29.0. 
  
I'm not sure that I follow the guidance for the second instruction, however. ("remove uses to import tasks") And, the number of changes in the example is daunting.

I think I am going to roll back to an earlier version. We will see what.

**Comment by jobcespedes** [comment]
About tekton helm chart, I found that there is some issues with the version numbers and dates. The last one seems to be 0.6.0 despite some other numbers like 0.29.0. Also version release dates seem to point to the same day.

To clarify about my second point regarding changing to native tekton pipeline syntax: jenkins-x offered a great functionality to import other tasks in the pipeline definition with `uses` (see example below). However, after upgrading, it did not work  and gave an error. So, I had to remove all instances of it. Looking for alternatives, I found `taskRef` from tekton api. However, using `taskRef` means different pods for each task imported. So, I had to define shared pvc between them. I ended up using 100% native tekton syntax in our pipelines. The link to diff from my previous were meant to exemplify those changes. Unfortunately, formatting and indentation changes were also applied in that commit, sorry.  The following is sample of what I found not to be compatible, at least when I upgraded:
```yaml
steps:
  # not working
  - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@1d617dda837673daa9fb677a31dd25fc0ff667d9
```

**Comment by davidrmcgee** [comment]
@jobcespedes outstanding help. For me, the chart update did not resolve the outstanding issue with the installation of jx failing due to the "invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1" make[1]: *** [versionStream/src/Makefile.mk:322" Until I overcome this defect, I won't be able to improve upon the pipelines. 

Thanks again!

**Comment by jobcespedes** [comment]
Oh I forgot about that. I had to use `jx-boot` prerelease version `3.10.86`: `ghcr.io/jenkins-x/jx-boot:3.10.86`. I changed to that version all instances  I found in `versionStream`. There is an issue open and a fix merged [here](https://github.com/jenkins-x-plugins/jx-gitops/pull/932). I am not sure if it has been released yet.

**Comment by davidrmcgee** [comment]
Thanks again, @jobcespedes. To ensure that I have understood. :-) 

I thought I might have to clone jx and rebuild it after updating `versionStream/src/Makefile.mk`. My plan was to update every reference for CronJob to use v1 of batch instead of v1beta1. However, I was hoping to avoid that clone/rebuild.

However, I think that you are proposing I rebuild `jx-versions`, upgrading references in that project for `jxboot` to `3.10.86` (in 4 job files)? I am hoping that you would not mind confirming. Moreover, I looked over that merge you offered. It appears to only update the default kubectl version. Is that is also required?  Am I misreading that?

**Comment by jobcespedes** [comment]
Yes, both 1) updating instances  of `batch/v1beta1` and 2) updating jx-boot, will help with the issues. 

About jxboot `3.10.86`, kubectl version update is what get rid off the issue, as suggested [in this comment](https://github.com/jenkins-x/jx/issues/8454#issuecomment-1538101803)

**Comment by jobcespedes** [comment]
I don't any guide, yet. From [this PR](https://github.com/jenkins-x-plugins/jx-pipeline/pull/521), I understand there is work in progress  to create tooloing for converting/migrating pipelines. Maybe @Skisocks could confirm. In addition, there is [Tekton docs](https://tekton.dev/docs/pipelines/pipelines/).

**Comment by Skisocks** [comment]
We're holding back on native Tekton for the time being as it appears that some work will have to be put into getting Tekton's git resolver up to the standard we'd require for jenkins-x. This is still very much in progress though as we'd really like to move to native Tekton.

We've got lighthouse working on Tekton 0.41.0 with both the `uses:` and native Tekton syntax and should have that out very soon. This removes the block we've had with upgrading to K8s 1.25+.

**Comment by tomhobson** [comment]
👋  Closing this as support is now completed! Thanks for all your contributions!

We're going to chase 1.27.x now as I agree with the k3s comment
